### ISSUE TITLE
long delay in coverage information becoming available through https://coveralls.io/builds/{commit}.json

### ISSUE THREAD

**Issue by cjw296** [lemurheavy/coveralls-public#1009]
Something seems wrong with:

https://coveralls.io/builds/13137716

All the jobs say "no data", but look fine from the travis side:

https://travis-ci.org/Simplistix/mush/jobs/272228715#L750

If I go to the json url for that commit hash, I get "None" for coverage:

https://coveralls.io/builds/7ffa16d4b07eea9e349b67cf5d609ad1fa2506ba.json

What's the best way to ask coveralls for the coverage results for a git commit?

**Comment by cjw296** [comment]
Interesting, that coverage percentage *now* shows 100%, but it didn't for hours after the build completed...

**Comment by cjw296** [comment]
Okay, so even 5 minutes wasn't long enough to wait:
https://travis-ci.org/Simplistix/mush/jobs/277490832

What's causing such long delays?

**Comment by robojeff** [comment]
Our team has been experiencing delays in test coverage getting reported on our GitHub PR pages.  It used to complete within a minute or so.  Now sometimes it never completes.  The problems started happening about 2 weeks ago.  We haven't modified our coveralls config files at all.

This is really aggravating.  Coveralls is useless to us until this issue is resolved.

**Comment by cjw296** [comment]
You'll have more joy emailing support@coveralls.io, nick@coveralls.io and lee@coveralls.io as they've confirmed this tracker is no longer monitored.

**Comment by robojeff** [comment]
Thanks Chris.
