### ISSUE TITLE
Local vs Live Coverage

### ISSUE THREAD

**Issue by lmckeen** [lemurheavy/coveralls-public#1054]
code coverage when local is showing as 100% but when live it shows as 99%... any reason for this? 

[reference repo if needed](https://github.com/theREDspace/HammerSpace)

**Comment by bytewalls** [comment]
I believe this issue is likely related to your coverage information being generated based on the transpiled typescript. 

You likely want to use a source map to remap code coverage results to your actual source. We are showing main.ts as having missing coverage because of missing branch coverage. I think this is likely due to something in how that file is being transpiled.
