### ISSUE TITLE
My private repo is getting mixed with someone else's repo.

### ISSUE THREAD

**Issue by julienbaley** [lemurheavy/coveralls-public#1058]
repo : TouchType/pika
I can see somebody else's build mixed with mine. This is a gross breach of privacy. Please fix immediately.

**Comment by julienbaley** [comment]
You mean coveralls? We're paying for it, so I hope not... (but we'll have to move away from it, then)

**Comment by LordDashMe** [comment]
yeah they're not responding to any issues here.

**Comment by julienbaley** [comment]
Isn't it the only contact method they offer, though?

**Comment by jgallen23** [comment]
I'm having the same issues. I'm wondering if its actually a travis issue though because if I run manually, the builds show up correctly, but if I run inside travis, I get somebody else's builds

**Comment by nickmerwin** [comment]
Hi all, seeing a public repo's builds in your private repo is a symptom of having `service_name: travis-ci` instead of `service_name: travis-pro`. No private data is being leaked the other direction.

More info here: https://docs.coveralls.io/troubleshooting#i-see-random-commits-on-my-travis-pro-private-repo
