### ISSUE TITLE
Do you support private repos in personal account?

### ISSUE THREAD

**Issue by gsogol** [lemurheavy/coveralls-public#1061]
We have 6 private repos with multiple collaborators and we currently have two issues:

Our CI setup uses Semaphore.

- We added `.coveralls.yml` file with the `repo_token`
- Coveralls is not showing all of the builds that happen in Semaphore
- Coverage report is not sent to Github even though the `coveralls/coveralls` status check is turned on. All we see is this: 
![image](https://user-images.githubusercontent.com/2625918/35335660-c8e040d2-00db-11e8-91ae-9cc578d5fed8.png)
- Our collaborators(in my private personal repos, not belonging to an org) cannot access the Coveralls report and it says Access not available.

Questions:

1. How do we show the coverage report as a comment on Github PR?
2. How do we enable access to our collaborators in private personal repos not belonging to any org?

**Comment by mvpspl619** [comment]
Any help here will be greatly appreciated.

**Comment by bytewalls** [comment]
Hi there, we do!

Sorry for the delay in getting back to you.

- In order for your collaborators to get access they will need to login to coveralls with their github account and click the `Sync Repos` button to gain access to private repos.
- To add github PR commenting you will need to enable `Leave Comments` for your repo as well as invite the [@coveralls](https://github.com/coveralls) account to your private repo in order for our bot to be allowed to comment on it. 

Hope this is helpful, please let me know if you have any questions.

**Comment by mvpspl619** [comment]
Jordan,

This is too late, we already switched to CodeCov. Very disappointed with
Coveralls paid support. Took you more than 2months to respond.


Thanks,
Raju

On Mar 15, 2018 at 5:22 PM, Jordan Oroshiba <notifications@github.com>
wrote:


Hi there, we do!

Sorry for the delay in getting back to you.

   - In order for your collaborators to get access they will need to login
   to coveralls with their github account and click the Sync Repos button
   to gain access to private repos.
   - To add github PR commenting you will need to enable Leave Comments for
   your repo as well as invite the @coveralls <https://github.com/coveralls>
   account to your private repo in order for our bot to be allowed to comment
   on it.

Hope this is helpful, please let me know if you have any questions.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lemurheavy/coveralls-public/issues/1061#issuecomment-373541699>,
or mute the thread
