### ISSUE TITLE
Pull Request comments for organization repo

### ISSUE THREAD

**Issue by HoelShare** [lemurheavy/coveralls-public#1062]
Hi,

I set up coveralls with travis-pro and it works very well on your web site. Now I setting up Pull Request comment.

In the docs you said "If you have a private repo that you would like to receive pull request comments on, you will need to allow pull access for our Coveralls bot". But actually what should i do?

We send the Coveralls bot @coveralls an invitation with "Read Access" days ago. But nothing has happened.
Just should I wait for the bot to accept invitation?

Thanks

**Comment by svenfinke** [comment]
This problem still persists.... Even 2 weeks later the invitation for the Bot was not accepted...

**Comment by ialisapient** [comment]
I followed the same docs as above, but added the bot as a collaborator with read only access (which worked), however, the PR comments do not seem to be working. (Same context: org repo.)

**Comment by clayreimann** [comment]
Same problem here too.

**Comment by nickmerwin** [comment]
@clayreimann I see that our bot accepted your https://github.com/yahoo/elide invite yesterday. Could you confirm? If not could you send another invite please?

Thanks!

**Comment by dpehrson** [comment]
@nickmerwin Does the @coveralls bot accept team invitations? I just set up a "Coveralls" team in our organization with read access to our first repo integrating coveralls and invited the bot to it. I'm curious the process by which it accepts these invitations and how long it will take.

Thanks!

**Comment by courtney-miles** [comment]
I submitted an invitation for "Read" access to https://github.com/coveralls for our private repo last year.  It is still listed as **Pending**.

Anything I can do to prompt it to accept? (seems posting here has worked for others.)

**Comment by keefertaylor** [comment]
I'm also curious about how to poke the bot into accepting my invite.

**Comment by cdimartino** [comment]
Is there a way to get Coveralls to accept the collaboration invitation I have sent it?

**Comment by afinetooth** [comment]
An update for anyone still experiencing this issue:

The [coveralls bot](https://github.com/coveralls) now automatically accepts invitations every 5 min, so if you're not receiving PR comments within 10-15 minutes, send an email to support@coveralls.io and someone will try to resolve the issue.

In order to receive PR comments, the [coveralls bot](https://github.com/coveralls) needs write permission on your repo. 

The traditional manner of adding collaborators to your (private) repo applies, so here's how to invite the [coveralls bot](https://github.com/coveralls):

### How to add the [coveralls bot](https://github.com/coveralls) to your repo:

1. On your repo, go to **Settings > Manage Access**.
2. Click **Invite a collaborator**.
3. Enter `coveralls`
4. Click **Add coveralls to [your-repo]**.
5. Coveralls will auto-accept your invitation within 5-10 min.*

_* Coveralls checks for new invitations every 5 min. If your invitation hasn't been accepted within 10-15 min, shoot us an email at support@coveralls.io and we'll accept manually._
