### ISSUE TITLE
Can't give coveralls bot comment permissions

### ISSUE THREAD

**Issue by tsiq-dastle** [lemurheavy/coveralls-public#1091]
The instructions state that to receive comments on pull requests, I have to give the @coveralls bot comment permissions on my private repo. After a bunch of Googling, I can't find clear instructions on how to do this.

I invited the bot as a collaborator on my repo. Is this what I am supposed to do? Is there an API I'm supposed to call?

Please help

**Comment by bytewalls** [comment]
Inviting the bot as a collaborator on your repo is correct. I will check and make sure that we have accepted that, in the meantime do you have `Leave Comments?` enabled in your repo settings? What CI provider are you using currently?

**Comment by nickmerwin** [comment]
@tsiq-dastle sorry about that, could you request @coveralls once more? The invite seems to have been revoked.

Thank you!

**Comment by nickmerwin** [comment]
Ok the second invite has been accepted. Thanks!

**Comment by afinetooth** [comment]
An update for anyone still experiencing this issue:

The [coveralls bot](https://github.com/coveralls) now automatically accepts invitations every 5 min, so if you're not receiving PR comments within 10-15 minutes, send an email to support@coveralls.io and someone will try to resolve the issue.

In order to receive PR comments, the [coveralls bot](https://github.com/coveralls) needs `write` permission on your repo. 

The traditional manner of adding collaborators to your (private) repo applies, so here's how to invite the [coveralls bot](https://github.com/coveralls):

### How to add the [coveralls bot](https://github.com/coveralls) to your repo:

1. On your repo, go to **Settings > Manage Access**.
2. Click **Invite a collaborator**.
3. Enter `coveralls`
4. Click **Add coveralls to [your-repo]**.
5. Coveralls will auto-accept your invitation within 5-10 min.*

_* Coveralls checks for new invitations every 5 min. If your invitation hasn't been accepted within 10-15 min, shoot us an email at support@coveralls.io and we'll accept manually._
