### ISSUE TITLE
Branches are not synced with Github

### ISSUE THREAD

**Issue by ArseniyAntonov** [lemurheavy/coveralls-public#1100]
Hello. 
We are using coveralls for Tarantool project 
https://github.com/tarantool/tarantool

We have branches like 2.0 and 1.9 for a long time, 
but these branches are still not available on coveralls page 
https://coveralls.io/github/tarantool/tarantool

`Sync branches` or `RESYNC WITH GITHUB` command didn't help.

Thank you.

**Comment by bytewalls** [comment]
Sorry for the inconvenience, we will investigate this.

**Comment by ArseniyAntonov** [comment]
@bytewalls 
Hello, is there any updates?

**Comment by bytewalls** [comment]
@ArseniyAntonov,

I believe the issue here is with the way the `coveralls-lcov` gem being used is being called. It looks like that gem does not automatically pull in the environment variables from travis to send to us, which means we don't have access to the travis build to establish branch information. For this reason, all current builds are being labeled as being built on `HEAD`.

In order to fix this I believe adding these flags to your call to coveralls-lcov: `--service-name travis-ci` and `--service-job-id $TRAVIS_JOB_ID` should fix your issues.

I've added a feature request to our board to update our coveralls gem to support lcov file uploads as well to hopefully better support this with our own built tools.

Hope this is helpful!
