### ISSUE TITLE
Coveralls showing data from another repository?

### ISSUE THREAD

**Issue by Hixie** [lemurheavy/coveralls-public#1103]
The source files listed on https://coveralls.io/github/flutter/flutter have nothing to do with our repo:
<img width="730" alt="" src="https://user-images.githubusercontent.com/551196/38517005-7b39cce8-3bed-11e8-92b2-cf9439f1f2bf.png">
<img width="730" alt="" src="https://user-images.githubusercontent.com/551196/38517008-7cbf2dd8-3bed-11e8-983c-55f49ce2d6bc.png">

The coverage numbers seem accurate, though.

**Comment by thanosd** [comment]
I'm seeing the same thing. Commits from a totally different repo. Private repo:

https://coveralls.io/github/savvymx/savvyanalysis

**Comment by anjin** [comment]
Hi!

Make sure you have "service_name: travis-pro" in your .coveralls.yml.

Travis uses non-unique job id's between its free and pro services, so if Coveralls doesn't know that your service-name is travis-pro, it looks up the info for those job ids using the free Travis API -- that's why they will show random commits and builds. Once your ENV var is set to specify travis-pro, the correct info will be pulled from Travis's pro API.

Conversely, no one will be able to see your private commits because the Travis-pro API requires special authentication via your Github OAuth token (whereas Travis free doesn't require any) -- the build ID mix-up can only go one way thankfully.

**Comment by thanosd** [comment]
Not so fast. ;)  I already that have in my config and still seeing the issue.

**Comment by thanosd** [comment]
Related: shouldn't coveralls be "smart" enough to see this is a different repo and suppress the information?

**Comment by Hixie** [comment]
I added the line suggested above, and it didn't fix it. If anything it made it worse, I'm not sure the numbers are correct anymore.

**Comment by Hixie** [comment]
@anjin I think this should be reopened. It makes coveralls useless to us, basically.

**Comment by Hixie** [comment]
@bytewalls any news?

**Comment by Hixie** [comment]
This is still broken. Flutter's coveralls page hasn't shown reasonable data since at least as far back as last April.

**Comment by Hixie** [comment]
Since this continues to be broken I guess we'll have to stop trying to use coveralls.

**Comment by xster** [comment]
I think there are 2 separate issues. 
https://coveralls.io/builds/21162782 etc are still showing the right per build data we're sending up to https://coveralls.io/api/v1/jobs. It's just not connecting to any metadata at the https://coveralls.io/github/flutter/flutter level. 

Behind the scene, what data does coveralls retrieve from various CI's APIs based on `service_name`? Can we provide everything that coveralls needs in one single post to https://coveralls.io/api/v1/jobs and not depend on any callbacks to any CI service?

**Comment by Hixie** [comment]
For what it's worth, we stopped using coveralls because of this issue.
