### ISSUE TITLE
Getting detached HEAD as the branch name

### ISSUE THREAD

**Issue by valendesigns** [lemurheavy/coveralls-public#1141]
Seeing branch names like `(HEAD detached at 1a1ecd3)` and it started doing this for all my builds in the last 24 hours. Any ideas on what's happening?

**Comment by bytewalls** [comment]
Thanks for your report, we found a bug in a recent deploy and deployed a patch last Friday for this issue.

**Comment by salaros** [comment]
Hi @bytewalls 
I'm still experiencing this issue [on one of my repos](https://coveralls.io/github/salaros/is-biz-mail-php):
![image](https://user-images.githubusercontent.com/675348/41847868-40b35480-7884-11e8-8163-c19a81e8b58b.png)

**Comment by salaros** [comment]
bump

**Comment by bytewalls** [comment]
@salaros Can you try removing the global `COVERALLS_RUN_LOCALLY` environment variable and let me know if that solves your issues? Running locally will result in it pulling the git information directly from the travis build environment and being report as `php-coveralls` service name. 

Travis does often run in a HEAD detached state as opposed to on the branch being tested. In order to solve this we integrate with the travis API for builds which occur on their service, identified by the service name. Most integration libraries can automatically detect and set this service name, but running locally will override that as your local machine isn't a service and it reports as `php-coveralls`.

**Comment by salaros** [comment]
You are right, it was `COVERALLS_RUN_LOCALLY=1` and `COVERALLS_REPO_TOKEN=<my token>` 😞 
probably when I tested Travis for the first time I haven't managed to get it working without these two variables, the strange thing is that locally it worked correctly (with vars set), but even if I did the same via `.travis.yml` it still failed to retrieve Git branch and `.coveralls.yml` in the root folder of the repo was ignored (mainly `service_name`)

**Comment by courtney-miles** [comment]
I'm having the same issue and have raised #1194 but have not received any support. I am on the verge of finding an alternative service, but am doing my best to exhaust all option before I do.

I'm using Coveralls with a private repo.  I don't have `COVERALLS_RUN_LOCALLY=1` set.  This is the contents of my `.coveralls` file.

```yaml
service_name: travis-pro

coverage_clover: build/logs/clover.xml
```

I'm using Travis CI to generate the coverage and [php-coveralls/php-coveralls:^2.0.0](https://packagist.org/packages/php-coveralls/php-coveralls) to send it. I have debugged php-coveralls and verified is correctly picks up the `service_name` from `.coveralls`.

Because it's a private repo, I have to use `COVERALLS_REPO_TOKEN` which is set as an environment variable in Travis CI.

**Comment by hxtree** [comment]
The same thing happened me. I ended up switching to Codecov, which badges don't look as good, but they seem to work. This issue stops the badge from updating as the URL states the head detach.
