### ISSUE TITLE
Question: No files covered

### ISSUE THREAD

**Issue by jbw91** [lemurheavy/coveralls-public#1148]
I'm having an issue reporting my coverage to coveralls. It successfully runs the tests and generates coverage using Jest, and it posts the lcov.info using `node-coveralls`, but it gives coverage unknown, with supposedly 0 files covered.

Here's the build: https://coveralls.io/builds/17665700

Here is the Travis build that posted the above coverage: https://travis-ci.com/jbw91/data-structures-ts/jobs/131033395

Would love to know if I've configured things incorrectly. Thanks!

**Comment by bytewalls** [comment]
@jbw91,

It appears as though the coverage being generated by jest and put in the lcov.info is listing the files as being at locations they are not at.  For instance when running tests it looks as though the lcov is pointing to `/src/double-node.ts` but this file is actually at `/src/common/double-node.ts`. 

I'm not sure what is flattening your file structure in your test setup for reporting, but if you fix that you should see the files pop up. The `node-coveralls` package checks to make sure the file exists before adding it to the json which is sent to coveralls. Otherwise the file structure in coveralls and in your actual file directories would not match.
