### ISSUE TITLE
Coveralls: New Coverage, Github Reporting, Missing Branches

### ISSUE THREAD

**Issue by suddenrushofsushi** [lemurheavy/coveralls-public#1153]
We appear to be having three (3) problems reported by other users here, and a fourth one as well:

### Issues at-hand:
1. We are no longer seeing New/Changed coverage details for our repo. (See: #1144 and #1126)
2. Coveralls no longer sends coverage information back to GitHub. (See: #1149)
3. When trying to browse our branches, only `master` and `staging` are visible, even after resync. (See: #1146)
4. All our builds are reported as belonging to staging or master, even though they are for many different branches with PRs. (All shiny and new)

### Additional details:
* This is for a private repo; see build: https://coveralls.io/builds/17819697 to find the repo and other pertinent details
* Travis is pushing information to Coveralls just fine (since we can track the build afterward)
* We're currently on the single private repo plan while we test coveralls integration
* I'm owner of the repo and organization on GitHub

- **Screenshots**
  * [Screenshot 1 - Coverage](#screenshot-1---coverage)
  * [Screenshot 2 - Missing coveralls information on Github](#screenshot-2---missing-coveralls-information-on-github)
  * [Screenshot 3 - Missing branches](#screenshot-3---missing-branches)
  * [Screenshot 4 - Everything is staging or master, even though they really aren't](#screenshot-4---everything-is-staging-or-master--even-though-they-really-aren-t)

#### Screenshot 1 - Coverage
Item 1 above (missing new/changed coverage) -- this is a PR that has its own branch, with numerous other commits... Coveralls reports it as First Build on Staging.. :dizzy: 
![coveralls-problem-new-coverage](https://user-images.githubusercontent.com/18706410/42344182-7eeb24c0-8069-11e8-9079-9ca4aa8545a2.png)

#### Screenshot 2 - Missing coveralls information on Github
Item 2 above -- we used to receive a third update in that list with the coverage information from Coveralls. We receive nothing, not even a pending message like in #1149
![coveralls-problem-github-integration](https://user-images.githubusercontent.com/18706410/42344169-77ac355a-8069-11e8-88e4-4a1f18a33b11.png)

#### Screenshot 3 - Missing branches
Item 3 above -- self-explanatory
![coveralls-problem-branches](https://user-images.githubusercontent.com/18706410/42344160-72841796-8069-11e8-9903-ffcd5803817a.png)

#### Screenshot 4 - Everything is staging or master, even though they really aren't
Item 4 above -- every build is listed as belonging to staging or master. Which are their targets for the PR, but not the branch the changes are on.
![coveralls-problem-only-staging](https://user-images.githubusercontent.com/18706410/42344147-6ba60088-8069-11e8-8d19-ae7ffef61cdb.png)

**Comment by bytewalls** [comment]
@suddenrushofsushi,

First of all thanks for your detailed report.

I believe all of these issues are linked to an OAuth issue, we are working on a solution but the issue seems to be specific to this account and not wider spread. I will provide a better update on our status for resolution here when we have figured out exactly what has caused the Oauth account to enter it's current state and have a direction forward.

As for how OAuth problem causes all these issues: Without access to Github we are unable to pull diffs which are required to figure out which lines have changed and thus, give missing line information. It also keeps up from creating GitHub build statuses, prevents us from pulling GitHub PR information which would fix the branch (it is falling back to what travis reports, and PR builds on travis are built on a merge commit for the branch you are merging into). As for the branch sync, that will only ever list the branches which we have record of, and also relies on pulling valid branches from GitHub. 

Sorry for the inconvenience, we will get this resolved as quickly as we can. Thanks for your time.

**Comment by suddenrushofsushi** [comment]
Alright, let me know if I need to do anything on this end.

Thank you

**Comment by bytewalls** [comment]
@suddenrushofsushi,

The OAuth issue has been fixed sorry for the inconvenience, it looks like only the third issue in your report is still and issue. We are digging deeper into this.

**Comment by alexbeltran** [comment]
Also experiencing missing branches in a private repo.

Build has branch information which does not appear in the main page. https://coveralls.io/builds/24999473 

Tried to resync with github.

**Comment by afinetooth** [comment]
Closing due to age and known fixes. Please open a new issue and refer to this one if you're experiencing something similar.
