### ISSUE TITLE
Github SAML SSO support for the Coveralls GitHub bot

### ISSUE THREAD

**Issue by vuspenskiy** [lemurheavy/coveralls-public#1161]
Hi guys,

Our company uses [SAML SSO](https://help.github.com/articles/about-authentication-with-saml-single-sign-on/) to authenticated at GitHub.

Is there a way to make the Coveralls bot use that? We may add your bot's public key for instance. Maybe there is an another way to authenticate: deploy keys, or authorize a GitHub app?

Very eager to see the bot's comments,
Vlad

**Comment by vuspenskiy** [comment]
@bytewalls, so is there any way for us to configure Coveralls to comment PRs and fail if coverage went down?

**Comment by robsonpeixoto** [comment]
News about it?

**Comment by SunStupic** [comment]
Any updates for this?

**Comment by GeoffreyPlitt** [comment]
Any update with SSO?

**Comment by afinetooth** [comment]
@GeoffreyPlitt yes! (This is an old one. We need to add this to our FAQ & Announcements, sorry.)

Coveralls.io supports SAML SSO. Let me explain how:

Since the only way to login to Coveralls.io is via OAuth through one of the major git hosting services (GitHub, Gitlab, Bitbucket), Coveralls leverages the SAML setup you have for your git hosting service.

So using GitHub as the example, use your SSO service, for example Okta, as you normally would to login to GitHub.com, then, while your new active SAML session is open, authenticate into Coveralls.io.

On the flip-side, if you authenticate into Coveralls.io _outside_ of the context of a valid SAML session, you will experience virtually no ability to use the Web App because your token will be rejected by GitHub as requiring SAML. So if you're having that experience, you'll want to re-auth through your SAML SSO service.

Here's a 1-pager you can share with your IT/SecOps team:
[Coveralls.io Authentication with SSO.pdf](https://github.com/user-attachments/files/18155977/Coveralls.io.Authentication.with.SSO.pdf)

**Comment by GeoffreyPlitt** [comment]
Gotcha thanks!

**Comment by afinetooth** [comment]
@GeoffreyPlitt I see I missed a key point here:

Regarding the **Coveralls Bot**, we do not have a way to ensure our PR Commenter bot authorizes through your SSO service, but the good news is that our [New GitHub Integration](coveralls.io/new-github-integration-beta) gets around this by using a GitHub App that leverages its own token and does not require a user-oriented token to perform actions like commenting on PRs.

**Switch to our New Github Integration**:
We recommend signing up for the [New GitHub Integration](coveralls.io/new-github-integration-beta). It's technically still in beta, but has been in production with thousands of users since May 2023. It will also become the default integration for all new accounts in early 2025.
