### ISSUE TITLE
First build on <branch> at %

### ISSUE THREAD

**Issue by laisti** [lemurheavy/coveralls-public#1167]
Hello!

I have setup default branch at Coveralls, let's say master. I made a new branch in GitHub. Then I made the first commit in a new branch. After build is finished I see "First build on <branch> at %" on my PR an GitHub.
Why it doesn't show me the comparison with my default branch master?
I would like to know if my PR increased, decreased or unchanged my coverage.

Is it a bug, or is it by design, or should it be some specific setting somewhere? So as I understood, coverage comparison is working inside one branch and not between new branch and default one.

**Comment by bytewalls** [comment]
@laisti,

Which integration library and CI service are you using? This can help us to troubleshoot what is going on. On PR builds, Coveralls will compare the coverage information between the commit for the build and the base commit from information pulled from GitHub. 

However, this is only done when the API request includes that PR information. If the build was complete before the PR was opened for instance, this information would not be generated, in part because we do not know how what commit to compare against without PR information (not all PR's are into the base directory branch).

**Comment by RickCarlino** [comment]
@bytewalls I am experiencing a similar situation. For the sake of demonstration, I wrote a stub function that has no tests to intentionally drop coverage. Instead of comparing itself to our default branch (`staging`), we think it is comparing coverage to itself (`intentionally_drop_coverage` branch).

Code available [here](https://github.com/FarmBot/Farmbot-Web-App/pull/1025). The issue started around the time we switched from Travis CI to Circle CI.

Thanks.

**Comment by TheFirstAvenger** [comment]
>However, this is only done when the API request includes that PR information. If the build was complete before the PR was opened for instance, this information would not be generated, in part because we do not know how what commit to compare against without PR information (not all PR's are into the base directory branch).

@joroshiba We are seeing this issue also. Is it possible for coveralls to use the default repo branch as the base comparison if no branch information is available? Alternatively, updating the comparison when that PR is opened would also be helpful. As it stands now, most of our single commit PR's are missing the critical comparison to master.

**Comment by mar-schmidt** [comment]
Having the same issue as described above

**Comment by jmonguilo** [comment]
Having the same issue... Using Github actions with `coverallsapp/github-action`.

Thanks.

**Comment by bryce-cahill** [comment]
I was also having this this issue and found that it was because I was not supplying a unique `service_job_id`. The [API Reference](https://docs.coveralls.io/api-reference) says that it is optional however, if I did not set it the pull requests would never link to the base commit which would result in the problem with "First build on..".

**Comment by dgw** [comment]
This should not be closed until the documentation correctly reflects that `service_job_id` isn't _really_ optional.

**Comment by afinetooth** [comment]
@dgw there are two (2) reasons it's helpful for us to close this issue:

1. While reported as a solution by one user (not the OP), the issue of getting "First build on <branch> at %" for a given PR build bears no consistent relationship to whether or not a user has specified `service_job_id` in their post to the API. It only relates to the fact that a base commit for the PR is missing from coveralls, for which there could be any number of reasons.
2. `service_job_id` is technically optional when you are building your own integration to coveralls. However, if you are using any of the [community-built language integrations](https://docs.coveralls.io/) found [here](https://docs.coveralls.io/), it may be that the particular integration has made `service_job_id` a requirement. The [Coveralls API Reference](https://docs.coveralls.io/api-reference) is meant to help users building integrations to the Coveralls API. It can also be helpful as a reference for end users to understand what's going on with their integration by examining the debug output in their CI build logs, when they've invoked their integration's "[verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v)."

We would rather let an issue stand if it either: 

- solves the original issue for _all_ users, or
- presents a _particular_ solution to a _particular_ issue.

**Comment by ankitm123** [comment]
> It only relates to the fact that a base commit for the PR is missing from coveralls

@afinetooth  Which argument can be used to set the base commit for the PR? Which values does coverall use to determine the base commit? I am using JenkinsX, so it may need a bit of manual tweaking at my end.

**Comment by afinetooth** [comment]
Hi @ankitm123. As I say above, it will depend on the integration, if you're using an existing one, but what I have seen most often is `service_job_id` mapped to the Jenkins env var, `BUILD_ID`.

Here's an [example](https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/getOptions.js#L47) from the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration:
https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/getOptions.js#L47

**Comment by ankitm123** [comment]
@afinetooth The link you posted is for Jenkins and not JenkinsX (which is a completely different CI/CD system - https://jenkins-x.io/). I did try setting service_job_id to build_id (this variable is available in JX), but that did not help.
Probably better to open a separate PR for this issue, as the original PR was for circle (or other supported CI providers) and JX is not natively integrated with coveralls, wdyt?

**Comment by afinetooth** [comment]
Hi @ankitm123. I agree. A new issue seems appropriate since this seems to relate to a new CI. I would have thought JenkinsX would be similar to Jenkins, and it probably is in many ways, but obviously this way doesn't resolve the issue.

When you submit the new issue, let us know what language you're using and what [coveralls language integration](https://docs.coveralls.io/) (see left-hand nav [here](https://docs.coveralls.io/)) you're using with Jenkins (if any). The github issues board for the integration is also a good place to start.
