### ISSUE TITLE
Show coverage of each package in a lerna monorepo

### ISSUE THREAD

**Issue by amaurymartiny** [lemurheavy/coveralls-public#1174]
I have a lerna monorepo containing several packages, and I run one test command on all the test files of all packages to get a global coverage. I then show a coveralls badge on my root README.

However, in the README of each individual package, I would also like to show the coverage of that package.

I was wondering how feasible this is.

**Comment by bytewalls** [comment]
@amaurymartiny, we don't currently have this functionality, I will add a feature request for the ability to get badges on a path basis to our board.

**Comment by giannif** [comment]
@aadityataparia any chance your repo is public and I can take a look? When I set up my monorepo, I decided to run `lerna run test` to run my `test` script in each package. I think I did this because I needed different `jestconfigs`. Wondering if you tried that approach and decided against it for any reason?

**Comment by aadityataparia** [comment]
@giannif I am using yarn workspaces, and wrote my own custom script to run tests in each package. 

https://github.com/sifrr/sifrr/blob/8bde3336df2dfe59e733604b91610412d21732af/scripts/test/runall#L11-L18

**Comment by amaurymartiny** [comment]
@giannif If you're interested, have a look at https://github.com/paritytech/js-libs:
- each package has a `yarn test` command which runs `jest`
- in the root package.json, I would have loved to run `lerna run test` to run all tests, but then I don't get the overall coverage, so I'm just running `jest` for now.

**Comment by YannickFricke** [comment]
@joroshiba Any updates on this? Would love to see it available! :)

**Comment by harshalthakre** [comment]
> I have a lerna monorepo containing several packages, and I run one test command on all the test files of all packages to get a global coverage. I then show a coveralls badge on my root README.
> 
> However, in the README of each individual package, I would also like to show the coverage of that package.
> 
> I was wondering how feasible this is.

How did you do that ? Do you have sample code for reference ?

**Comment by ionicsolutions** [comment]
You can generate coverage badges for your packages by submitting their coverage reports on specific branches.

It's a bit hacky and you won't be able to browse the code coverage on coveralls, because the paths don't match, but it is straightforward to set up. Have a look at [this repo](https://github.com/xai-demonstrator/xai-demonstrator/) and specifically on [how the coveralls report is set up](https://github.com/XAI-Demonstrator/xai-demonstrator/blob/master/.github/workflows/review-sentiment.yml#L54).

**Comment by dcharkes** [comment]
It seems somewhat inconsistent that there is support for monorepo in the repo settings, support for carryforward, but no support for a badge per package on a monorepo.
