### ISSUE TITLE
Clarification for Parallel Reporting

### ISSUE THREAD

**Issue by berfarah** [lemurheavy/coveralls-public#1178]
Hi! I'm trying to implement coveralls.io for my company and wanted to get some clarification around the webhook. According to your documentation, I should be sending you a payload that looks something like this:

```json
{ 
  "payload": {
       "build_num": 1234,
       "status": "done"
     }
}
```

to `https://coveralls.io/webhook?repo_token=$COVERALLS_TOKEN`.

Can you clarify what `build_num` corresponds to in your [api](https://docs.coveralls.io/api-reference)? Does `build_num` correspond to `service_number`? Or `service_job_id`? Can it be a string (given that those two are both strings according to your API's spec)?

Thanks in advance for helping me out!

**Comment by bytewalls** [comment]
@berfarah what ci service are you using? Many have an ability to make these request built in with a payoosd our systems know how to process (admittedly documentation in this area has room for improvement)

**Comment by berfarah** [comment]
Thanks for the quick reply, @bytewalls! We're using buildkite. From what I've seen in various libraries that you list for different language support, it looks like `service_job_id` tends to be `BUILDKITE_BUILD_ID` which is a uuid type string. We also have a number that's `BUILDKITE_BUILD_NUMBER` that we can work with.

**Comment by bytewalls** [comment]
@berfarah That will be the same as the `service_number`if it is available (otherwise we use the `service_job_id`). In our system a build is composed of multiple jobs, typically each job has a unique `service_job_id`, and those can be clumped together under a single `service_number`. This can be a number or UUID, both are acceptable. The important piece here is that jobs sent have a unique `service_job_id` and matching `service_number`, that `service_number` should be the `build_num` on the hit to parallel webhook.

We don't currently have automatic support for buildkite, but I will look into adding this (currently parallel webhook works out of the box with travis, circle, codeship, solano, and semaphore) you can always use the api as you have found documentation for though.

**Comment by berfarah** [comment]
@bytewalls Fantastic, good to know. So it doesn't matter if I pass in a string or a number to the webhook? Are the docs something I could update via PR or are they internal?
