### ISSUE TITLE
coverage unknown

### ISSUE THREAD

**Issue by vaibhavmule** [lemurheavy/coveralls-public#1185]
Masonite Framework uses @coveralls for code coverage but today when I made a pull request, the coverage:unknown and not showing the percentage, it is showing `?% `.

Link: https://github.com/MasoniteFramework/core/pull/296
Link to coveralls: https://coveralls.io/builds/18894456

When nothing is changed, it should just show current percentage instead of `?%`

**Comment by bytewalls** [comment]
@vaibhavmule,

When your coverage suite ran after this change it sent us no coverage data, all of the needed information except actual coverage data is included in the response we got from the API. 

Looking over the changes you made, the coveralls-python tool you are using to submit coverage requires you to have previously generated coverage files (which it then reports to Coveralls). Since you have moved reporting coverage to a separate build stage the residual coverage files likely no longer exist on which to gather and report the coverage to coveralls, hence the API request having no coverage information and the ?% coverage reading.

**Comment by vaibhavmule** [comment]
Thanks, @bytewalls for a brief explanation. 

P.S: It is my first using Travis Stages.
