### ISSUE TITLE
coveralls not showing organization

### ISSUE THREAD

**Issue by taktv6** [lemurheavy/coveralls-public#1186]
Hi there,

I have the issue, that I can't see the github bio-routing org in coveralls. 
On https://coveralls.io/repos/new I can see a few personal profiles and some other orgs. However, bio-routing is not in the list. I'm an owner of bio-routing and I've checked already, that my membership is publicly visible. Third party access for "Coveralls Pro" is also approved.

What the f**k is wrong here?

Thanks
takt

**Comment by czerwonk** [comment]
We could solve the issue by using the >>Update Github Access Settings<< function for the project. After another sync the org and project suddenly appears.  Since we already had one project of the org running with coveralls this is >>interesting<<.

![update_github_access](https://user-images.githubusercontent.com/88703/45265952-ad71c600-b453-11e8-8891-8e51d88b4679.png)
