### ISSUE TITLE
Source not available

### ISSUE THREAD

**Issue by nalinigans** [lemurheavy/coveralls-public#1188]
I just started using coveralls with our open source repository https://github.com/GenomicsDB/GenomicsDB, so this is probably a new user issue. I am not able to navigate to the source, I see _Source Not Available_. I did try setting the Git repo root directory, but that is not helping either. All filenames are absolute to begin with. 
Coveralls link - https://coveralls.io/github/GenomicsDB/GenomicsDB
How can I configure coveralls to get brows-ability working? I am open to suggestions.
Thanks.

**Comment by nalinigans** [comment]
Do we need to set up the coverall token with Travis?

Also, Codecov.io works great with the same set of clove generated files, but I like the coverall visualization a lot better. So any pointers to solving the initial issue will be helpful.

**Comment by bytewalls** [comment]
@nalinigans which tool are you using for coverage reporting? It looks as though the issue is one of the reported filepath, as you can see when you look at your code page it looks as though the reporter is reporting the absolute path on the server as opposed to the relative path for your code base. Essentially instead of reporting the filepath as, for instance `home/travis/build/GenomicsDB/GenomicsDB/src/main/jni/src/genomicsdb_GenomicsDBImporter.cc` the file path should be `src/main/jni/src/genomicsdb_GenomicsDBImporter.cc`
