### ISSUE TITLE
Coveralls not updating the coverage

### ISSUE THREAD

**Issue by ageekymonk** [lemurheavy/coveralls-public#1206]
Hi, 

  I am sending coverage details and it is not updated. https://coveralls.io/jobs/41274794
Can you guys help me with this

Thanks
Ramz

**Comment by williamcroberts** [comment]
I'm having similar issues with only the first build (Sep 26) data being displayed despite numerous uploads to the server.

Details on:
tpm2-software/tpm2-pkcs11#93

**Comment by senthilrch** [comment]
I am facing the same issue for my public github repo. I have coveralls integrated with Travis-CI. All was working fine till a couple of days back. Since yesterday, coveralls has stopped working, though travis-ci successfully launches the coveralls job. But the coveralls job has no coverage data. See here:-

- https://coveralls.io/github/senthilrch/kube-fledged

**Comment by drydmat** [comment]
@senthilrch What was the problem? I'm having this issue now.

**Comment by nickmerwin** [comment]
hi @drydmat could you link me to the repo in question?

**Comment by drydmat** [comment]
hi @nickmerwin unfortunately it's a private repo so I don't have a link to give.

We run tests from Circle and Coveralls gives back a status of 200 with a build URL so it's working in that respect but Coveralls is reporting no data for all the files for some reason.

**Comment by nickmerwin** [comment]
@drydmat ok you can email us here with the private repo details and we'll check now: support@coveralls.io
