### ISSUE TITLE
Can't access subscription settings

### ISSUE THREAD

**Issue by duerlund** [lemurheavy/coveralls-public#1231]
When we log in and go to [subscriptions](https://coveralls.io/subscriptions), it only says "Account managed by:".

**Comment by etiennebatise** [comment]
I am also experiencing this issue on a private repo that war recently moved to a GitHub organisation. 

![image](https://user-images.githubusercontent.com/5644956/104165526-c9a61900-53f9-11eb-95c5-08bbab420529.png)

**Comment by afinetooth** [comment]
@etiennebatise this is because the user who owned the subscription was deleted. 

Please note the subscription is also currently cancelled.

If you wish to start a new subscription you can do so by logging into https://coveralls.io and going to PRO SIGN UP > FINSPOT > ADD PRO.

If you need any help, please email us at support@coveralls.io. You can reference this issue for convenience.

**Comment by afinetooth** [comment]
@duerlund if you're still having an issue with your subscription, please email us at support@coveralls.io. Thanks.

**Comment by duerlund** [comment]
@afinetooth Thanks, we stopped using your service, and I kind of forgot this issue. Sorry for not closing it.

**Comment by afinetooth** [comment]
Ok, thanks, @duerlund

**Comment by etiennebatise** [comment]
@afinetooth Thanks for the quick feedback! 

As a feedback, I think would be great to provide a link to the documentation on the UI when this thing happen.

**Comment by afinetooth** [comment]
Thanks @etiennebatise, I've submitted a feature enhancement / change request to that effect.
