### ISSUE TITLE
Coverage decreased (-75.7%) to 0.0%

### ISSUE THREAD

**Issue by jay** [lemurheavy/coveralls-public#1256]
We have a coverage failure in curl/curl#3501 that says the coverage decreased to 0% but we're at a loss to explain why given the light change in the commit, and all CI is passing. The coverage report says "0 of 0 relevant lines covered (NaN%)".

/cc @bagder

**Comment by espoirMur** [comment]
Same thing here !!!

**Comment by hendrikmuhs** [comment]
Linking https://github.com/eddyxu/cpp-coveralls/pull/157 

TL/DR

If you have a C++ project and your coverage numbers go nuts after upgrading the compiler (gcc>=8), you might hit a bug in `cpp-coveralls` which parses gcov output wrongly after an upstream change in gcov.

I think this only applies to C++ code (so probably does not help the curl project), but whoever finds this issue, might find this information useful as this issue is tagged C _and_ C++.

**Comment by bagder** [comment]
We gave up on coveralls in the curl project. It was just not stable enough for us.
