### ISSUE TITLE
Coveralls bot not commenting

### ISSUE THREAD

**Issue by viniciuskneves** [lemurheavy/coveralls-public#1280]
Hello,

Yesterday I've setup Coveralls for my private organization repo. The coverage reports seem to be working as I can see them on Coveralls dashboard.

The problem is that the bot is not commenting the coverage reports back to my PR. I've granted READ access to @coveralls (only for the specific repository) and it has been accepted. I've also enabled comments on Coveralls repo settings. Will it only comment when I open PR to my default branch?

I'm currently using Travis CI + Coveralls.

Thanks in advance!

**Comment by viniciuskneves** [comment]
All of the sudden it started working now! 🤷‍♂️

**Comment by afinetooth** [comment]
An update for anyone still experiencing this issue:

The [coveralls bot](https://github.com/coveralls) now automatically accepts invitations every 5 min, so if you're not receiving PR comments within 10-15 minutes, send an email to support@coveralls.io and someone will try to resolve the issue.

In order to receive PR comments, the [coveralls bot](https://github.com/coveralls) needs `write` permission on your repo. (`read-only` permission, available through GH orgs, won't work.)

The traditional manner of adding collaborators to your (private) repo applies, so here's how to invite the [coveralls bot](https://github.com/coveralls):

### How to add the [coveralls bot](https://github.com/coveralls) to your repo:

1. On your repo, go to **Settings > Manage Access**.
2. Click **Invite a collaborator**.
3. Enter `coveralls`
4. Click **Add coveralls to [your-repo]**.
5. Coveralls will auto-accept your invitation within 5-10 min.*

_* Coveralls checks for new invitations every 5 min. If your invitation hasn't been accepted within 10-15 min, shoot us an email at support@coveralls.io and we'll accept manually._
