### ISSUE TITLE
coveralls c++ support with circleci

### ISSUE THREAD

**Issue by AndreasAZiegler** [lemurheavy/coveralls-public#1289]
According to a previous issue I created, I have to use the node-coveralls integration library to be able to use coveralls with c++ and circleci. As I'm not familiar with node, I don't see how I can use node-coveralls with my c++ project. Is there any tutorial or another c++ integration library that one can use for coveralls?

**Comment by nickmerwin** [comment]
Hi @AndreasAZiegler you can use the setup instructions here:
https://github.com/nickmerwin/node-coveralls

Since Circle comes with node installed, you'll just need add this line to your Circle config:

`npm install coveralls --save-dev`

Then add a the command at the end of your build to cat your lcov file to the coveralls exectuable:

`cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js`

Additionally you'll need to have `COVERALLS_REPO_TOKEN` environment variable set, and the executable will collect the other environment variables from Circle to pass along to the Coveralls API.
