### ISSUE TITLE
Golang files not appearing in Coveralls report

### ISSUE THREAD

**Issue by forstmeier** [lemurheavy/coveralls-public#1294]
### Description
I've configured a `travis.yml` file in my project [Heupr](https://github.com/heupr/heupr) but I'm only seeing three of the five files with actual code appearing in the Coveralls output [here](https://coveralls.io/github/heupr/heupr). Am I missing a configuration in the `travis.yml` file that would make sure all files are reported on?

**Comment by jakesylvestre** [comment]
Hey, did you manage to get this resolved?

**Comment by forstmeier** [comment]
@jakesyl I believe so but I honestly can't remember what the solution was. The repo has also gone through an entire rebuild since then so a lot has changed.

**Comment by afinetooth** [comment]
Hi @forstmeier, @jakesyl, just so I understand, are you saying the source file does not appear when you click on it's name in your source files table? Or are you saying some files are excluded from your coverage report / calculation?

If you want to paste the URL to an affected build we'll have a look. Otherwise, if you're concerned about privacy, you can email us at support@coveralls.io and reference this issue.

Thanks.

**Comment by jakesylvestre** [comment]
@afinetooth the latter. I managed to get this resolved with [go-acc](https://github.com/ory/go-acc)

**Comment by afinetooth** [comment]
@jakesyl got it. glad to hear it.
