### ISSUE TITLE
GitLab Subgroups are not supported

### ISSUE THREAD

**Issue by pkoz** [lemurheavy/coveralls-public#1303]
Subscribed to Pro just only to realize that Coveralls does not support GitLab Subgroups.
https://docs.gitlab.com/ee/user/group/subgroups

Repos from subgroups do not appear on the list or repositories.
An attempt to send a POST request to API ended up with "Internal Server Error"
An attempt to send the coverage from local ended up with "Couldn't find a repository matching this job."

Any idea about ETA for the support of GitLab Subgroups?

**Comment by afinetooth** [comment]
Support for GitLab sub-group repos was added in Spring 2019. 

I tested adding repos belonging to GitLab sub-groups today. Details below.

Closing the issue. 

---

**Details**:

I created a Group and a Subgroup in GitLab, where:

- **My Awesome Group** is the parent, and
- **My Awesome Subgroup** is the child of My Awesome Group.

Then I created a project belonging to each group/subgroup. (Both projects were public.)

Then I went to Coveralls and logged in via GitLab.

Then I visited ADD REPOS.

Then, after clicking SYNC REPOS, I was able to see both projects, which appeared like this:

- MY-AWESOME-GROUP305 / my-awesome-group-project-1
- MY-AWESOME-GROUP305 / my-awesome-subgroup/my-awesome-subgroup-test-project-1

**Screenshot**:

![Screen Shot 2020-07-15 at 5 22 29 PM](https://user-images.githubusercontent.com/918667/87612574-c4247c00-c6bf-11ea-9d29-23fd1d045037.png)

My use case:
- My groups are both public. 
- My projects are both public.
- I am using the standard / free version of GitLab. 
- I am using the free (free for public repos) version of Coveralls.

**Comment by afinetooth** [comment]
Some more follow-up here:

Given that you're a Pro user, you may be trying to access private gitlab repos belonging to private groups and subgroups. 

I tested that as well and was able to see private projects from private subgroups, when I upgraded to a paid subscription, and when that subscription was associated with the relevant gitlab group. (here, gitlab groups function like github orgs.)

here is my example result, after adding a private subgroup and private projects belonging to the public group I originally created above:

![Screen Shot 2020-07-17 at 6 35 01 PM](https://user-images.githubusercontent.com/918667/88000786-6fb04080-cab3-11ea-8d3c-54788d49ea6a.png)


note that this worked because i upgraded to a paid service level, Coveralls Org, to gain access to private repos, and the org / group i subscribed for was `MY-AWESOME-GROUP305`, the parent group of my new private subgroups and repos.

note also that to see the private subgroups and repos, on the ADD REPOS page, I had to click SYNC REPOS and, at one point, REFRESH PRIVATE REPOS.

hope it helps.
