### ISSUE TITLE
Coveralls bot not commenting on pull requests

### ISSUE THREAD

**Issue by vigenere92** [lemurheavy/coveralls-public#1313]
We added coveralls bot as a collaborator to our app - https://github.com/synup/app, but still the bot is not commenting on the pull requests, though coverage reports are generated and are visible on the coveralls dashboard.

**Comment by troex** [comment]
same for us on private repository attribution/attribution

**Comment by steveklebanoff** [comment]
Same.  Anyone resolve?

**Comment by supernintendo** [comment]
Same here, private repo in our case.

**Comment by rajaanova** [comment]
Was this resolved ? Any workaround for this.

**Comment by afinetooth** [comment]
@vigenere92 et.al., with other users this issue was rooted in permissions. can you verify that the user who owns the repo on Coveralls has write permissions on the repo? See this issue comment for context: https://github.com/zestedesavoir/zds-site/pull/5680#issuecomment-611301988.

**Comment by mad-it** [comment]
Maybe this is related? https://github.com/coverallsapp/github-action/issues/19

@afinetooth Coveralls GitHub action work perfectly fine for public repo's, but private repo's it does not comment.

Do you have any updates you could give surrounding this?

I have tried claiming the private repo in coveralls, but that did not remedy the comment issue.

**Comment by afinetooth** [comment]
An update for anyone still experiencing this issue:

The [coveralls bot](https://github.com/coveralls) now automatically accepts invitations every 5 min, so if you're not receiving PR comments within 10-15 minutes, send an email to support@coveralls.io and someone will try to resolve the issue.

In order to receive PR comments, the [coveralls bot](https://github.com/coveralls) needs `write` permission on your repo. (`read-only` permissions, available through GH orgs, won't work.)

The traditional manner of adding collaborators to your (private) repo applies, so here's how to invite the [coveralls bot](https://github.com/coveralls):

### How to add the [coveralls bot](https://github.com/coveralls) to your repo:

1. On your repo, go to **Settings > Manage Access**.
2. Click **Invite a collaborator**.
3. Enter `coveralls`
4. Click **Add coveralls to [your-repo]**.
5. Coveralls will auto-accept your invitation within 5-10 min.*

_* Coveralls checks for new invitations every 5 min. If your invitation hasn't been accepted within 10-15 min, shoot us an email at support@coveralls.io and we'll accept manually._

**Comment by flipace** [comment]
I think it would be great to add this information to the FAQ / Troubleshooting section on your site since it's a bit cumbersome to track down the issue on GH.

Also, it may be a good idea to add some "debug" info when looking at the coverage data for a commit so its clear "why" no PR comment is posted (eg a simple section "No PR comment sent due to no coverage data for the base commit" etc). This would help someone who's just configuring your service (like me 🙈 ) to not feel like it's all not working properly 👍

**Comment by afinetooth** [comment]
@flipace We've added those steps to the [Pull Request Comments](http://127.0.0.1:4000/coveralls-notifications#pull-request-comments) section of [Notifications](https://docs.coveralls.io/coveralls-notifications) docs. They'll appear there in a few days:

![Screen Shot 2020-10-09 at 11 44 14 AM](https://user-images.githubusercontent.com/918667/95620269-c3805500-0a24-11eb-90b3-3b28bc21eb55.png)

Also added an API feature request to our backlog, to include status of PR checks / comments to debug output.

Thanks for the suggestions.
