### ISSUE TITLE
Displaying smaller coverage than it's actual

### ISSUE THREAD

**Issue by bkielbasa** [lemurheavy/coveralls-public#1332]
This is a good example of the problem: https://github.com/go-bdd/gobdd/pull/32

Coveralls reports these lines https://coveralls.io/builds/25059786/source?filename=testhttp/setup.go#L39 as not covered but that's not true. Those lines are executed during the test but the code coverage says something different. When I run it locally, Goland shows the coverages about 84 % on file `setup.go`.

![image](https://user-images.githubusercontent.com/1235620/62704768-6cc85700-b9ec-11e9-8bd6-6cd2e56f2c11.png)

**Comment by afinetooth** [comment]
@bkielbasa since coveralls basically just reads the output from your CI build, a better place to look for an answer would be around any discrepancy between CI and local. 

For instance, perhaps a `goveralls` config variable would account the difference in coverage. An example of such a config setting might be `-covermode atomic` found in this [config example for GitHub Actions, here](-covermode atomic) vs. `-covermode=count` [here](https://github.com/mattn/goveralls#for-others).

Have you tried submitting an issue to the [goveralls](https://github.com/mattn/goveralls/issues) project?
