### ISSUE TITLE
Bot not posting comments on private repo PRs.

### ISSUE THREAD

**Issue by ellisio** [lemurheavy/coveralls-public#1348]
Hey folks,

I sent an email to support on 2019-08-23, and have yet to hear anything. So I'll post it here, perhaps the community has an idea.

> The bot has seemed to stop posting PRs to our private repos.
> 
> An example PR that just received the github status check, but not a comment, was this one:
> 
> https://github.com/salesmessage/arcadia-api/pull/415
> 
> The coveralls user is a member of our organization, and has "read" access to the repo.

Cheers

**Comment by ellisio** [comment]
Is there any public support for this product? No one is responding to emails, or this GitHub community.

**Comment by nickmerwin** [comment]
Hi @ellisio sorry for the delayed response. I checked that PR #415 and the comment was not added because the base build on master was not present on Coveralls: `e23e2c`.

Comments are only posted when we have the base build present in order to calculate the coverage delta.

It may be that you have your CI configured in a way to disable builds on master.

**Comment by ethanbray** [comment]
@nickmerwin can I recommend including that information in the documentation if it isn't already? I didn't see it anywhere.
