### ISSUE TITLE
Unable to sign up for Coveralls with Github!

### ISSUE THREAD

**Issue by plantpurecode** [lemurheavy/coveralls-public#1357]
When trying to sign up for a Coveralls account via my Github account, I land on the 500 error page when returning from the OAuth permissions page on Github.

https://coveralls.io/authorize/github/callback?code=[code-redacted]&state=[state-redacted] is the page throwing the 500. (I've intentionally redacted the code and state parameters since this is a public forum.)

**Comment by pklaschka** [comment]
I can confirm that I, too (since earlier today), land on a 500 page when trying to sign **in** with my GitHub account (a slightly different use case, of course, but it seems to be the same problem).

Some more details:
Accessed today at Fri, 27 Sep 2019 12:23:58 UTC from Germany, the request (`HTTP/2.0 GET` to the url mentioned by @plantpurecode) went to a remote address of `104.25.103.25:443` and resulted in a `HTTP 500 Internal Server error`, tested in the latest versions of Firefox and Chromium.

**Comment by nickmerwin** [comment]
Hi all, apologies for the outage -- we had a Redis server go down earlier today and are back to normal now.

Thanks.
