### ISSUE TITLE
coverage info not being reported back to github for few of the repository

### ISSUE THREAD

**Issue by rajaanova** [lemurheavy/coveralls-public#1369]
For few of the repository the coverage info is not getting returned to github. We see that the coverage being processed but its not being sent back.
One thing i noticed is the when the commiter is "web-flow" then coverage details is being returned.
Even the build number is proper.
But when the commiter is "Git hub" the coverage details is not being returned and build number is very high.
Dont know how this commiter is getting decided.
Note : I am using this for private repo.

I have started noticing this from last 15-20 days.

**Comment by rajaanova** [comment]
> For few of the repository the coverage info is not getting returned to github. We see that the coverage being processed but its not being sent back.
> One thing i noticed is the when the commiter is "web-flow" then coverage details is being returned.
> Even the build number is proper.
> But when the commiter is "Git hub" the coverage details is not being returned and build number is very high.
> Dont know how this commiter is getting decided.
> Note : I am using this for private repo.
> 
> I have started noticing this from last 15-20 days.

**Comment by rajaanova** [comment]
The solution was mentioned in https://github.com/lemurheavy/coveralls-public/issues/1149

**Comment by eyal0** [comment]
@rajaanova Did this fix the problem for you?  I am also seeing this problem.  My coverage is showing up correctly on coveralls.io website but I am not getting any updates in my github PRs.

What did you need to do in order to fix the problem?

**Comment by rajaanova** [comment]
@eyal0 For me the issue was fixed by recreating the coverall profile for the given repo.

**Comment by eyal0** [comment]
@rajaanova I tried to remove my repo from coveralls and add it again but it didn't help.  I can see my update in coveralls but I don't see anything written to my PRs.

**Comment by eyal0** [comment]
My problems started, I think, when I switched to github actions.  Previously, I used TravisCI.

**Comment by eyal0** [comment]
Seems like the problem happens when the PR is from a different repo than the target.  For example, I am trying to merge from eyal0/branch1 to pcb2gcode/master .  If I instead push to pcb2gcode/branch1 and then try to merge from branch1 to master, both in the pcb2gcode repo, then I get the status updates.

Maybe the github token that I get in one case versus the other has different permissions and that is the problem?  https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token

Maybe the GITHUB_TOKEN that is made with the foreign pull request doesn't have permission to add comments and make status updates so that is the problem?
