### ISSUE TITLE
GitHub Actions: PR comments are not being added

### ISSUE THREAD

**Issue by merlinnot** [lemurheavy/coveralls-public#1371]
Hi! I just bought a subscription, but unfortunately PR comments are not added to my pull requests at all. I double checked the configuration, but it seems fine. I also tried multiple options (compact/detailed view etc.). Here's a screenshot:

![Screen Shot 2019-10-30 at 18 53 44](https://user-images.githubusercontent.com/10390061/67884744-a1106700-fb46-11e9-941a-aefc773af98b.png)

May I kindly ask for assistance?

**Comment by eyal0** [comment]
I am also seeing this.

**Comment by ivasilko** [comment]
I just bought a subscription and running into the same issue. @merlinnot Were you able to solve it?

**Comment by merlinnot** [comment]
It only works for public repositories. So you might as well cancel your subscription, for public repositories it's free. Although I'd love to support the work people behind Coveralls put into this, there is just no way to communicate. As you can see, this issue hangs here for good four months.

**Comment by afinetooth** [comment]
@merlinnot for private repos, you'll need to manually add our commenter bot, [coveralls](https://github.com/coveralls), to your repo as a collaborator. That will allow `coveralls` to leave PR comments.

Working on improving docs on this. Thanks for your patience.

Closing for now. Just reply if you need follow-up.

**Comment by eyal0** [comment]
@merlinnot This is a problem with using GitHubActions.  I don't know if coveralls fixed it yet.

When a PR comes in, it gets github credentials that are read-only.  Those credentials get passed on to coveralls.  So coveralls is unable to use those credentials to modify the PR so you won't see the PR get updates.

Is anyone able to get coveralls to add comments into their PRs?

**Comment by mikeengland** [comment]
@eyal0 I am also experiencing the same issue with Github Actions. Did you manage to resolve this?

**Comment by mikeengland** [comment]
@afinetooth is this issue meant to be closed? I just saw that you assigned it.

**Comment by eyal0** [comment]
@mikeengland I didn't resolve it.  I'm not sure that it can be resolved!  Maybe adding the coveralls bot as a collaborator solves the problem?  That might be.  I'm not sure how to do that.

@afinetooth Do you have instructions on how to add the coveralls bot as a collaborator so that it can add those comments about coverage for public repos?

**Comment by mikeengland** [comment]
@eyal0 I couldn't get it to work after trying for a while. I started using the unofficial Python action here: https://github.com/AndreMiras/coveralls-python-action. The maintainer could get it to post in his example PR, but for some reason I couldn't on our pypika repository!

Coveralls itself is updated fine, it is just the comment back that fails.

**Comment by eyal0** [comment]
@mikeengland the GitHub token that you get when you run CI on a PR depends on the owner. If you make a PR in your own repo, you get a token with full privilege so coveralls is able to post a comment. But if it's a PR between different forks then it's a read-only token.

Maybe that's why it didn't work?

Yes, the update to coveralls doesn't require GitHub privilege. Only the posting of a comment does.

**Comment by mikeengland** [comment]
@eyal0 Thanks that makes sense. What I don't understand is why it worked when using Travis CI and running coveralls. For example here, https://github.com/kayak/fireant/pull/289.

**Comment by eyal0** [comment]
I don't know but I think that Travis is trusted by coveralls. So when Travis tells coveralls to post a comment, it will.

GitHub actions can be written by anyone. So there's no guarantee that the PR comes from the right repo. You could write code to litter other people's repos.

It's possible to add secret tokens to a repo. In theory that would let you put a secret coveralls token for CI. But it wouldn't work because someone could write a PR that modifies the CI to publicize the token!

GitHub already thought of that so PRs from others are not allowed to use tokens at all, only the read only GitHub action. So there's no way to put a secret token into a GitHub repo that would hand permission over to the coveralls server for writing comments. It's kind of silly because any user is allowed to add comments to a repo but the GitHub token has even less permission.

One solution would be for coveralls to simply trust the token. Maybe that would lead to a bunch of abuse, though. Who knows?

Another way that I proposed is to have a new class of secret tokens that can be used by CI but only if the CI workflow files are unmodified. So if the CI is secure, it would get the secret tokens. And if a user modifies it, whether with malicious intent or not, they would just get the read only version. So PRs that modify the CI wouldn't get coveralls updates but that hardly seems like a problem.

GitHub doesn't seem to be making any effort in any direction to fix this so for now, it's just a shortcoming of GitHub CI with which we need to live. I considered switch back to Travis but I preferred having fewer systems and GitHub allows more concurrent builds so it's faster.

This is really GitHub's problem for not providing a solution to the issue. Do you have any workaround ideas?

**Comment by mikeengland** [comment]
Thanks for the explanation! Unless some of the coverage tools e.g. Coveralls had some sort of official trust setup with Github then I am not sure there is an easy workaround.

**Comment by afinetooth** [comment]
> @afinetooth Do you have instructions on how to add the coveralls bot as a collaborator so that it can add those comments about coverage for public repos?

Sorry for the delay here, just wanted to provide these if it's still helpful to anyone with this issue.

Copy of:
https://github.com/lemurheavy/coveralls-public/issues/1062#issuecomment-632960914

### How to add the [coveralls bot](https://github.com/coveralls) to your repo:

In order to receive PR comments, the [coveralls bot](https://github.com/coveralls) needs write permission on your repo. 

The traditional manner of adding collaborators to your (private) repo applies, so the steps are:

1. On your repo, go to **Settings > Manage Access**.
2. Click **Invite a collaborator**.
3. Enter `coveralls`
4. Click **Add coveralls to [your-repo]**.
5. Coveralls will auto-accept your invitation within 5-10 min.*

_* Coveralls checks for new invitations every 5 min. If your invitation hasn't been accepted within 10-15 min, shoot us an email at support@coveralls.io and we'll accept manually._
