### ISSUE TITLE
how are relevant lines counted?

### ISSUE THREAD

**Issue by xieofxie** [lemurheavy/coveralls-public#1386]
I have seen different relevant lines from 20k to 30k for commits in same repo. Why do they change and what's the meaning of relevant lines? Thanks

**Comment by caleb15** [comment]
I have the same question - in https://coveralls.io/builds/33450052 I see that the coverage is 70.985% but the relevant line coverage is 74.59%. What is the difference between the two?

https://i.imgur.com/oJnPwct.png

**Comment by afinetooth** [comment]
@caleb15 I have an answer for you here.

We have a setting to INCLUDE BRANCH COVERAGE IN AGGREGATE %, which is checked by default:

![Screen Shot 2020-10-08 at 4 57 32 PM](https://user-images.githubusercontent.com/918667/95524853-5cf92980-0987-11eb-971b-32cf9922aa0d.png)

This means that if your code coverage tooling includes branch analysis, we read it and combine it into the final coverage %.

However, since the standard format, LCOV, does not supply aggregate numbers for branch coverage, only raw numbers, we treat each branch as a line and add it to the hit / missed counts. So in other words, the line % and branch % are not equivalent and therefore can't just be averaged.

That's why, given these coverage details:
https://coveralls.io/builds/33450052

![Screen Shot 2020-10-08 at 5 04 26 PM](https://user-images.githubusercontent.com/918667/95525189-54edb980-0988-11eb-9a3e-de8e5602505f.png)

The total percentage is not 51.1%, but instead 70.985%.

The formula is:

```
aggregate coverage w/ branches = (lines hit + branches hit) / (relevant lines + relevant branches)
```

In the above case:

```
aggregate coverage w/ branches = (109745 + 3379) / (147140 + 12224) = ( 113124 / 159364 ) = 70.985%
```

If you want to factor out branch coverage for a "cleaner" aggregate coverage number, you'll just need to uncheck the setting:

![Screen Shot 2020-10-08 at 5 12 46 PM](https://user-images.githubusercontent.com/918667/95526820-7dc27e80-0989-11eb-9ca8-0c964dcaeff2.png)

Hope that provides more clarity.

**Comment by afinetooth** [comment]
@xieofxie I'm going to close this issue for now in hopes that answer provides more clarity for you as well, but if you want to share an example of large differences in relevant lines between two commits in the same repo, please open a new issue and share the two coveralls build URLs. That'll help us asses quickly.

**Comment by caleb15** [comment]
Thanks. Do you know what coverage format includes branch coverage?

**Comment by afinetooth** [comment]
@caleb15 yes, LCOV supports it when the underlying tool is configured to measure branch coverage.

**Comment by afinetooth** [comment]
@caleb15 ah, you mean what tool supports _aggregate_ branch coverage analysis? Afraid I’m not familiar. I know that different languages (python, go, and others) have their own formats, but LCOV is the most universal standard.
