### ISSUE TITLE
random coverage failures

### ISSUE THREAD

**Issue by skeggse** [lemurheavy/coveralls-public#1427]
I'm running into what seems to be the same problem as #750:

```
[error] "2020-04-17T00:05:56.052Z"  'error from getOptions'
/home/travis/build/bee-queue/bee-queue/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Error: Command failed: git cat-file -p 530956486962d779831d40715c5c7a162844e3a4
fatal: Not a valid object name 530956486962d779831d40715c5c7a162844e3a4
```

See the [build log](https://travis-ci.com/github/bee-queue/bee-queue/jobs/320275111#L400-L406).

Anything I can do to make this more reliable?

**Comment by afinetooth** [comment]
hi @skeggse , I'm going to close this for age and because the nature of the error seems like something that could have been a one-off, or at least not related to our API:

> Error: Command failed: git cat-file -p 530956486962d779831d40715c5c7a162844e3a4
> fatal: Not a valid object name 530956486962d779831d40715c5c7a162844e3a4

I reviewed your project and see the last two builds look fine:
- https://coveralls.io/builds/34584848 (push)
- https://coveralls.io/builds/34584809 (pull_request)

Although I do see you switched to Github Actions for CI.

Let us know if there's something we can follow up on for you.
