### ISSUE TITLE
Coverage badge Says unknown even after build

### ISSUE THREAD

**Issue by srini-apty** [lemurheavy/coveralls-public#1429]
HI Team

Please have look at https://coveralls.io/github/aptyInc/apty-assist. This is a private project.

When go to the page I can see the coverage number but not the badge.

This is urgent as we have a GO/NOGO Decision pending for our paid subscription.

**Comment by afinetooth** [comment]
Hi @srini-apty,

Apologies, this is something that's not well-documented, but Coveralls needs a non-PR build on the repo in order to calculate change from a PR build and to display a badge. 

Looking at https://coveralls.io/github/aptyInc/apty-assist, it doesn't appear to have any non-PR builds:

![image (1)](https://user-images.githubusercontent.com/918667/80152043-d5059b80-856f-11ea-9a82-dfbd72b3f586.png)

One regular push to the repo, or the branch to which you're proposing to merge the PRs and you should get a numerical badge status.

Please try that and let us know if it doesn't resolve the issue.

**Comment by srini-apty** [comment]
Our Build process would only run if commit only comes from a PR. how do we deal with this.

**Comment by afinetooth** [comment]
@srini-apty looking at your latest builds it appears the issue is resolved. 

Builds on your dev branches are builds of type "pull_request" and builds on your default branch are of type "push":
https://coveralls.io/repos/297804/builds

![Screen Shot 2020-11-04 at 12 00 00 PM](https://user-images.githubusercontent.com/918667/98161856-4619fa00-1e95-11eb-952c-1f89065d0bc2.png)

And you're showing coverage % in your badge and atop your coverage table:

![Screen Shot 2020-11-04 at 11 58 31 AM](https://user-images.githubusercontent.com/918667/98161725-12d76b00-1e95-11eb-86b7-501108468e03.png)

Do you feel you were able to resolve the issue or that you had to perform an undesirable workaround. I would love to understand what your steps were if you don't mind sharing.
