### ISSUE TITLE
Files not Mapping to Repo

### ISSUE THREAD

**Issue by srini-apty** [lemurheavy/coveralls-public#1430]
HI Team

Please have look at https://coveralls.io/github/aptyInc/apty-assist. This is a private project.

The Files are not showing the proper hierarchy in the builds . Can you help us with the same.

This is urgent as we have a GO/NOGO Decision pending for our paid subscription.

**Comment by afinetooth** [comment]
Hi @srini-apty,

Apologies, this is something that's not well-documented, but Coveralls needs a non-PR build on the repo in order to calculate change from a PR build and to display a badge. 

Looking at https://coveralls.io/github/aptyInc/apty-assist, it doesn't appear to have any non-PR builds:

![image (1)](https://user-images.githubusercontent.com/918667/80152043-d5059b80-856f-11ea-9a82-dfbd72b3f586.png)

One regular push to the repo, or the branch to which you're proposing to merge the PRs and you should get a numerical badge status.

Please try that and let us know if it doesn't resolve the issue.

**Comment by afinetooth** [comment]
Hi @srini-apty,

It looks like you'll need to provide specific base directory as explained here:
https://coveralls.io/builds/30278277/source?filename=lens%2Fsrc%2FApp.tsx

![image (2)](https://user-images.githubusercontent.com/918667/80152347-58bf8800-8570-11ea-8823-3570018e80ed.png)

Please experiment with that and let us know if it doesn't resolve the issue for you.
