### ISSUE TITLE
Github: Do not ask access to private repositories in the case of Open Source plan

### ISSUE THREAD

**Issue by filip26** [lemurheavy/coveralls-public#1438]
current behavior:
1. find Coveralls on Github marketplace
2. select Open Source plan and click on install
3. Coveralls asks access to public and to private repositories

expected behavior:
1. unchanged
2. unchanged
3. Coveralls asks access only to public repositories

**Comment by afinetooth** [comment]
@filip26 sorry for the delay. sweeping through old issues.

thank you for the report. i have submitted a feature change request to not authorize for private scope when plan = Coveralls Open Source.

much appreciated.

closing for now due to age. feel free to follow-up for status here. no ETA, but 30-60 days is a reasonable timeframe.
