### ISSUE TITLE
Browsing source code gives 500 error

### ISSUE THREAD

**Issue by ioquatix** [lemurheavy/coveralls-public#1441]
Trying to browse:

https://coveralls.io/builds/21399462/source?filename=lib/async/terminal.rb

as linked from the coverage report gives me error 500.

**Comment by ioquatix** [comment]
This might still be an issue?

**Comment by afinetooth** [comment]
HI @ioquatix. The underlying issue here appears to be with the configuration of your parallel jobs.

Specifically, each of your jobs `248.1`-`248.4` makes four (4) separate posts to https://coveralls.io/api/v1.jobs.

(We only expect each job to make one (1) post to the `/jobs` API.)

Taking Travis Job 248.1 as an example:
https://travis-ci.org/github/socketry/async/jobs/487365388

You'll see these posts at these lines:

1) Line 1096:

```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #248.1
[Coveralls] https://coveralls.io/jobs/44735932
Coverage is at 86.43%.
```

2) Line 1182

```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #248.1
[Coveralls] https://coveralls.io/jobs/44735938
Coverage is at 89.61%.
```

3) Line 1391

```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #248.1
[Coveralls] https://coveralls.io/jobs/44735975
Coverage is at 81.41%.
```

4) Line 1883

```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #248.1
[Coveralls] https://coveralls.io/jobs/44735981
Coverage is at 92.29%.
```

See the [Coveralls API Reference](https://docs.coveralls.io/api-reference) for more on some of the parameters mentioned below:

What happens when you submit several jobs in a row with the same build number (`service_number`) and job number (`service_job_id`) is that we assume you mean to overwrite the previous one and replace it with the current one.

So in this case, only the _last_ of your four (4) jobs was taken as Job `248.1` and processed fully. And, as you can see, the coverage % for that job (`92.29%`) is the one that persists:

https://coveralls.io/builds/21399462

![Screen Shot 2021-08-05 at 10 39 08 AM](https://user-images.githubusercontent.com/918667/128395977-b4af9f8f-b5f6-42cb-a6a8-7d99a03af043.png)

Since each of your jobs is sending different tests, for what appears to be a separate set of files, the **404 error** likely means that we didn't get the reference to the file in the set of coverage stats that was kept. (_Note that [this source file link](https://coveralls.io/builds/21399462/source?filename=lib/async/terminal.rb) is actually throwing a **404 error** and not a **500 error**._)

In fact, I have searched for that file in each of your separate jobs, by entering the file name into SOURCE FILES > LIST > SEARCH and while the file appears in the _Build_:

**Build 248**
https://coveralls.io/builds/21399462
![Screen Shot 2021-08-05 at 10 50 47 AM](https://user-images.githubusercontent.com/918667/128397451-5acdf918-9a87-451d-90b2-185ce0d37642.png)

It does not appear in any of the build's _jobs_:

**Job 248.1**
https://coveralls.io/jobs/44735981
![Screen Shot 2021-08-05 at 10 51 34 AM](https://user-images.githubusercontent.com/918667/128397552-5ab883a6-6918-4f77-9441-29920ff8bcb4.png)

**Job 248.2**
https://coveralls.io/jobs/44735893
![Screen Shot 2021-08-05 at 10 51 56 AM](https://user-images.githubusercontent.com/918667/128397602-f164d11d-7f61-43fa-9fd1-94efd0f462f0.png)

**Job 248.3**
https://coveralls.io/jobs/44735912
![Screen Shot 2021-08-05 at 10 52 18 AM](https://user-images.githubusercontent.com/918667/128397662-d9cccc0f-e5db-4aec-b1c3-590fa0697c56.png)

**Job 248.4**
https://coveralls.io/jobs/44735961
![Screen Shot 2021-08-05 at 10 52 43 AM](https://user-images.githubusercontent.com/918667/128397714-d0acde97-018d-4555-a33c-6071b3536f41.png)

**Job 248.5**
https://coveralls.io/jobs/44735924
![Screen Shot 2021-08-05 at 10 53 06 AM](https://user-images.githubusercontent.com/918667/128397767-6660df03-4a1c-4ae4-a569-f2c6e8d380e1.png)

**Job 248.8**
https://coveralls.io/jobs/44736131
![Screen Shot 2021-08-05 at 10 53 45 AM](https://user-images.githubusercontent.com/918667/128397868-4e06a896-8eb0-4c72-8e45-1d0c739c7cfc.png)

TBH, I'm not sure where the build would have gotten a manifest that included the `lib/async/terminal.rb` file, but it's possible it came from either of the jobs between `248.6`-`248.7`, which seem to be missing.

The first step here is to look at your parallel jobs as configured and make sure you're only sending one discreet set of test results per job.

The second step will be to run the jobs in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) ([explained here](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v)) so that we have a reference to look back at if a future build repeats this behavior, where none of the parallel jobs contains a reference to a file shown in the build. (We can examine the actual JSON sent in each post to see if, where and how the file was referenced. Then we can make an API call for you with that reference to see what response we get back from the Github API.)

**Comment by ioquatix** [comment]
I think I know what happened, the test suite runs multiple other test suits, and I think those picked up the environment variables and submitted the travis data multiple times for the same job.
