### ISSUE TITLE
Different directory separators on Linux and Windows builds pollute results

### ISSUE THREAD

**Issue by danepowell** [lemurheavy/coveralls-public#1443]
I am reporting to Coveralls from PHP builds on both Linux and Windows machines (as part of a Travis CI build matrix).

PHPUnit prints paths in clover.xml using the directory separator for the current platform, i.e. `/` on Linux and `\` on Windows.

The problem is that Coveralls seems to interpret these as completely separate files. i.e. `src/MyFile.php` and `src\MyFile.php` are listed separately in the file list, even though they are obviously the same.

Additionally, clicking on the Windows-style path results in a "file not found" message.

I'm wondering how people normally deal with this. One alternative would be to disable reporting on Windows, but there's some risk there of not catching differing coverage between Linux and Windows. Ideally Coveralls would:

- Intelligently merge results from Windows and *nix builds, and/or
- Recommend against cross-platform reporting, and/or
- Provide guidance (documentation) on how we can manage this ourselves, such as by rewriting clover.xml to use Unix-style paths on Windows builds.

**Comment by afinetooth** [comment]
@danepowell sorry for the delay. Sweeping through old issues.

it looks like this was solved on your side, but in general, the code that converts your native coverage report (ex. LCOV) to JSON, for consumption by our API, would typically normalize the paths (path separators). looks like that's what your colleague did.

closing due to age. please just re-open if the issue persists.
