### ISSUE TITLE
Coveralls reports reporting inconsistent or wrong data?!

### ISSUE THREAD

**Issue by fingolfin** [lemurheavy/coveralls-public#1448]
The coveralls reports for our PRs used to be useful, but recently are almost completely useless (sorry, I can't say when exactly this happened).

I'll take https://github.com/gap-system/gap/pull/4032 as an example, as I know exactly which lines in our source code it should affect (I wrote it specifically to trigger a few previously uncovered code lines).

Coveralls added a comment to the pull request saying that
> Coverage increased (+0.003%) to 84.559%
which is plausible. Let's look at the report which is at https://coveralls.io/builds/30847890

Problem 1: I am pretty sure that this used to tell me at a glance at the top which new lines are covered now, and which lost coverage. Perhaps I am misremembering, though? Anyway, it only has a section `UNCOVERED EXISTING LINES` now which mentions one line that lost coverage (in the file `lib/string.gi`)... That doesn't really square with an *increased* coverage, though, does it? (The PR in question adds exactly one line of source code, so this isn't a case of "lots of previously uncovered code got removed; besides, every other recent PR on gap-system/gap that I expected had the same issue, so...)

OK, so let's inspect the source tree at the bottom of the report. Some things I notice:

Problem 2: it lists both `./src/FOO.c` files and `src/FOO.c` -- apparently some data is not normalized? Ah well, I guess I'll have to add code to further preprocess our JSON before we feed it to Coveralls (but e.g. codecov seems to be able to take care of such things automatically, would be nice if this was the case here).

Problem 3: the headers say: "LIST 760 - CHANGED 229 - SOURCE CHANGED 1  - COVERAGE CHANGED 229" yet when I click on e.g. "Source changed", it lists... nothing! Just the text "No data available in table."

<img width="878" alt="Screenshot 2020-05-18 at 15 43 41" src="https://user-images.githubusercontent.com/241512/82219994-5ad1f800-991e-11ea-86e8-984c24c25ebf.png">

The same holds for for  "Coverage changed".

Problem 4: For "Changed" it lists tons of files but what it reports makes no sense to me (it lists 136 entries, but the number of files which for which either content or coverage changed should be in the single digits). Where does this come from? I found no way to discover what is supposed to be changed about these files?

<img width="875" alt="Screenshot 2020-05-18 at 15 46 03" src="https://user-images.githubusercontent.com/241512/82220254-af757300-991e-11ea-871f-76baba905cdb.png">

Any pointers would be appreciated.

**Comment by ped7g** [comment]
Few weeks back (? cca) the coveralls web report stopped to show the differences in numbers and deltas - visible well on "Problem 4", this table used to display which numbers did change.

About your "Problem 4" - the coveralls report does count as "change" also different amount of passes through line, so if you add single new test testing only very specific part of source, but to launch it you pass through the general source, it will change the HITS/LINE numbers in many files which were not modified, but are used by the new test (my project is assembler and I'm using integration-like tests mostly, running the binary through main() and actually assembling source files, so when I add new test, I get plenty of new HITS/LINE for the core files).

But now my coverage reports look like this:
https://coveralls.io/builds/31030180  ( -> switch to "Changed 18" tab and there's no change-info), while it used to look like this:
https://coveralls.io/builds/30842706 ( -> switch to "Change 20" tab and there are also the deltas and highlights which values did change)
That's actually the last report where I have them, so that's from 17 May 2020 01:57PM UTC

Since then the info is not being rendered, is it bug or some intentional crippling of reports? (I guess I could have opened my own issue, but I decided to just comment here)

**Comment by afinetooth** [comment]
This was a known issue for some time back in Late-May/early-Jun and has now been resolved. Closing the issue.

**Comment by fingolfin** [comment]
Problem 2 and 3 are indeed fixed. But Problem 4 persists.
