### ISSUE TITLE
service_build_url and service_job_number are undocumented

### ISSUE THREAD

**Issue by fingolfin** [lemurheavy/coveralls-public#1450]
These keys are used in the code at https://github.com/lemurheavy/coveralls-ruby/blob/ecece72d423352432bcac2833952f352c2377350/lib/coveralls/configuration.rb

But https://docs.coveralls.io/api-reference doesn't mention them.

**Comment by martin-walsh** [comment]
Also undocumented is `service_branch` ?

Are these legacy fields, or should they be included?

**Comment by afinetooth** [comment]
Hi, @fingolfin @martin-walsh,

Those fields are non-required fields for which support has been added to help with certain of our community-contributed integrations. They have mostly to do with covering officially unsupported CIs, and were created as a convenience for developers extending their integrations to support those CIs.

So again, they are optional / not required, and you would likely only need to use them if you're using a CI not listed [here](https://docs.coveralls.io/supported-ci-services).

Here's a list of several of those fields. I think it covers the ones you've referenced, but if you have questions about others, let us know:

- **service_job_number** - is an optional non-unique job identifier; it's available if you want to identify each job yourself, and don't want them auto-numbered, or if you expect the jobs to run out-of-sequence and want to make sure they can be identified across builds.
- **service_build_url** - also optional; you can pass the return link to the job at your CI; it's otherwise inferred for the officially supported CIs.
- **service_branch** - this is an optional way of setting the branch; it should be the same as `git[:branch]` in the `git` hash, but if for some reason the git repo hasn't been checked out at CI build time, this is a simpler way of setting it than building up the `git` hash.

To answer your more specific question, these are not legacy fields, they just extend beyond those officially supported by the API. They are not deprecated, and we will continue supporting them in the foreseeable future, but as they don't relate to our officially supported CIs, we reserve the right to discontinue support, which we'd likely only do if we're providing an alternative means of achieving support for additional CIs.
