### ISSUE TITLE
Is there a way to see difference in coverage on line-level?

### ISSUE THREAD

**Issue by thoni56** [lemurheavy/coveralls-public#1453]
Once you find a file with difference in coverage between two builds, the next question is "which lines" had differences in coverage.

I tried the documentation, but could not find any information about the "UI" there, neither was this question covered as far as I could see.

**Comment by afinetooth** [comment]
@thoni56 are you not able to see line level changes when you go here in the UI?:
**Repo > Build > Source Files On Build > Coverage Changed**

You should be able to open any file under **Coverage Changed** and see github style +/- changes in green and red. 

Ex:

![Screen Shot 2020-06-01 at 4 00 23 PM](https://user-images.githubusercontent.com/918667/83462808-01d78900-a421-11ea-9f4c-a50eb746ef77.png)

**Comment by thoni56** [comment]
Yes I can see those lines. But I thought red means "no coverage" and green means "covered" as indicated by the exclamation mark at the end of non-covered lines and a hit count on green lines. And I think of that as "in this build".

I can't see that as a diff compared with last build. Or am I misunderstanding something completely?

To be clear, I wanted a view which shows which lines have lost coverage as compared to the previous build.

**Comment by afinetooth** [comment]
@thoni56 I think the issue is that we only show the diffs for PR builds. If you submit a PR-based commit, your build should show a couple of additional things:

First, directly below the coverage summary, you'll see a table of diffs, broken into "new missed lines in diff" and "uncovered existing lines", like this:

![Screen Shot 2020-06-02 at 10 58 51 AM](https://user-images.githubusercontent.com/918667/83553435-0c952b00-a4c0-11ea-92d1-2e8edbb597ca.png)

Those show you _your_ changes to those files and coverage changes relative to those new lines. You can click on files there to see the diffs in those files. (I'll get to how those look below.)

Second, under Source Files > Coverage Changed, you'll see two additional components:

**Comment by afinetooth** [comment]
@thoni56 you're right. I had to clarify this for myself. I'm familiar with a couple of other indicators on source files, but have since learned they only relate to files with diffs, and only apply for PR builds. I'll explain those below. They may help with some of what you're looking for.

In the meantime, I've confirmed we don't provide line-by-line _changes_, only file-level _changes_ and line-by-line _coverage_. Explaining "why" will take more space and, as I want check some of my assumptions, I'll wait until I'm better prepared to share that here.

As it regards PR builds, we provide a little more information on changed files. It won't give you everything you want, but it will tell you a little more about _your_ changes and how they affect coverage. 

Specifically, if you submit a PR-based commit, your build will show a couple of additional things:

1. Directly below the coverage summary, you'll see a table of diffs, broken into "new missed lines in diff" and "uncovered existing lines", like this:

![Screen Shot 2020-06-02 at 10 58 51 AM](https://user-images.githubusercontent.com/918667/83553435-0c952b00-a4c0-11ea-92d1-2e8edbb597ca.png)

Those files will also appear in the table of **Coverage Changed** files, where:

2.A. You'll see them indicated by a pencil:

![Screen Shot 2020-06-02 at 5 38 38 PM](https://user-images.githubusercontent.com/918667/83582979-e68b7d00-a4f7-11ea-8b17-d1307d1eb213.png)

And upon viewing their source...

2.B. You'll see additional line-level information, showing when NEW lines are UNCOVERED:

![Screen Shot 2020-06-02 at 5 47 34 PM](https://user-images.githubusercontent.com/918667/83583411-24d56c00-a4f9-11ea-87c2-156b9fb384ab.png)

And EXISTING lines remain UNCOVERED:

![Screen Shot 2020-06-02 at 5 42 07 PM](https://user-images.githubusercontent.com/918667/83583137-6285c500-a4f8-11ea-9efa-8703968f1dc1.png)

As I learn more about why we (and AFAICT other services) don't show line-level _changes_, I'll share that, with the likelihood of seeing it in a future release.

**Comment by thoni56** [comment]
Thanks @afinetooth for that thorough explanation. I'm very fond of trunk-based development for several reasons, but can also see the reasoning for prioritizing this for PR:s.

I'm glad that I did not misunderstand anything, and actually the need isn't that pressing. On trunk based development you would pretty much know what changed the coverage, namely the changes ;-)

In my case I have random falling coverage, but I think that is because of some tests needing to run the same binary in two instances simultaneously. I have not yet found a way to avoid the potential clash when gcov writes coverage data in the same .gcda. So I am assuming this is my root problem. But this made me curious if I could see what, where and when this happens using the coverage info.

Again, thanks for the explanation. I'll leave this open for you to close when you feel it serves no informational value any longer. E.g. this is explained somewhere else ;-)

**Comment by afinetooth** [comment]
Thanks @thoni56. Closing for housekeeping reasons, but the informational value should remain for users searching on key terms / topics / labels. Thanks again.
