### ISSUE TITLE
How to cover closing brackets of a method?

### ISSUE THREAD

**Issue by escopecz** [lemurheavy/coveralls-public#1454]
Coveralls shows 1 new uncovered line in this class. Here it's how it looks like:
![Screenshot 2020-06-03 at 12 54 33](https://user-images.githubusercontent.com/1235442/83631669-2c9b1c00-a59e-11ea-8e96-1657adc57cd7.png)

I believe that is Coveralls bug. Or please let me know how to cover it.

**Comment by afinetooth** [comment]
Hi @escopecz,

The designation of a line as relevant (and therefore uncovered) is the responsibility of the test coverage library you're using (for instance, Simplecov for Ruby).

Coveralls just reads the results of the coverage report and displays them (we don't calculate them); so you'd have to investigate what your test coverage library is reporting.

If you run the coverage report locally, you should be able to see the same designation of that line as "relevant," even though it may not be.

You may be able to tweak the configuration of your coverage library so that it ignores lines that are essentially meaningless to you.

If you do run that locally and see something different for that line, let me know and I'll look into the discrepancy.

Hope it helps,
James

**Comment by escopecz** [comment]
The question is why did Coveralls mark that line as "UNCOVERED EXISTING LINE" in the coverage report for my PR. I did not touch the `findParentFieldInForm()` method at all in my PR.

BTW, there are other uncovered existing lines in the file. I don't understand why it's reporting just that one and not all. Or maybe I don't understand what is the "UNCOVERED EXISTING LINES" report for.

![Screenshot 2020-06-04 at 10 51 11](https://user-images.githubusercontent.com/1235442/83735993-54978780-a651-11ea-9411-08e9d5a5dd07.png)

**Comment by afinetooth** [comment]
To clarify, the UNCOVERED EXISTING LINES report just highlights uncovered lines in files that were changed in the last PR commit. They're the same as uncovered lines in regular source files, they just happen to be highlighted this way in files that have _changed_. They are shown with "UNCOV" to distinguish them from _newly added_ lines that are also uncovered, which are annotated with, "NEW."

(As a side note, the NEW UNCOVERED LINES and UNCOVERED EXISTING LINES reports currently only appear for PR-based builds.)

You ask why Coveralls marked that line as an UNCOVERED EXISTING LINE. It only did so as directed by the coverage report it received for the file. Your coverage library is what _determined_ the line was uncovered. Forgive me for stating the obvious, but I just want to establish the reasoning for my answer to your initial question:

You're saying the `findParentFieldInForm()` method did not change, which I understand. The question is whether your _test coverage library_ considered that line uncovered in the base branch as well. (Maybe it did. One way to find out is to run a local report in the base branch.)

For the sake of argument, let's assume it didn't, and that the base report considered that line COVERED, or NOT RELEVANT. There _are_ scenarios in which existing code suddenly goes uncovered between two commits. One example is tests being removed. Another is a change to tests or test data that locks down the value of a conditional, such that one or more of a method's conditional branches stops getting tested.

Codecov lists some reasons for what it calls "[unexpected coverage changes](https://docs.codecov.io/docs/unexpected-coverage-changes#reasons-for-unexpected-changes)":

> 1. Adding or removing tests.
> 2. Failing to upload coverage reports.
> 3. Time sensitive tests.
> 4. Missing coverage reports or failed builds.
> 5. Dependencies changed resulting in a different execute plan.
> 6. Encrypted variables may prevent some execution paths.

I can't speak to what may have changed in your commit, unless you want to link me to it and I can have a look (and have access to the source files, which would have to be public).

I hope this is helpful. I know it can be frustrating trying to understand why certain code lines got marked as they did.

And all this said, if a local run of your test coverage library, or output from your CI, shows that your coverage results are indeed _different_ from what Coveralls displays, then by all means, we will look into that as a bug on our side. And I'm not ruling that out, either. I would just need the output from your coverage report, for that file, _before_ it reached Coveralls, in order to compare.

**Comment by escopecz** [comment]
Thank you for your response. I generated clover.xml file with the same command and driver we use in our CI. When I search for the `findParentFieldInForm` method then this is the result on base branch:
```xml
        <line num="1002" type="method" name="findParentFieldInForm" visibility="private" complexity="4" crap="4.05" count="7"/>
        <line num="1004" type="stmt" count="7"/>
        <line num="1005" type="stmt" count="1"/>
        <line num="1008" type="stmt" count="6"/>
        <line num="1009" type="stmt" count="6"/>
        <line num="1010" type="stmt" count="6"/>
        <line num="1011" type="stmt" count="6"/>
        <line num="1014" type="stmt" count="0"/>
```

and this is on my PR:
```xml
        <line num="917" type="method" name="findParentFieldInForm" visibility="private" complexity="4" crap="4.05" count="7"/>
        <line num="919" type="stmt" count="7"/>
        <line num="920" type="stmt" count="1"/>
        <line num="923" type="stmt" count="6"/>
        <line num="924" type="stmt" count="6"/>
        <line num="925" type="stmt" count="6"/>
        <line num="926" type="stmt" count="6"/>
        <line num="929" type="stmt" count="0"/>
```
The report is here: https://coveralls.io/builds/31241400

But the source code is in a private repository for now. I will push it back to the open source project once we will test it internally, so the source will be publicly accessible in a week or 2.

**Comment by afinetooth** [comment]
@escopecz sorry for the delay.  Thanks for the update. I see those two reports indicate identical coverage between your PR and the base, _for that method_. However, in comparing the two files the difference may still be relevant _at the line level_. 

I'll close the issue for now. If, when the project is open, you'd like me to look at the source and run locally, just reply and I'll re-open.
