### ISSUE TITLE
invalid source is analysed

### ISSUE THREAD

**Issue by bluebird75** [lemurheavy/coveralls-public#1457]
My project is bluebird75/luaunit .

For the build 428, the coverage went down from 98% to 36% . When looking at the coverage detail (see https://coveralls.io/builds/31452707 ) the source is actually from another project (a django project obviously). This explains the dramatic decrease.

There is something wrong going on...

**Comment by afinetooth** [comment]
@bluebird75 we see it happen sometimes that projects built on Travis CI cross-pollinate. It's because Travis uses non-unique job IDs between its free and pro services. (We cover it as a common issue, [here](https://docs.coveralls.io/troubleshooting).)

Normally, the problem is reported by a travis-pro user and the fix is to declare "service_name: travis-pro" in your .coveralls.yml file.

In your case, you appear to be a travis-ci.org user ("service_name: travis-ci"), so we're uncertain how this build got to you, but the pattern indicates it's another travis build containing a job ID of 428.6 that was run on Jun 15, 2020.

Interesting details on your original build with job 428.6 include that it is based on an [old commit on your project](https://github.com/bluebird75/luaunit/commit/d7586a13227d30aa1a129ba847a722e2b108159d), from Mar 4, 2018, and that the [build failed at travis](https://travis-ci.org/github/bluebird75/luaunit/builds/349042840) on that date; so we never received it back then. 

Why we would now, we're still investigating. All we're sure of at this point is that we got a POST to our /jobs API on Jun 15 that thought it belonged to your project (but contained source files unrelated to your original build/job).

We think you're probably safe to delete that build and move on, but it might be worth checking with Travis to see if they have any insights.

Hope it helps.

**Comment by bluebird75** [comment]
Thanks for the feedback. Things are back to normal now.
