### ISSUE TITLE
We don't receive Coveralls' hook since 5 hours ago

### ISSUE THREAD

**Issue by luisdalves** [lemurheavy/coveralls-public#1474]
Hey guys,

Again we are facing some delays, we don't receive coveralls' hook since 5 hours ago for one of our repos. Coveralls Status page is not reporting any issues on going.

Is there any way to know what's happening? We have reported the same behavior in less than 30 days on issue #1460.

We depends of this report to merge our code and this issues is causing a lot of delays for our CD pipeline.

Our org is: tiendanube.

Thanks!

**Comment by afinetooth** [comment]
Hi @luisdalves,

Yes, apologies, our [status page](https://status.coveralls.io/) now reflects an incident we are currently addressing. It was not there at this time yesterday.

This is the same performance issue referenced in https://github.com/lemurheavy/coveralls-public/issues/1460, but some of the effects have changed and so has our response.

We have some special infrastructure needs and, while we have been attempting an infrastructure upgrade for the past two (2) nights, we have not been successful due to an inventory limit on our instance type in our region. We have been working with AWS on this, but we've still not been able to remove the blocker.

We are scheduled again for a third attempt tonight 12-3AM PST. You can keep up-to-date via our status page:
https://status.coveralls.io/

If there's one project of yours that's experiencing the issue, please email us at support@coveralls.io and we will determine if it has been involved in any backed-up queues yesterday.
