### ISSUE TITLE
Does not rendering stably coverage last 2 days

### ISSUE THREAD

**Issue by svenedik** [lemurheavy/coveralls-public#1475]
For the last 2 days, coverage reports are not calculated stably and trigger GitHub late. Therefore, our development has been blocked. Please help us as soon as possible.

![image](https://user-images.githubusercontent.com/38247600/90005403-d504e500-dc9f-11ea-8d6a-6106ca28d968.png)

**Comment by afinetooth** [comment]
Hello @svenedik,

Apologies for the issues. They're being caused by us hitting new resource limits, leading to intermittent performance slowdowns (backed up queues and slow job processing). You can read more about the issue and follow status, here:
https://status.coveralls.io/

Please rest assured that, unless we reach out to indicate otherwise, your builds will eventually complete and your reports will render without any loss of data.

Until we're able to complete a planned infrastructure upgrade, we are monitoring the situation and addressing slowdowns on a case-by-case basis.

Thanks for your patience.
