### ISSUE TITLE
Coveralls comment not appearing

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1478]
Sorry for all the issues, but I just don't appear to be a lucky person :joy: 

We have been using coveralls for more than a week but I have never seen any coveralls comments posted, despite having it turned on in the settings.

https://coveralls.io/github/15five/fifteen5/settings
![image](https://user-images.githubusercontent.com/46505081/90430936-1f5ddb80-e07d-11ea-81a7-aa1726fbebb1.png)

![image](https://user-images.githubusercontent.com/46505081/91099656-91539900-e618-11ea-9ec7-abd69c43b782.png)

We are using CircleCI. I have seen status checks before - does commenting require any extra permissions we need to configure? If so how do I configure that?

**Comment by afinetooth** [comment]
hi @caleb15,

i know you say you've seen no pr comments, but specifically, can you please verify that you don't have pr comments for any / all of these PR#s on your side:

1. 30439
2. 30578
3. 30592

these are PRs for which i can verify a PR comment should have been sent.

we are seeing a pattern of missing PR comments for some projects. we're looking into it right now. knowing about those specific PRs will help, just because it eliminates one reason for me in your case.

thanks.

**Comment by caleb15** [comment]
Thanks for the quick response @afinetooth !

There are no coveralls comments in any of the PRs you mentioned.

For example (30439):
![image](https://user-images.githubusercontent.com/46505081/91101349-b39ae600-e61b-11ea-88bd-9ba4a3c164f6.png)

**Comment by afinetooth** [comment]
hi @caleb15 ,

I'm going to close this issue as I've followed up in email.

For those following:
Most issues with PR comments relate to GH access permissions, or an expired token. That is, _if_ you're receiving PR comments for other repos. If you're not receiving PR comments for any of your repos, there's likely a setup issue. Best to submit your issue here with a specific build URL, or email us at support@coveralls.io if you're concerned about sharing your data publicly.
