### ISSUE TITLE
coverage seems to be uploaded fine, but target page delivers 404

### ISSUE THREAD

**Issue by dhiller** [lemurheavy/coveralls-public#1480]
I'm one of the maintainers of the [KubeVirt project](https://github.com/kubevirt/kubevirt/)

We are recently having problems with uploaded coverage data, i.e our job (using [mattn/goveralls](https://github.com/mattn/goveralls)) [reports exit code 0 and prints this](https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3945/pull-kubevirt-goveralls/1298878553160421376):

```
...
Job ##11933.14
https://coveralls.io/jobs/66914141
...
```

while the page delivers a 404
Same for [another job run](https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3945/pull-kubevirt-goveralls/1298626677550616576): 

```
...
Job ##11933.6
https://coveralls.io/jobs/66886644
...
```

Also the reporting back to the GitHub status does not seem to happen any more.

Would be great if you can take a look. Thanks!

**Comment by dhiller** [comment]
Maybe related to #112 and #1439

**Comment by dhiller** [comment]
Interesting here is that this does not seem to happen everywhere. I.e. [on this PR](https://github.com/kubevirt/kubevirt/pull/4035) the [coverage link](https://coveralls.io/jobs/66916805) works.

EDIT: [job link here](https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4035/pull-kubevirt-goveralls/1298888493832867840)

**Comment by dhiller** [comment]
But also worth mentioning is that the coverage does not seem to get reported back to GitHub any more.

**Comment by afinetooth** [comment]
Hi @dhiller,

Has anything changed with your CI config? 

Those two jobs appear to be for the same build, a build with ID #11933.

You are showing:

- ##11933.6
- ##11933.14

But the build for the project with that ID:
https://coveralls.io/builds/33019817

Shows just one job:

- ##11933.93

Indicating that there were 92 previous jobs for the build.

The disappearance of those previous jobs is due to automatic removal by coveralls because it's recognizing them as duplicates (jobs with the same `service_job_id` and `flag_name`).

Are you intending to run >90 jobs in parallel? My guess is no, since other recent builds only have a single job each:

- https://coveralls.io/builds/33066398 (##11938)
- https://coveralls.io/builds/33053526 (##11937)
- https://coveralls.io/builds/33048883 (##11936)
- https://coveralls.io/builds/33048758 (##11935)

Using ##11935 as an example:

![Screen Shot 2020-08-28 at 4 37 31 PM](https://user-images.githubusercontent.com/918667/91622605-c62f5b00-e94c-11ea-964d-be3a02a0f08a.png)

On the other hand, for build ##11934 we have something different:

- https://coveralls.io/builds/33043219

![Screen Shot 2020-08-28 at 4 38 19 PM](https://user-images.githubusercontent.com/918667/91622627-e232fc80-e94c-11ea-812c-de80ee2f4848.png)

For that one it looks like there were other jobs run, with only the fourth, perhaps the last, accepted as not-a duplicate.

Does this pattern shed any light?

**Comment by dhiller** [comment]
Hi @afinetooth,

thank you for your time investigating this!

You were right, the duplicates might well have been caused by us running the coveralls again when Prow was trying to do a batch merge. So this might explain it. We have since put in a check to avoid doing this again. Also it seems that due to a misconfiguration on our end we just didn't provide the GitHub PR number and the branch name for the API calls done by goveralls to work. I think I still need to have a deeper look into this but by doing this for us this seems to have resolved the issue.

One note though: I found the [api reference documentation](https://docs.coveralls.io/api-reference) a little unclear insofar as only the repo token was mentioned as required. Maybe the hint should be more clear that i.e. whenever a (in our case GitHub) status should be attached the PR id is required for this to work (don't know how to best put this myself)?

Again, thanks for having a look!

**Comment by afinetooth** [comment]
Regarding needing to specify the branch, we have discovered that's required with some CIs (although not those in our [supported list](https://docs.coveralls.io/supported-ci-services)); therefore, we've provided the optional parameter, `service_branch`, assuming that's the one you referenced:

- **service_branch** - this is an optional way of setting the branch; it should be the same as git[:branch] in the git hash, but if for some reason the git repo hasn't been checked out at CI build time, this is a simpler way of setting it than building up the git hash.

Most additional parameters like this have been added as needed/requested to support community integrations as they try to add support for CIs outside our [supported list](https://docs.coveralls.io/supported-ci-services). For this reason they don't appear in official documentation.

That said, we're working on updates to our API docs, so thanks for the suggestion. It would be good to annotate some of our endpoints with "officially unsupported" parameters for use in various edge cases.
