### ISSUE TITLE
Background coverage graph stuck on https://coveralls.io/github/ledgersmb/LedgerSMB

### ISSUE THREAD

**Issue by ehuelsmann** [lemurheavy/coveralls-public#1483]
The background on https://coveralls.io/github/ledgersmb/LedgerSMB indicates coverage of ca 25% on the right-most coverage measurement, while I had expected that point to correspond to the most recent coverage test outcome on the default branch (master) -- which happens to be ca 43%.

Could you have a look if you can get this graph "unstuck"?

The associated repository https://coveralls.io/github/ehuelsmann/LedgerSMB seems to get the right-most measurement correct in its graph, because that does report ca 43%...

**Comment by afinetooth** [comment]
Hi @ehuelsmann,

I see those right-most points on your top graph represent _much_ older builds on your project&mdash;from 2017. 

We may be having an issue scaling the graph, or we may be rendering the wrong portion. Since we render each build as a point on that graph, we start making decisions about which portion to render when we get above a certain number of builds. Your project was added to the system in 2014, so you have lots of builds and I'm sure fit into the outlier conditions. 

I've submitted the issue for review and will follow up asap.

In the meantime, the good news is the issue seems limited to the graph. Your recent builds all look correct, as does the corresponding coverage.

Thanks for your patience as we look into this.

**Comment by ehuelsmann** [comment]
@afinetooth thanks for looking into this. Any results from your analysis yet? Is it curable? Personally, I would not mind if the older values would slowly move out of the viewport on the left as new values are added on the right.

**Comment by ehuelsmann** [comment]
@afinetooth Hi! Anything you can say about this?

**Comment by afinetooth** [comment]
hi @ehuelsmann sorry for the delay. i submitted a PR to display the last 1,000 builds (rather than first 1,000). it needs to be reviewed and accepted. when it is i'll update you here.

**Comment by ehuelsmann** [comment]
Perfect! Thanks for the update!

**Comment by afinetooth** [comment]
hi @ehuelsmann that change should be deployed in the next 24-48 hrs. let me know if you don't see it by then. closing issue for now.
