### ISSUE TITLE
Coverage not being updated in total but individual ones

### ISSUE THREAD

**Issue by 94929** [lemurheavy/coveralls-public#1488]
```
Unsure why this is happening: 
 - my badge is stuck at 81% (https://github.com/whyboris/karma-helpful-reporter)
 - it shows 81% on Coveralls (https://coveralls.io/github/whyboris/karma-helpful-reporter?branch=karma-helpful-reporter)
 - but the last build is 98.638% (https://coveralls.io/builds/12852563)

I'm not sure why Coveralls is ignoring my last build and showing the number from several weeks ago. Perhaps this is a different issue than what the others in this thread are having.

_Originally posted by @whyboris in https://github.com/lemurheavy/coveralls-public/issues/971#issuecomment-322946878_
```
I get the same issue https://coveralls.io/github/LUXROBO/pymodi, would appreciate if anyone could help.

Thanks in advance.

**Comment by afinetooth** [comment]
Hi @jha929,

I'm now seeing your badge coverage is up-to-date. That's on:

- [Github](https://github.com/whyboris/karma-helpful-reporter) - Where it's 100%:

![Screen Shot 2020-09-22 at 11 22 00 AM](https://user-images.githubusercontent.com/918667/93921748-d6c1bf80-fcc5-11ea-9beb-0550f198cf62.png)

- [Coveralls](https://coveralls.io/github/whyboris/karma-helpful-reporter?branch=karma-helpful-reporter) - Where it's 100%:

![Screen Shot 2020-09-22 at 11 22 57 AM](https://user-images.githubusercontent.com/918667/93921838-f953d880-fcc5-11ea-9404-6c3aa0283de7.png)

- As well as for the [build you cited from 16 AUG 2017](https://coveralls.io/builds/12852563) - Where the coverage is your previously expected 98.638%:

![Screen Shot 2020-09-22 at 11 24 21 AM](https://user-images.githubusercontent.com/918667/93921974-2acca400-fcc6-11ea-9169-572d752372ad.png)

Given that build is from 2017, it's hard to say what has transpired since then that might have changed.

But as far as badges showing outdated coverage, we have seen that be an issue on GitHub in particular as they have an aggressive caching mechanism, discussed here:
https://github.com/github/markup/issues/224

We typically point users to this how to, to purge their cache:

- How to purge content from Github camo cache:
https://help.github.com/en/github/authenticating-to-github/about-anonymized-image-urls#removing-an-image-from-camos-cache

```
$ curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....
> {"status": "ok", "id": "216-8675309-1008701"}
```

Since this appears to be resolved, I'm going to close the issue. Just reply if anything remains to be done.
