### ISSUE TITLE
Can't see Github private repos

### ISSUE THREAD

**Issue by grasbergerm** [lemurheavy/coveralls-public#1491]
After ensuring third party access is granted, I still cannot see the private repos for an org I am a part of. Interestingly enough, on the add repos page, under the org filter, I can see the proper number of repositories (with private repos included) but the search does not show any private repos.
![image](https://user-images.githubusercontent.com/6827110/95894234-cba70000-0d56-11eb-8b52-9629ccbf2b43.png)

**Comment by afinetooth** [comment]
Hi @grasbergerm, 

The reason is that, while Coveralls is free for public repos, access to private repos requires a subscription. Once there's a subscription for the associated organization, you'll have access to the org's private repos (to the extent you have access through the GH org).

To add a subscription, click the ADD PRO button.

If you're evaluating, please know all subscription levels come with one month of free trial service. As long as you cancel before the renewal date, you won't be charged.

Once you've created a subscription for your org, if you're not seeing the private repos on your ADD REPOS page, click the REFRESH PRIVATE REPOS button.
