### ISSUE TITLE
Update ruby Set Up page (Missing method SimpleCov::SourceFile # coverage)

### ISSUE THREAD

**Issue by mochetts** [lemurheavy/coveralls-public#1499]
### Description

When following the set up guide for ruby, the developer is instructed to add the `coveralls` gem:
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/3678598/98180283-450dba80-1edf-11eb-8e94-3b41483adc63.png">

However, this gem has a conflict within its dependencies. It's including the [latest version of simplecov](https://github.com/lemurheavy/coveralls-ruby/blob/master/Gemfile#L8) which doesn't have the method `coverage` for `SimpleCov::SourceFile`.

This leads to this error when running a travis build:
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/3678598/98180376-800fee00-1edf-11eb-95cd-a90317b114d3.png">

Complete log [here](https://travis-ci.org/github/mochetts/my-vids/builds/741505764)

### Solution
Either lock `simplecov` gem to version `0.17.0` (which has the missing method) or update the set up guide so that it uses [this gem](https://github.com/tagliala/coveralls-ruby-reborn):
```ruby
gem 'coveralls_reborn', '~> 0.18.0', require: false
```

**Comment by afinetooth** [comment]
Thanks @mochetts. We're aware this integration is behind on maintenance. 

The team behind that integration has been working on a [universal coverage reporter](https://github.com/coverallsapp/coverage-reporter) that can be used in lieu of or as a component of any integration.

For Ruby projects that can't lock Simplecov to 0.17.0 in their own Gemfile, we do typically recommend switching to [coveralls-ruby-reborn](https://github.com/tagliala/coveralls-ruby-reborn), which has been well-maintained.

Point taken that we should consider swapping the gem reference in the repo start page for Ruby projects. Since we have a large installed base of Ruby users it would be ideal to merge the two projects.

Thanks again for the feedback.

**Comment by mochetts** [comment]
@afinetooth thanks for the quick reply. I updated the title of this issue so that anyone experiencing the same can quickly find the solution.

**Comment by afinetooth** [comment]
Appreciate that, @mochetts. Thanks.
