### ISSUE TITLE
Partly coverage recognition

### ISSUE THREAD

**Issue by Falseclock** [lemurheavy/coveralls-public#1507]
Please look at this report

https://coveralls.io/jobs/71796796/source_files/4050171917

That's looks very strange
![image](https://user-images.githubusercontent.com/3299139/101309063-9eb62b80-3875-11eb-828b-752f274744a4.png)

**Comment by afinetooth** [comment]
@Falseclock yes, but notably it's consistent with other instances, for example:

![Screen Shot 2020-12-14 at 5 31 54 PM](https://user-images.githubusercontent.com/918667/102156368-43b2a480-3e32-11eb-8b66-9c51c0b193cb.png)

Coveralls simply displays the coverage stats we receive in the report generated by your coverage library, which I believe in your case is [PHPUnit](https://github.com/sebastianbergmann/phpunit) exporting in clover format (through [php-coveralls](https://github.com/php-coveralls/php-coveralls)). 

The question is why your coverage library is marking these lines uncovered, when similar to constructs in other languages, they might be considered not relevant and ignored.

I'm not familiar enough with PHP to know why your library would be marking those uncovered. Have you asked in [php-coveralls issues](https://github.com/php-coveralls/php-coveralls/issues)?

If it's unexpected, it could be an issue of a similar class to these on SO:

- [PHPUnit HTML and Clover coverage reports differ due to codeCoverageIgnore](https://stackoverflow.com/questions/6949051/phpunit-html-and-clover-coverage-reports-differ-due-to-codecoverageignore)
- [Why does PHPUnit show some close-curly-braces as not being covered?](https://stackoverflow.com/questions/8827132/why-does-phpunit-show-some-close-curly-braces-as-not-being-covered)
