### ISSUE TITLE
No repositories listed under Bitbucket account

### ISSUE THREAD

**Issue by RobertoRoos** [lemurheavy/coveralls-public#1509]
I created a coveralls.io account linked to both my Github and Bitbucket. When adding a repository I can find the public Github repos, but I cannot see my public Bitbucket repos, the list is just empty, even though there should be multiple repositories.

When putting in the URL directly I get a 404 error: https://coveralls.io/bitbucket/Roberto-R/uptime-tester

I have tried unlinking and linking my account again, and even deleting my account entirely. This made no difference.

The 'sync repos' button makes no difference.

Thank you for any assistance!

**Comment by RobertoRoos** [comment]
Tried it with a new Bitbucket account and here I can add a Bitbucket repository. So something is going on with my account / repo specifically.

**Comment by afinetooth** [comment]
Hi @RobertoRoos , yes, I'm able to reproduce. Will you please email us at support@coveralls.io and reference this issue? Would like to track it internally and keep any sensitive info private. Thanks.

**Comment by RobertoRoos** [comment]
I just tested this again (hadn't really looked at this for a year), but I still cannot see any Bitbucket repos, public or private.

**Comment by afinetooth** [comment]
Hi, @RobertoRoos. I'm able to find your Github account and one Github repo, but not your BitBucket account or any BitBucket repos. 

This is to say, I can still reproduce the issue, but only for your account. I _am_ able to see my _own_ public repos from BitBucket.

TBH, I'm not sure if my previous message about being able to reproduce applied to you, or all BitBucket users. Either way, the same next step applies:

Can you please try unlinking and re-linking your BitBucket account from your [ACCOUNT PAGE](https://coveralls.io/account)?

I suspect there's an issue with your BitBucket OAuth token.

**Comment by RobertoRoos** [comment]
I unlinked my account and for good measure also revoked the token from inside Bitbucket.org itself. I relinked but nothing has changed.

My Coveralls could be removed entirely if that's something to try, I haven't used it for anything yet.

Thanks for your help!

EDIT: I see I can do that myself. I deleted my account and tried to login through Bitbucket again. I redid the authorization. But I still cannot see any Bitbucket repos...

**Comment by afinetooth** [comment]
Hi @RobertoRoos. Yes, I see the new account you created and I see your public repos at BitBucket.

However, after our API client makes a call to the BitBucket API to get a list of all your accessible repos, a _second_ call, to collect the data on those, _fails_ on the first repo it sees: `itco/the-roast-of-yoeri-bruinsma-hg_874b1c_hg`

The specific error message is:

```
BitBucket::Error::Forbidden (#<struct Faraday::Env method=:get, body="Repository currently not available.", url=#<URI::HTTPS https://bitbucket.org/api/2.0/repositories/itco/the-roast-of-yoeri-bruinsma-hg_874b1c_hg> [...]
```

I couldn't tell at first if any (or all) other repos would fail in the same way because this was the first repo it encountered, but, since the request came with a paging parameter, I requested the "next page" of results and got a similar error: 

This time for repo: `itco/activity-creator-hg_776e4e_hg`

```
BitBucket::Error::Forbidden (#<struct Faraday::Env method=:get, body="Repository currently not available.", url=#<URI::HTTPS https://bitbucket.org/api/2.0/repositories/itco/activity-creator-hg_776e4e_hg> [...]
```

In this second query, I noticed requests for some _other_ repos you have access to _succeeded_, for instance, the repo, `ctw-bw/soes_arm`.

(_Simplifying from a previous version of this answer..._)

Here's how it works from our side:

We build an API client object with your OAuth access token, like this:

```
# ruby
@bitbucket_client ||= BitBucket::Client.new new_access_token: <your_bitbucket_token>
```

Then we request all the repos you have access to, like this:

```
# ruby
@bitbucket_client.get_request("/2.0/user/permissions/repositories", page: page)
```

The scope of that call extends to both _public_ and _private_ repos that you have access to. You having access to them _is_ the scope.

Then, we attempt to make _another_ call&mdash;a query against each of the repos you have _access_ to&mdash;that then checks the scope of each repo: _public_ or _private_. 

But _that_ is the call that's failing&mdash;even though we expect to be able to make it, like this:

```
# ruby
bb_repo = @bitbucket_client.get_request("/2.0/repositories/#{name}")
```

I am currently stuck there, wondering why this isn't happening for all users, but I wanted to share my current findings with you in case you have any insights into why requests of certain repos you have access to might be failing (I'm currently thinking: additional access restrictions? similar to the IP-blocking feature at Github?)

If you don't have any ideas why this might be occurring, I'll dive deeper.

**Comment by RobertoRoos** [comment]
Well this has been a while :p

I went to check the original repository and I _can_ add it now (not that the project is still relevant). So I guess the issue is resolved?

**Comment by afinetooth** [comment]
Hi @RobertoRoos. Apologies on the poor follow-up here. We're a small team and do our best, especially with these public issues, which are technically a community-first board. If you are a member of a any paid subscriptions, I would encourage you to email Coveralls Support directly at support@coveralls.io, where you'll get priority response on a shorter timeline than through this board. We've been a _little_ better with new issues here over the past year, but it can still take up to a week for us to respond to issues here. (It's still a fine place to get input from fellow users, though, so always worth it if you have the time.)

**Comment by RobertoRoos** [comment]
@afinetooth that's fine, I didn't mean to be snarky, maybe my message came across poorly. I had just forgotten about this issue.

I'm glad it's working now, I'll get back to Coveralls in the future!

**Comment by afinetooth** [comment]
Ah! No worries. I misinterpreted and was feeling bad about the follow-up. All good. 

BTW, since you're a Bitbucket user, I did want to mention one new Bitbucket feature released since our last exchange above: [PR COMMENTS FOR BITBUCKET](https://coveralls.io/bitbucket-pr-comments). I hope it'll be useful to you.
