### ISSUE TITLE
Any additional docs to explain the "relevant lines" graph? 

### ISSUE THREAD

**Issue by samsmithnz** [lemurheavy/coveralls-public#1512]
The docs don't have anything I can find about this, and I find the graph confusing.

![image](https://user-images.githubusercontent.com/8389039/103142420-b3494f00-46d0-11eb-91d3-9e92c3d88a7a.png)

**Comment by afinetooth** [comment]
Hi @samsmithnz,

We're working on an update to our documentation, due early this new year (2021).

First thing to note is there's an apparent bug in your build's graph (which I've submitted for a fix), but let me explain how it works / should work:

**RELEVANT LINES COVERED graph**:

- The grey section of this graph (background) represents RELEVANT LINES in your source code (lines of code that are not comments, blank lines, etc.)
- The pink section (foreground) represents COVERED LINES (lines covered by tests).
- The dots in the pink trendline represent the (line-based) coverage for your last ten (10) builds.
- The graph shows three (3) figures for the current build: RELEVANT LINES, COVERED LINES & HITS PER LINE.

![Screen Shot 2020-12-29 at 2 22 38 PM](https://user-images.githubusercontent.com/918667/103317845-51932880-49e1-11eb-8ceb-128748b573bb.png)

The _issue_ here is that the figure associated with your last dot reads 144.73%, which happens to match the HITS PER LINE figure (as a number: 144.73) but doesn't really make sense as an _over-100%_ figure (unless you want to think in terms of "saturation"). 

In actuality, I believe this figure should be a _sub-100%_ percentage representing the ratio: 

- **COVERED LINES** / **RELEVANT LINES**

In your case, this would be:

- **2053 COVERED LINES** / **2089 RELEVANT LINES**

Or:

- **98.28%**

Which is also visually more reasonable for that section of your graph:

![Screen Shot 2020-12-29 at 2 13 37 PM](https://user-images.githubusercontent.com/918667/103317512-3d026080-49e0-11eb-9e6f-1979799cb3c0.png)

Now, why do we show this RELEVANT LINES COVERED graph when we display AGGREGATE COVERAGE for the build elsewhere?

Namely, here:

![Screen Shot 2020-12-29 at 2 16 55 PM](https://user-images.githubusercontent.com/918667/103317724-dd588500-49e0-11eb-9ca8-5f20ba96c24c.png)

Note the total coverage (aggregate coverage) for your build is actually **98.072%**, less than your (line-based) coverage of **98.28%**.

That's because in your project [SETTINGS](https://coveralls.io/github/samsmithnz/AzurePipelinesToGitHubActionsConverter/settings) you have this setting set to YES:

![Screen Shot 2020-12-29 at 2 36 05 PM](https://user-images.githubusercontent.com/918667/103318392-30333c00-49e3-11eb-8b3a-5a59d958cb12.png)

The [LCOV](https://wiki.documentfoundation.org/Development/Lcov) standard allows for consideration of code _branches_, in addition to code _lines_, in determining code coverage.

When INCLUDE BRANCH COVERAGE IN AGGREGATE COVERAGE % is set to YES, we use a formula to combine BRANCH COVERAGE with LINE COVERAGE into an AGGREGATE COVERAGE figure.

Your **AGGREGATE COVERAGE %** happens to be **98.072%**.

But your LINE-BASED COVERAGE is **98.28%**, and the RELEVANT LINES COVERED graph is there to provide that detail, outside the context of AGGREGATE COVERAGE.

**Comment by afinetooth** [comment]
@samsmithnz I'll let you know when the issue with the graph is fixed.

**Comment by samsmithnz** [comment]
Thank you for the wonderful explanation. Makes a lot of sense.
