### ISSUE TITLE
Combining coverage using multiple CI providers

### ISSUE THREAD

**Issue by spyoungtech** [lemurheavy/coveralls-public#1520]
Hi, I have a project that uses multiple CI providers. In this case, GitHub Actions and Appveyor for testing on different platforms (MacOS, Windows, and soon will be adding another for Linux)

I've noticed that the coverage will report _either_ the GHA or Appveyor coverage results, but will not combine them.

I've tried adding `COVERALLS_PARALLEL` to my env variables in both configurations, but this does not seem to change the outcome.

Is there a way to get these reports combined?

**Comment by afinetooth** [comment]
@spyoungtech yes, cross-CI builds is not something we support and the base assumption is that a build is coming from one service. It's on our roadmap but not likely to be released this year.

Any attempt to merge jobs across CIs into a single build would be experimental and isn't something we can guarantee will work. Not aware of anyone having accomplished it thus far.

If this is mission-critical, I'd recommend you look at a CI provider like [CircleCI](https://circleci.com/build-environments/) that supports [all the platforms](https://circleci.com/build-environments/) you mention above.

That said, I can share a few tips on exploring a solution if you're feeling intrepid:

1. [Explore our API Reference](https://docs.coveralls.io/api-reference) - Specifically, familiarize yourself with all the parameters required for POST requests to our /jobs endpoint. Jobs are the building blocks of builds. (Single-job builds are simply comprised of one job.)
2. Proceed as if using an [unsupported CI](https://docs.coveralls.io/supported-ci-services) - You'll want to make sure you're providing values for [these environment variables](https://docs.coveralls.io/supported-ci-services#insert-your-ci-here).
3. Choose a unique `service_name` - And keep it consistent across jobs. Re: `CI_NAME` from (2), you'll need to make sure the API believes you're coming from one service. Choose something it won't recognize so it doesn't treat your job with any default behavior for that service. Note: `service_name` is the API param here; `CI_NAME` is the associated CI env var.
4. Ensure a consistent `service_number` across CIs - One build should have the same `service_number` (aka. `CI_BUILD_NUMBER`) for all jobs, across CIs. This is the main identifier required to link jobs to a single build. 
5. Leave `service_job_id` blank / null - Without a value, our system will auto-increment an integer value for each incoming job. Many services, and many pre-built integrations that you might use, will auto-supply this, so you'll need to make sure it's not being passed.
6. Use `parallel=true` - As you're sending multiple jobs for one build, you are indeed creating a parallel build. So follow [parallel build instructions](https://docs.coveralls.io/parallel-build-webhook). This means that after sending all jobs, you'll need to send a [parallel webhook](https://docs.coveralls.io/parallel-build-webhook) to close the build. The logical place to do this is from the last CI service to run, if you can control the order. (You will have to control the order, otherwise, you may close the build before all jobs are in.)
7. Use `flag_name` - Not required, but using `flag_name` will be helpful to, for instance, receive separate PR checks for each job, which may be even more relevant in your case.

If you make any progress, please share it and we'll help how we can.
