### ISSUE TITLE
Need multiple "owners" with equal access to repositories

### ISSUE THREAD

**Issue by leerho** [lemurheavy/coveralls-public#1521]
Hello, we have 3 folks that need to have equal "owner" access to our project Coveralls sites, for example [coveralls.io/github/apache/datasketches-java](https://coveralls.io/github/apache/datasketches-java).    We found out that I have access to the "Settings" menu and to the Token regeneration, but  my colleagues do not.

How can we fix this?

**Comment by afinetooth** [comment]
Hi @leerho, as it stands, for other users to have access to the repo's settings they'll need to have "admin" access through your Github organization, per Github's [Repository Permission Levels](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization).

**Comment by leerho** [comment]
I am not referring to the "settings" in the GitHub Repo, but the "settings" in the Coveralls page as in the above link.  For example, If I access [coveralls.io/github/apache/datasketches-java](https://coveralls.io/github/apache/datasketches-java) signed in with my GitHub account I can see the "Settings" button on the Coveralls' page. When my colleague signs in with his GitHub account, he does not see the "settings" button on the Coveralls' page.  These "settings" have only to do with Coveralls-related options.

The "settings" button on the GitHub Repo page is something else entirely and unrelated.

**Comment by afinetooth** [comment]
@leerho yes, I understand. Sorry for the confusion. 

We also refer to Coveralls projects as "repos" since they're scoped to your repo. We typically refer to this page as your "repo page":
https://coveralls.io/github/apache/datasketches-java

And by (repo) "settings" I _was_ referring to the "Settings" link that appears on your "repo page" in Coveralls.

And the rest still stands. In order to be able to access and update those settings, the user would need to have "Admin" level permissions on the repo at your originating repo host, in your case Github.

As each of your users OAuth's into Coveralls via Github, we check each user's Github permissions each time they log into Coveralls, and each time they access a repo, and we base many Coveralls access permissions on those. In this case, we only show coveralls repo settings to users with Github Admin access.

So the solution would be to give your colleagues "Admin" access to the relevant repos at Github, through your org.
