### ISSUE TITLE
"DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

### ISSUE THREAD

**Issue by psy0rz** [lemurheavy/coveralls-public#1524]
I keep ketting this error on https://coveralls.io/github/psy0rz/zfs_autobackup.

**Comment by afinetooth** [comment]
@psy0rz your builds were affected by a system-wide issue that occurred this afternoon.

The incident was short but caused thousands of background jobs to fail temporarily.

That DataTables error indicates that a background job that draws the TREE and LIST views of your source files table failed to complete (or complete _yet_). Many people will be experience the same today until failed jobs from this afternoon are re-enqueued and re-processed (successfully).

Please let us know if you're still experiencing this in a few hours, or by the time you start work tomorrow.

**Comment by psy0rz** [comment]
The problem still persists.

**Comment by afinetooth** [comment]
Thanks, @psy0rz , yes, we're aware of some projects failing to render the LIST view of their SOURCE FILES table. 

As this most likely has to do with failed jobs that did not re-process, or failed again, I suspect you'll be okay with future builds. 

If not, please let me know.

We're working on the affected builds right now.

**Comment by afinetooth** [comment]
@psy0rz the underlying issue should be resolved now. Let me know if not.

**Comment by LinqLover** [comment]
Gey @afinetooth, I keep having the same problem in this repository for a few days: https://coveralls.io/github/hpi-swa-lab/squeak-inbox-talk?branch=cache

It would be great if you could fix this, it's really embarrassing and my coverage counter has fallen to zero. :-)

**Comment by afinetooth** [comment]
Hi @LinqLover, I just checked your repo and the issue appears to be resolved.

From looking at the previous builds, with coverage at 0.0%, I can't see anything that provides any insight, except that, for some reason, each build thinks you only reported on 1 file (instead of the 111 source files in your coverage report). This could be an issue with your coverage report format. 

Two questions:

1. What package are you using to generate your coverage reports? 
2. What coveralls integration are you using to convert that report (to JSON) and upload to coveralls? 

Your project appears to be in Smalltalk. I am not familiar with any integrations for Smalltalk.

**Comment by LinqLover** [comment]
Hi @afinetooth, yes, the issue has magically resolved itself in the meantime.

I am using [smalltalkCI](https://github.com/hpi-swa/smalltalkCI) which automatically integrates with Coveralls, but usually, this has worked well in a number of repositories. The coverage integration for smalltalkCI is also described [here](https://github.com/hpi-swa/smalltalkCI/blob/master/docs/COVERAGE.md) in greater detail.

**Comment by afinetooth** [comment]
@LinqLover glad to hear it. [Looks good](https://coveralls.io/github/hpi-swa-lab/squeak-inbox-talk).

Thanks for the info on [smalltalkCI](https://github.com/hpi-swa/smalltalkCI). I have added it to our list of language integrations, here:
https://docs.coveralls.io/
