### ISSUE TITLE
Failed to parse string - of empty coverage file

### ISSUE THREAD

**Issue by zhorvatic** [lemurheavy/coveralls-public#1528]
I am trying to set coveralls coverage tracking for a repository without a single test in Golang.

Because no tests are going through statements, the Golang test processor produces an empty coverage file in `.gcov` format.
This is afterwards converted into `.lcov` file format using https://github.com/jandelgado/gcov2lcov and posted using coveralls orb https://circleci.com/developer/orbs/orb/coveralls/coveralls to coveralls API. 

The setup works fine on other repositories (that have at least a single test), but for this particular case (as the file is empty) we receive the following error:

```
[debug] "2021-02-15T16:53:48.425Z"  'in: ' ''
[error] "2021-02-15T16:53:48.427Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2021-02-15T16:53:48.427Z"  'input: ' ''
[error] "2021-02-15T16:53:48.427Z"  'error from convertLcovToCoveralls'

/usr/local/lib/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Failed to parse string
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Exited with code exit status 1
CircleCI received exit code 1
```

I would expect that the POST passes and the coverage is set to 0.00% 

How should we approach resolving this problem?

**Comment by afinetooth** [comment]
Hi @zhorvatic in order to see exactly what JSON you're passing to the coveralls API, can you please add the:

```
verbose: true
```

param to your config file per [instructions here](https://circleci.com/developer/orbs/orb/coveralls/coveralls#commands)?

Coverage of 0.00% actually reflects a non-empty LCOV report (and ultimately JSON with a non-empty value for the key `source_files:`) where all code files are enumerated, each with a coverage hash showing relevant and non-relevant lines (integer and `null`s, respectively), where all the relevant lines are uncovered (`0`).

If the `source_files` param is passing the value of an empty string (`' '`), that's probably the issue; though a more informative exception would help. I suspect there'd be a different error for empty array (`[]`).

As for how to approach a fix, if the LCOV report is empty (JSON: `source_files: []`), that behavior resides in your coverage tooling (the library that generates test coverage reports). Seems like it just won't generate a report without at least one test. In that case, the most efficient fix will probably be to add one test, even if trivial.

**Comment by zhorvatic** [comment]
Hi @afinetooth, the verbose is already set, and the output is listed in the original post. This is the orb setup:
```
      - coveralls/upload:
          path_to_lcov: ~/app/coverage.lcov
          token: COVERALLS_REPO_TOKEN
          verbose: true
```
I have debugged the issue locally, so here's some more info. 

When there are no statements covered, `go test -v -tags musl -covermode atomic -coverprofile ./coverage.gcov ./...` will create a file with content.
```
mode: atomic

```
If this is fed into the converter `gcov2lcov -infile coverage.gcov -outfile coverage.lcov` it will create a file with content
```
```
Since the above output is sent as the `source_files`, that probably is an issue, as you mentioned.

> If the source_files param is passing the value of an empty string (' '), that's probably the issue; though a more informative exception would help. I suspect there'd be a different error for empty array ([]).

I see the potential value of having more informative exception messages stating the expected input format, especially in this case. 

> As for how to approach a fix, if the LCOV report is empty (JSON: source_files: []), that behavior resides in your coverage tooling (the library that generates test coverage reports). Seems like it just won't generate a report without at least one test. In that case, the most efficient fix will probably be to add one test, even if trivial.

Adding a test will most likely be the quick-fix solution for us.

**Comment by afinetooth** [comment]
Hi @zhorvatic I agree and have submitted a request to deliver a better error for such requests. Thanks. 

Closing for now. Just reply to re-open.
