### ISSUE TITLE
False negative status set in github

### ISSUE THREAD

**Issue by jku** [lemurheavy/coveralls-public#1531]
We have coveralls integrated with Github Actions and are experiencing false negative results in the Github statuses that Coveralls.io sets.

We use coveralls-python to upload multiple parallel builds from a github action (and use a finalize task in the end). These look fine on Coveralls.io (example https://coveralls.io/builds/37444203). One of the individual builds is marked as failed on github though: 
<img src="https://user-images.githubusercontent.com/31889/109170794-c7b9ce80-7789-11eb-9e64-80f5222eb2e7.png" width=50% height=50%/>
There was no change in coverage in this merge. coveralls.io view seems to agree with that but the github status does not. The same problem has happened in several jobs. Another maybe related issue is that the number of status checks on the github UI is often less than the number of jobs in the build.

Have we misunderstood something?

coveralls project: https://coveralls.io/github/theupdateframework/tuf
TUF issue https://github.com/theupdateframework/tuf/issues/1287
The github workflow: https://github.com/theupdateframework/tuf/blob/develop/.github/workflows/ci.yml

**Comment by afinetooth** [comment]
@jku can you please share the full message you see in the failing check(s)? I would like to trace it to the exact job that sent the check.

I see that there were no relevant diffs between the base branch and the PR branch being merged. That said, I suspect a calculation something like -0.001%. Practically no change, but technically _some_ change, causing the check to fail/fire.

This would be an issue to handle on our side, but in the meantime, you can make the annoyance go away by giving some value to this [setting](https://coveralls.io/github/theupdateframework/tuf/settings):

![Screen Shot 2021-02-25 at 1 28 06 PM](https://user-images.githubusercontent.com/918667/109220053-4eac7e00-776d-11eb-9aac-ab7c15c3c2f4.png)

(Something between 0.01 and 0.99 depending on how sensitive you want it to be.)

With other CI options you have the option of delivering just one check to Github, instead of one for each job, by not passing a `flag_name` for each job, but with the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) `flag_name` is required per [Usage > Inputs](https://github.com/marketplace/actions/coveralls-github-action#inputs).

Let me know if that doesn't work.

**Comment by afinetooth** [comment]
Actually @jku just realized you're not using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), but the [Coveralls Python Github Action](https://github.com/marketplace/actions/coveralls-python), so you might be able to get away with removing the `flag_name` param from your `ci.yml`, which, if you prefer, would reduce your checks down to one for the aggregate coverage result.

**Comment by afinetooth** [comment]
@jku One more thing: Per [this explanation](https://github.com/lemurheavy/coveralls-public/issues/1513#issuecomment-753383263), if any jobs seem to be failing, not because of a decrease in coverage, but because coverage falls below some threshold (albeit unspecified right now), you can provide a value for this settings as well:

![Screen Shot 2021-02-25 at 2 43 50 PM](https://user-images.githubusercontent.com/918667/109229242-e0b98400-7777-11eb-8d34-430600a1ab3c.png)

These values should give you the widest margin:

![coverage_thresholds](https://user-images.githubusercontent.com/918667/109229318-f9c23500-7777-11eb-804c-90fc93721a6a.png)

**Comment by jku** [comment]
Thanks for the suggestions

> @jku can you please share the full message you see in the failing check(s)? I would like to trace it to the exact job that sent the check.

If you're referring to the tooltip on github, it's _"Coverage decreased (-0.0%) to 97.506%"_, see e.g. this commit: https://github.com/theupdateframework/tuf/commit/60875f912b430785141e1691a70d7d21827fe86c 
However clicking through to the supposedly failing result on coverage.io: https://coveralls.io/jobs/75737070 we see that _"Coverage remained the same at 97.818%"_.

**Comment by afinetooth** [comment]
@jku, thanks. Update / summary:

- The failing check was indeed due to the "-0.0%" change (that figure being signed was a side effect of a calculation error, most likely related to rounding / degree of precision / type conversion.)
- I've identified a bug behind that on our side and have reported it. (Thanks.)
- No ETA for fix right now, but in the meantime, you can avoid the failing checks by changing the [settings](https://coveralls.io/github/theupdateframework/tuf/settings) mentioned above.
- Why?: Even the infinitesimal decrease labeled "-0.0%" exceeded the `nil` value you had for COVERAGE DECREASE THRESHOLD FOR FAILURE.

**Comment by andy-maier** [comment]
I believe I have also run into this on some of my repos. For example: 
* https://github.com/andy-maier/pytest-easy-server/pull/49 - all test envs fail
* https://github.com/andy-maier/pytest-easy-server/pull/48 - only python 3 based tests fail

The good news is that the circumvention recommended above (of setting values in the coverage threshold fields) worked for me. :-)

**Comment by afinetooth** [comment]
@andy-maier thanks for you `+1`. 

The underlying issue on our end does appear to be the case for this PR:
https://github.com/andy-maier/pytest-easy-server/pull/48

For this one, I'm seeing actual negative changes in coverage:
https://github.com/andy-maier/pytest-easy-server/pull/49
(-4.2% across the board)

![Screen Shot 2021-04-05 at 12 14 51 PM](https://user-images.githubusercontent.com/918667/113615296-8928f680-9608-11eb-8ae3-e30660d5b3e1.png)

In any case, thanks for using the workaround for now.
