### ISSUE TITLE
Unable to change default branch

### ISSUE THREAD

**Issue by jovergaag** [lemurheavy/coveralls-public#1540]
I changed default branch on Github from `master` to `main`. After 24 hours, the default branch in my Coveralls repo has not updated so I have tried two things to manually update it, both unsuccessful.
* Clicking "Sync repos" does not update the default branch
* Deleting the repo by toggling it "Off" on the "Add repos" page. The repo never is deleted/disabled. After toggling it off, the repo has a spinning icon next to it indefinitely. After refreshing the page or navigating to the repo it is clear that it is still enabled. I have tried switching the toggle to "Off" several times, all of them unsuccessful.

**Comment by jovergaag** [comment]
Repo: https://github.com/Recidiviz/pulse-dashboard

**Comment by afinetooth** [comment]
@jovergaag just checked your repo and the default branch is now main. If you see otherwise, please let me know. (Uncertain why it would take that long.) In a pinch, if you see this again, try clicking SYNC BRANCHES in the Branch Menu:

![Screen Shot 2021-04-06 at 1 44 17 PM](https://user-images.githubusercontent.com/918667/113775903-30c42880-96de-11eb-94f6-92c5260d8d7e.png)

The hang on toggling OFF repos is a known issue. I have linked this issue to it, so I'll include an update here when fixed.

**Comment by jovergaag** [comment]
@afinetooth It is now main! Thank you, I just needed to wait another 8 hours.

I appreciate your time. Feel free to close this issue.

**Comment by afinetooth** [comment]
@jovergaag glad to hear it, but, yeah, definitely shouldn't take that long. If it happens again, feel free to let us know at support@coveralls.io and someone will check/verify for you. You can mention [this issue](https://github.com/lemurheavy/coveralls-public/issues/1540). 

Also, don't forget to try the SYNC BRANCHES button if branch sync seems to be delayed. It's a separate request but it might resolve that part of the full sync.

Will close. Thanks.
