### ISSUE TITLE
Second build on PR lacks "uncovered existing lines"

### ISSUE THREAD

**Issue by jacobtylerwalls** [lemurheavy/coveralls-public#1549]
Hi, and thanks for this service.

We have a false positive for "uncovered existing lines" on the first linked report below. The lines first appear at `music21/features/native.py` L122-127.

PR build (840040966)
https://coveralls.io/builds/39673217

last build on master (840015388) showing lines were uncovered already
https://coveralls.io/builds/39672796

The subsequent build on this PR no longer showed the message for uncovered existing lines. If this is due to a job starting on a PR while a job on master is still going, do let me know. Thanks.

**Comment by afinetooth** [comment]
Hi @jacobtylerwalls. You're welcome.

So, there are two types of DIFF shown in the DIFF section of a PR build:

- UNCOVERED EXISTING LINES
- UNCOVERED NEW LINES

UNCOVERED EXISTING LINES are lines that existed in the previous version of the file, that were uncovered then, and remain uncovered now. 

---

### ^^ CORRECTION: 
**The correct definition of UNCOVERED EXISTING LINES is actually:**

- **Lines that existed in the previous version of the file, that were _covered_ then, but are _uncovered_ now.** 

**Otherwise, taken together with UNCOVERED NEW LINES, we would not be showing the user what we intend to show in the line-by-line coverage view, which is:**

- **All the places where coverage has _decreased_, and exactly where it can be improved.**

**This fact renders the rest of this answer _INCORRECT_.**

**(Though it will be left here as-is, for now, for reference.)**

**The correction of this answer is shown by comparison to another example, described here:**
https://github.com/lemurheavy/coveralls-public/issues/1563#issuecomment-863604488

**(That comment refers back to this one.)**

---

UNCOVERED NEW LINES are newly added lines, that didn't exist in the previous version of the file, that are uncovered.

In this case, the status of those lines (`music21/features/native.py:L121-127`) looks correct to me since they existed in the previous version of the file, were uncovered then, and remain uncovered in the new version.

If there is an issue here, it might be that the `UNCOV` label was only affixed to L122-124 && L126-127. I'm not 100% sure that's the case, but their "relevance" and the fact that they are "uncovered" remains the same in both versions.

---

> The subsequent build on this PR no longer showed the message for uncovered existing lines. If this is due to a job starting on a PR while a job on master is still going, do let me know. Thanks.

I do think this is an issue, which I've reported.

I think the DIFF is missing from that [second PR build](https://coveralls.io/builds/39673881), for some reason.

If you note the CHANGES in the SOURCE FILES table, they are correct, and relative to both the [base build](https://coveralls.io/builds/39672796), and the [first PR build](https://coveralls.io/builds/39673217).

#### [Base build](https://coveralls.io/builds/39672796) (LEFT) / [First PR build](https://coveralls.io/builds/39673217) (RIGHT):
![Screen Shot 2021-05-14 at 1 55 24 PM](https://user-images.githubusercontent.com/918667/118330021-0a9f5e80-b4bc-11eb-916e-10545f80809c.png)

#### [Base build](https://coveralls.io/builds/39672796) (LEFT) / [Second PR build](https://coveralls.io/builds/39673881) (RIGHT):
![Screen Shot 2021-05-14 at 1 57 23 PM](https://user-images.githubusercontent.com/918667/118330227-50f4bd80-b4bc-11eb-8c81-06aae3101752.png)

**Comment by jacobtylerwalls** [comment]
Ah, so it's "these EXISTING lines are still UNCOVERED", not "you UNCOVERED these EXISTING (covered) lines". Based on the word order I always thought it was the latter, but thanks for the explanation. 👍🏻

**Comment by afinetooth** [comment]
Exactly. Totally understandable. 

Unfortunately, not too many other word choices to keep it succinct. EXISTING LINES THAT REMAIN UNCOVERED is probably too prosaic. Open to suggestions.

**Comment by jacobtylerwalls** [comment]
I like how the other one (NEW MISSED LINES IN DIFF) puts the payload up front: there's new lines and you missed 'em.

So, maybe LINES STILL MISSED? Not pushing here, but just since we're talking about it. Similar with the "Run Details", when I see "x now uncovered", my first thought is, "oh, meaning <i>starting</i> now, I just uncovered them?"

Wordsmithing is tricky--do as you please! And thanks for getting back so quickly.

**Comment by afinetooth** [comment]
I think LINES STILL MISSED sounds good. I've added your wording suggestions to an enhancement request in our backlog. Thanks for the input.

**Comment by afinetooth** [comment]
Closing for now due to incorrect answer. Left as-is, with correction, for reference.
