### ISSUE TITLE
Coverage sometimes goes away on summary page

### ISSUE THREAD

**Issue by jasonstitt** [lemurheavy/coveralls-public#1552]
- We have a repo set up with a coverage score displayed on the summary page
- Another build goes through
- The summary page shows a "hollow" (outline) % sign with no percentage. Sometimes there is a branch % listed in smaller type below that.
- On clicking into the repo page, there is an actual (and solid) percentage score shown at the top

Is there something we can do differently here to get the default branch coverage consistently shown on the summary page? Or is this potentially related to slow job runs?

**Comment by afinetooth** [comment]
Hi @jasonstitt, in the case I imagine you were referring to, the last build on your default branch had not completed. Which is to say, the very last background job had not completed, specifically, that which renders the TREE view in the SOURCE FILES table. This may relate to "slow job runs," in terms of build time, in that, sometimes, due to traffic, build times will be slow and a build will hang in a state like this until all its jobs complete. However, in this case, it seems the final job hung permanently, or failed, leaving the build in its unfinished state, which did not update the coverage cache for the repo. 

In case like this, you have two options:

1. Re-run the build at your CI (if your CI offers that feature).
2. Contact us at support@coveralls.io and we can run the procedure that the failed job would have run.

Sorry for the inconvenience.

There is an existing issue in our backlog to address the resulting missing coverage data on the ALL REPOS index page. I have added your case as an example.
