### ISSUE TITLE
Clarification: is github write permission needed for PR comments in private repo?

### ISSUE THREAD

**Issue by darynmitchell** [lemurheavy/coveralls-public#1553]
The [docs for notifications](https://docs.coveralls.io/coveralls-notifications) say that for private repo,
> If you have a private repo that you would like to receive pull request comments on, you will need to allow **pull access** for our Coveralls bot

What does "pull" access mean?

I see issue comments from April 2020 ([eg](https://github.com/lemurheavy/coveralls-public/issues/1313#issuecomment-611752531)), May 2020 ([eg](https://github.com/lemurheavy/coveralls-public/issues/1280#issuecomment-633279419) [and](https://github.com/lemurheavy/coveralls-public/issues/1091#issuecomment-633279309) [and](https://github.com/lemurheavy/coveralls-public/issues/1062#issuecomment-632960914)) and June 2020 ([eg](https://github.com/lemurheavy/coveralls-public/issues/1371#issuecomment-649134035)) where @afinetooth said that "write" permission is needed.

But then in [September 2020](https://github.com/lemurheavy/coveralls-public/issues/1370#issuecomment-694561377), @afinetooth noted:
> We've addressed potential root causes for a number of these issues in the past 5-6 months (not receiving PR comments, PR comments being delivered late, not receiving more than one PR comment for the same PR, discrepancies in badge coverage, etc). At this point, to effectively address a specific issue we'd need a recent example.

So I just want to pin down, was access level fixed for PR comments? What exactly does "pull" access mean?

I'm just trying to understand
1. how to configure coveralls to get PR comments showing coverage change
2. why in the world github "write" role would be needed, when "read" role allows commenting on pull requests. Considering that ["write" access would allow]() the coveralls bot to push arbitrary code to our private repo (as well as delete commits, pull requests, and issues), that seems like something that I could never allow past risk assessment... what am I missing here?

Thanks for clarifying.

**Comment by afinetooth** [comment]
@darynmitchell as we discussed this via email, I will just summarize our findings here:

### Previously, PR Comments required Write access to repo:
When our **PR Comments** feature was implemented, we needed to support use cases where **Contributor** access was limited to the **repo** level (no **Github Org** involved), and where, compared to **org**-level, there is a lack of granular access permissions and all **Contributors** have **Write** access to the repo.

Specifically, to receive **PR Comments**, Coveralls users needed to add the [Coveralls Bot](https://github.com/coveralls) user as a **Contributor** to their repos, which would give our bot **Write** access to each repo. This posed an unacceptable security concern for some potential customers, but was a limitation we couldn't overcome at the time.

### Now, PR Comments can be enabled via Read Only access, this way:
In the meantime, it appears that&mdash;possibly due to changes at Github&mdash;Coveralls users with security concerns can avoid giving the [Coveralls Bot](https://github.com/coveralls) **Write** access to their repos, _if their Coveralls subscription is associated with a **Github Org**_, by adding the [Coveralls Bot](https://github.com/coveralls) to their **Org** via **[Your Github Org] > People > Outside Collaborators**, then adding the [Coveralls Bot](https://github.com/coveralls) to each intended repo with **Read Only** access:

![bot_can_comment_with_read_only_access](https://user-images.githubusercontent.com/918667/121073772-d0a63d00-c787-11eb-843c-88ebd8066fec.png)

Based on tests, this method _does_ appear to allow **PR Comments _without_ giving Write access** to the [Coveralls Bot](https://github.com/coveralls) user. 

So this should be the approach for Coveralls users with this specific security concern.

We will update our [docs here](https://docs.coveralls.io/coveralls-notifications) shortly to reflect this.  

Closing issue for now, please just reopen if necessary.
