### ISSUE TITLE
Coverage badges are not working 

### ISSUE THREAD

**Issue by rajasegar** [lemurheavy/coveralls-public#1554]
The coverage badges in my repo are showing `coverage unknown` though the coverage is showing in the coveralls website properly. Repos here:
https://github.com/rajasegar/moment-dayjs-codemod
https://github.com/rajasegar/ember-tailwind-codemod

**Comment by afinetooth** [comment]
Hi @rajasegar. The reason for that is that the coverage badge reflects the latest coverage % for your _default_ branch, and there are no builds for your default branch (**main**) in either of those projects.

Specifically, though, the issue relates to all branches because the correct branch values are not coming over to us.

Notice the BUILD HISTORY table in both of these repo pages:

https://coveralls.io/github/rajasegar/moment-dayjs-codemod
![Screen Shot 2021-06-04 at 1 50 23 PM](https://user-images.githubusercontent.com/918667/120861193-d0196680-c53b-11eb-8f80-c1f105895770.png)

https://coveralls.io/github/rajasegar/ember-tailwind-codemod
![Screen Shot 2021-06-04 at 1 50 40 PM](https://user-images.githubusercontent.com/918667/120861212-da3b6500-c53b-11eb-9e85-fc78b016c3f1.png)

Values in the **BRANCH** column are all "?", which means they're missing from the incoming JSON in your POST to the [Coveralls API](https://docs.coveralls.io/api-reference).

Similarly, we're getting no value for the param `service_name`, which is why the **VIA** column is empty.

This appears to be a configuration issue. Seems the relevant CI env vars are not getting mapped to the required JSON fields the API expects.

If you would please run some new builds in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v), we can see exactly what JSON you're sending in your POST.

Since your project is in Javascript, I'll assume you're using [node-coveralls](https://github.com/nickmerwin/node-coveralls) as your Coveralls integration, in which case you can pass the `-v` or `--verbose` flag where you're calling the `coveralls` command in your CI config, or you can set the CI env var: `NODE_COVERALLS_DEBUG=1`.

**Comment by rajasegar** [comment]
OK , let me try with the verbose flag

**Comment by rajasegar** [comment]
This is the run with verbose flag, I noticed the branch value is still undefined.
https://github.com/rajasegar/ember-tailwind-codemod/actions/runs/909073251
Anyway the issue is resolved if I use the coveralls/github-action
https://github.com/coverallsapp/github-action
The coverage badge is working fine now after using the github action

**Comment by afinetooth** [comment]
I see. Yes, you can see that's not coming over in the `git` hash provided through your CI:

![Screen Shot 2021-06-07 at 3 34 37 PM](https://user-images.githubusercontent.com/918667/121095812-e0347e80-c7a5-11eb-915c-8d7826918957.png)

Sometimes that needs to be configured at the runner level.

In any case, the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) is a good option. If you're happy using that, it will handle the mappings for you.

Glad you found a solution.

I will close this for now, just re-open if needed.
