### ISSUE TITLE
MS Teams: WebHook Integration throws error 400

### ISSUE THREAD

**Issue by asheynkman** [lemurheavy/coveralls-public#1555]
MS Teams WebHooks Integrations keep throwing error 400. How can you make it work?

**Comment by afinetooth** [comment]
Hi @asheynkman. As we resolved this via email, I'll share the conclusions for others with the same issue below:

## Note:
This issue relates to the **Coveralls Notifications** feature, found in **_[Your Repo] > Settings > Notifications_**, which enable your Coveralls repo to send coverage updates via notifications to various services, including **_Email_**, **_Slack_**, _(Generic) **Webhook**_, etc.

Notably, this issue is **_not_** related to the **Parallel Builds Webhook** feature (aka. the **webhook _endpoint_** of the [Coveralls API](https://docs.coveralls.io/api-reference)), which is [discussed here](https://docs.coveralls.io/parallel-build-webhook).

---

## Supported notification services:
Coveralls currently supports sending notifications to these services:

- Email
- Slack
- Hipchat
- Gitter
- Webhook (Generic JSON)

We do _**not**_ currently support the [Microsoft Teams](https://www.microsoft.com/en-us/microsoft-teams/teams-for-work) service.

Custom support for such as service would probably entail data formatting to support a proprietary messaging standard, which could include authorization headers, required fields (like target channel), etc.

The best we can offer at this time to to use the most _generic_ notification, the **Webhook Notification**, which sends simple JSON to a designated endpoint, and choose as your endpoint an iPaaS platform, such as Zapier.com, that will connect with **Microsoft Teams**.

Here's how that would look using a sample Coveralls project and Zapier.com account:

1) Create a New "Zap" with a **Zapier Webhook** _Trigger_:

![screencapture-zapier-app-editor-99400620-nodes-99400620-setup-2021-06-03-17_55_53 (1)](https://user-images.githubusercontent.com/918667/120863295-289e3300-c53f-11eb-8f43-6419687d44fc.png)

2) Choose **Microsoft Teams** as the next step, the _Action_:

![screencapture-zapier-app-editor-99400620-nodes-99400620-sample-2021-06-03-17_41_47 (1)](https://user-images.githubusercontent.com/918667/120863364-4370a780-c53f-11eb-98d0-c6004cdac8a7.png)

*Examining the trigger payload gives you an idea about the structure of the JSON object Coveralls is sending.*

3) Choose **Send Channel Message** as the Action and select the Channel where you want the message to go:

![Screen Shot 2021-06-03 at 5 43 18 PM](https://user-images.githubusercontent.com/918667/120863423-600cdf80-c53f-11eb-9563-33637206b960.png)

We're not affiliated with Zapier.com in any way. It simply has a free tier, but you have many alternative services like this to choose from.
