### ISSUE TITLE
COVERALLS_REPO_TOKEN as repository secret forbids coveralls to run for regular contributors (non-maintainers)

### ISSUE THREAD

**Issue by abravalheri** [lemurheavy/coveralls-public#1557]
Hello, first of all, thank you very much for all the support and love for the opensource community, it really helps a lot.

After the changes in the policy of TravisCI for opensource projects, I have been trying to move all the open source projects I participate to CirrusCI, since it have good, "unlimited", support for opensource.

In general using coveralls works perfectly, not many changes required. There is one thing, though, that seems very difficult to understand, and it is caused by the following factors:

- I need to specify `COVERALLS_REPO_TOKEN`, otherwise the error `Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.` happens.
- When adding the token, [coveralls docs](https://docs.coveralls.io/supported-ci-services) seem to recommend keeping the token secret.
- This works fine for owners and maintainers of the repository, however PR from regular contributors cannot access secrets, and therefore coveralls fails to run... The sad part is that having statics about how much PRs impact on the coverage is very handy...

I believe this is a common problem in several CI solutions: it does make sense to hide secrets from occasional contributors, otherwise they could simply submit a PR changing the CI configuration to simply print the secret as plan text.

Do you guys have any good practice/workaround associated with this issue? Is there an alternative flow (that does not use TravisCI) that do not require specifying the token?

**Comment by afinetooth** [comment]
Hi @abravalheri. Thanks.

Have you tried setting a _private environment variable_ at your CI? 

I'm not familiar with Cirrus CI features, but CIs like Travis, CircleCI, Gitlab CI and Github Actions will let you set a CI- or repo-scoped environment variable and will usually have a means of making it secret and obfuscating it from the build log:

**Gitlab CI: Settings > CI/CD > Secrets:**
![Screen Shot 2021-06-04 at 2 58 20 PM](https://user-images.githubusercontent.com/918667/120866674-4ec6d180-c545-11eb-83b4-db623d396a74.png)

**Github Actions: Settings > Secrets:**
![Screen Shot 2021-06-04 at 2 54 51 PM](https://user-images.githubusercontent.com/918667/120866449-d19b5c80-c544-11eb-9cd6-c9efa79f0dca.png)

^^ That would be the recommendation. ^^

I would also say that if your project is open-source (public repo), then many of the security concerns are moot and you could probably leave the repo token in your coveralls.yml. 

As a moderate security measure, if you have periods of contribution after which you want to close access, you can easily roll the token at intervals with the REGENERATE button next to it on your repo page and settings page:

**Repo page:**
![Screen Shot 2021-06-04 at 2 52 28 PM](https://user-images.githubusercontent.com/918667/120866303-7c5f4b00-c544-11eb-861f-513ce901b9a9.png)

**Settings page:**
![Screen Shot 2021-06-04 at 2 52 58 PM](https://user-images.githubusercontent.com/918667/120866339-8ed98480-c544-11eb-8935-90ceb48bdf72.png)

**Comment by abravalheri** [comment]
Hi @afinetooth, thank you very much for the clarification. That is definetely food for thought.

Yes, that is more or less what I did in Cirrus. I specified a private env var, but then it can only be decoded/read by maintainers.

I would argue that if CI services offer private env vars that can be read by regular contributors, than they are not really private, are they? Even if they are obfuscated in the logs, the security still cannot be guaranteed once regular contributors have access to decoding it.

One could, for example, change the CI configuration file in the PR (since nowadays configuration as code is prevalent) and use curl or other tool to post the secret to an external server, exposing it anyway. Alternatively, if the CI config cannot be modified by code, a malicious contributor could tamper with the test suite itself (making some part of the code post to an external service or print an encoded/modified version of the secret to the logs that is different from the original and therefore not obfuscated but still recoverable, e.g. a simple `rot13`).

I know this scenario of exposing the token is a bit unrealistic/conspiracist for public repos, but I am just trying to imagine the treat model and a possible attack surface area.

Please correct me if I am wrong, but so far it looks to me that **either**:

- It is necessary a code review before allowing the CI to run, but this is far from ideal:
    - Running the CI as soon as possible for PRs allow developers to quickly fix problems they have introduced without noticing even before the maintainers/code owners have time to review the PR, which help saving time and energy. 
    - There are several services that can run in the CI that help to alleviate the load of a review and help the maintainers to take decisions, such as linters, automated security tests, complexity analysers, automatic code smell detectors, etc…
    - Coverage change is a very important factor to be considered during a review, for approving PRs.
    - Dividing the review process in 2 stages (before/after CI) discorages reviews.

**or** 

- Requiring a token for public repositories is not really offering any extra security. In this case, coveralls does not seem to offer a solution against "project impersonation" other than "limiting PRs to trusted contributors".
   - Is it correct to say that a token would be then useful just for billing purposes?

What are your thoughts about this matter? (I am no security specialist and this reasoning can easily be flawed, I am just trying to understand what would be the best workflow and its associated treat model for using coveralls).

**Comment by afinetooth** [comment]
Hi @abravalheri. 

Well, if there's any lack of concern on my part it would be due to what I consider a relatively small "surface area" of attack, as you put it.

The Coveralls repo token is limited to one function, submitting coverage data to coveralls, and to only one port of entry, the /jobs endpoint of the Coveralls API: https://coveralls.io/api/v1/jobs. It's only used there to identify your repo at our service and doesn't give anything like user access or access to source code, etc.

Literally the only thing a user could do, as malicious use of the token, would be to submit an incorrect coverage report (let's assume a _better_ one) to Coveralls, which would give a rosier view of a particular PR to someone reviewing the difference in coverage %.

But this is something a user could do anyway if they were so motivated, even without knowing the repo token. 

I'm thinking about Github Actions, where a user can be a contributor, but not an admin, and therefore not have access to repo secrets. In this case, the contributor can make their changes in a PR, then the GHA workflow will build the PR and send its coverage stats to Coveralls, during which the stored secret is used without the contributor being the wiser. 

Perhaps a worse "worst case" would be a third party posting to coveralls from an imposter repo (via CI or command line), having somehow obtained the repo token. But again, all they would have done is add a coverage report for a commit that, likely, coveralls would not be able to find in your repo (unless they managed to get the commit sha right).

As I say, knowing the repo token wouldn't give such a user any more access to your repo at Coveralls than they have through Github. That token doesn't give a Coveralls _user_ access to your repo. (again, its scope of use is limited to POSTs to the /jobs endpoint of the Coveralls API: https://coveralls.io/api/v1/jobs.)

So if you're concerned about such an actor accessing the repo at Coveralls and, say, using the line-by-line coverage feature to view source code (in this scenario, for a private repo), they _couldn't_. On every login to Coveralls we check the user's access token against their current access privileges at Github. So, if the user doesn't have access to the repo at Github, they won't gain access to the repo or its resources via Coveralls.

Furthermore, the line-by-line coverage feature is based on a real-time API call to the Github API using the current user's access token, in which the file is read and re-constructed line-by-line for just that view. No source code is stored at Coveralls.

Am I missing another scenario you're thinking of?

**Comment by abravalheri** [comment]
Hi @afinetooth, I think it pretty much describes it all, thank you very much for the detailed explanation/review.

The scenario I was imagining the most was an imposter trying to submit a worse coverage data trying to discredit a project (but as I admitted before, it is very much non-realistic, just more of a thought exercise).

So I suppose there is no real benefit in trying to keep the token completely private, right? I suppose obfuscating it a bit in the logs using the options of the CI providers help, but no need to obsess with it being perfectly unreachable...

Thanks again for all the clarifications! 😄

**Comment by afinetooth** [comment]
@abravalheri I would tend to agree with that. You bet. Thanks for the input.
