### ISSUE TITLE
Coverage status showing unknown

### ISSUE THREAD

**Issue by dwmoffatt** [lemurheavy/coveralls-public#1561]
Coverage status shows Unknown but most recent coverage report shows 56%

https://coveralls.io/github/dwmoffatt/macro-zero

Any reason why it would not be updating?

**Comment by dwmoffatt** [comment]
I am using python coveralls to upload the coverage reports generated by pytest to the server

**Comment by afinetooth** [comment]
Hi @dwmoffatt. It's because the coverage badge represents the repo's "official" coverage, if you will. The coverage for what is likely the production release of the repo. Therefore, it's based on the coverage of the last build on your **default branch**, yours being **master**, and right now you don't have any builds on **master**.

If you accept one of your PRs, typically, the one with your coveralls setup, merge it into master and let CI build master, you'll have the first build contributing to your badge coverage.

**Comment by dwmoffatt** [comment]
@afinetooth 

That makes way more sense! I couldn't find that information in the docs anywhere. I will adjust my CI to do a build when PRs are merged into master and have that push the coverage report to coveralls. 

Thank you for the information and getting back to me quickly!

**Comment by dwmoffatt** [comment]
Just an update, I did what you described and it is working now! My only suggestion would be to make note of how the works in the docs. This issue can be closed! Thank you again for the speedy response!

**Comment by afinetooth** [comment]
Thanks @dwmoffatt. We're definitely intend to improve our documentation. For now, as the process may change given your project's language, we try to get users to start with the READMEs for the community-driven projects on our [current docs page](https://docs.coveralls.io/). Sometimes people miss it because it's in the left nav. It will be more prominent in our docs update. Thanks for the input.
