### ISSUE TITLE
False positive for uncovered existing lines on first build of PR

### ISSUE THREAD

**Issue by jacobtylerwalls** [lemurheavy/coveralls-public#1563]
Hi. 👋🏻  
Based on https://github.com/lemurheavy/coveralls-public/issues/1549#issuecomment-841500158, my understanding is that "UNCOVERED EXISTING LINES" means lines already uncovered in the target, then still uncovered after a build.

If that's right, then I'm still not certain why I'm seeing previously **covered** lines that I deliberately uncover--that are not part of my diff, just side effects--to be reported as "UNCOVERED EXISTING LINES". It seems this category includes any missed lines whether or not they were covered before.

See [this build](https://coveralls.io/builds/40651755) on https://github.com/jacobtylerwalls/music21/pull/33.

![Screen Shot 2021-06-16 at 7 48 03 PM](https://user-images.githubusercontent.com/38668450/122309177-cdbff080-cedb-11eb-97b1-845ca93c3320.png)

The messaging in the top right makes sense to me, "1 existing line in 1 file now uncovered", but the messaging in the center "UNCOVERED EXISTING LINES" seems to lump it in with what @afinetooth was walking me through (as a tangent on another issue) as referring to lines that were uncovered before and still uncovered after build, or in other words, just a FYI -- your file coverage isn't complete, fancy working on it while you're here?

Great service, just still need a little help understanding the reports. Thanks.

**Comment by afinetooth** [comment]
Hi @jacobtylerwalls. Apologies, this is on me.

Looking at my previous comment I believe I gave a mistaken definition of UNCOVERED EXISTING LINES. 

Where I said:
> UNCOVERED EXISTING LINES are lines that existed in the previous version of the file, _that were uncovered then_, and remain uncovered now.

I should have said:
> UNCOVERED EXISTING LINES are lines that existed in the previous version of the file, _that were covered before_, _but are uncovered now_.

Otherwise (if that's not the correct definition), there's no "diff" in the files, from a coverage perspective, between the two builds.

Since we are trying to show you where your coverage has _decreased_, and can be immediately corrected, we _would_ want to show you:

- Where new lines came in without coverage (UNCOVERED NEW LINES), and
- Where previously _covered_ lines are now _uncovered_ (UNCOVERED EXISTING LINES)

Comparing the [Base Build](https://coveralls.io/builds/39993924) to the [PR Build](https://coveralls.io/builds/40651755) related to [the build you mention above](https://coveralls.io/builds/40651755), for the file `music21/_version.py`, this holds:

![Screen Shot 2021-06-17 at 2 07 59 PM](https://user-images.githubusercontent.com/918667/122478766-d6b5ce00-cf7e-11eb-99be-4c1eb92fba19.png)

LINE 49 was _covered_ before, but is now _uncovered_.

As for my [comment](https://github.com/lemurheavy/coveralls-public/issues/1549#issuecomment-841500158) on the [previous issue](https://github.com/lemurheavy/coveralls-public/issues/1549)...

I think I convinced myself of the incorrect definition of UNCOVERED EXISTING LINES because the evidence seemed to be staring me in the face with [this file](https://coveralls.io/builds/39673217/source?filename=music21%2Ffeatures%2Fnative.py) from your [first PR build](https://coveralls.io/builds/39673217).

However, as I look again, I'm bothered, again but more after the contravening example, by the inconsistencies, like the fact that among LINES 121-131, LINES 121 & 125 were previously uncovered but are not marked UNCOV like the others in the set:

![Screen Shot 2021-06-17 at 3 03 07 PM](https://user-images.githubusercontent.com/918667/122478791-e1706300-cf7e-11eb-969a-b3cc81ef25bf.png)

(Previously, I considered that could be attributed to some branch-to-line conversion, or _something_ like that.)

Between the two PR builds having the same [Base Build](https://coveralls.io/builds/39672796), the [Second PR Build](https://coveralls.io/builds/39673881) looks correct, and aligns with the correct definition of UNCOVERED EXISTING LINES:

![Screen Shot 2021-06-17 at 3 17 28 PM](https://user-images.githubusercontent.com/918667/122479084-6196c880-cf7f-11eb-81f4-f3f5d4258375.png)

The same lines are uncovered, they've just moved position in the file. They're not marked UNCOV because they were _already_ uncovered before. In other words, no _coverage diff_ there.

So, I'm not sure what issue is at play with the [First PR Build](https://coveralls.io/builds/39673217), but there's something wrong with it that might be unrelated and would take a closer look.

I'm sorry to have added to your confusion around this.

I'm going to go try to correct my mistake in a readable way in the [previous issue](https://github.com/lemurheavy/coveralls-public/issues/1549).

**Comment by jacobtylerwalls** [comment]
Super. Thanks. Very clear. I get the intent of the reports now. Feel free to close or refocus this ticket however you like if there were any followups. Thanks again for the service. 👍🏻

**Comment by chapayevdauren** [comment]
Hi @afinetooth 
I am having the same issue, mostly in each PR
<img width="1118" alt="Screenshot 2022-05-19 at 16 01 09" src="https://user-images.githubusercontent.com/10752486/169271601-b026b8b4-04a6-40e7-a23e-ea5e1ca7b09f.png">
