### ISSUE TITLE
Account is not linked when commit is authored under the noreply github alias

### ISSUE THREAD

**Issue by forivall** [lemurheavy/coveralls-public#1568]
For my commits, i'm using the email "forivall@users.noreply.github.com", and on the committer history at https://coveralls.io/github/forivall/meh-ts-decorator, it does not link my github account. On github, my account is properly linked in the commit history. https://github.com/forivall/meh-ts-decorator/commits/latest

**Comment by afinetooth** [comment]
Hi @forivall, It appears we're using the full name associated with your github handle for most of those committer values in your build history. Also, those values aren't normally linked.

One question and one suggestion:

**Question**:
What is the use case you have in mind when you are expecting, or hoping, that the value for committer in your coveralls build history would link to your github profile page. (Or is it to your commit history for the project, like: https://github.com/forivall/meh-ts-decorator/commits?author=forivall?) What is the point of the link as you see it?

**Suggestion**:
If you start running some builds in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v), we can see exactly what JSON is being sent from your integration to the [Coveralls API](https://docs.coveralls.io/api-reference). 

This is to say, we'll see whatever your integration is taking from the CI environment and mapping to the ultimate JSON body in your POST to https://coveralls.io/api/v1/jobs.

I see you're using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action). Since that integration uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood, the best debug flag IMO will be to add the following CI environment variable (and value) to [your GHA config yaml](https://github.com/forivall/meh-ts-decorator/blob/latest/.github/workflows/main.yml):
`NODE_COVERALLS_DEBUG=1`

That should add debug output showing both the LCOV from your coverage reports and the JSON in your final POST to your build logs. That will give us an idea where to go from here if we want to try tweaking some of those values.

**Comment by forivall** [comment]
The point of the link is just to be consistent. Use case is so the data is correct. In addition to github using my full name for commits, i also have the following in my `.git/config`:
```
[user]
	name = Emily Marigold Klassen
	email = forivall@users.noreply.github.com
```
(I leave name/email empty and [`user.useConfigOnly`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-useruseConfigOnly) so i can use my work email for work repos, and noreply for public repos)

One other difference is that my [old config](https://github.com/forivall/meh-ts-decorator/blob/9e4328/package.json?ts=2#L30) was using travis-ci & directly calling node-coveralls. [(last travis build)](https://www.travis-ci.com/github/forivall/meh-ts-decorator/builds/233931313)

Enabling the debug flag, and since i committed using github's browser based editor, i see the following [in the action's log](https://github.com/forivall/meh-ts-decorator/runs/3205730235?check_suite_focus=true&ts=2#step:6:104):
`[info] "2021-07-30T21:16:57.279Z"  'sending this to coveralls.io: ' '`
```json
{
  "source_files": [...],
  "git": {
    "head": {
      "id": "db99371e283c13dc39331d4cf1d0de9ce20a08f7",
      "committer_name": "GitHub",
      "committer_email": "noreply@github.com",
      "message": "config: enable NODE_COVERALLS_DEBUG",
      "author_name": "Emily Marigold Klassen",
      "author_email": "760204+forivall@users.noreply.github.com"
    },
    "branch": "refs/heads/latest",
    "remotes": [{ "name": "origin", "url": "https://github.com/forivall/meh-ts-decorator" }]
  },
  "run_at": "2021-07-30T21:16:57.252Z",
  "service_name": "github",
  "service_job_id": "1083600983",
  "repo_token": "***"
}
```

Overall, this is low priority. It would just be nice to have the link, but the link isn't critical. I use coveralls over other coverage providers because the coverage reports are simply the most readable and useful, and this issue doesn't really impact that too much.

**Comment by afinetooth** [comment]
Thanks @forivall. 

Despite the care you've taken to ensure the right name/email values are being sent per your git config, I'm afraid we can't ensure those will always be the ones displayed given current coveralls functionality.

Currently, for `COMMITTER` in the build history, we display `committer_github_login` (from Github's Repos API: `repo.commit.committer.login`), with a link to Github, if it's provided and, when not, we substitute with `committer_name` or `committer_email`.

To always display your intended values requires a feature enhancement on our side, which is to display `COMMITTER` as `author_name` or `author_email`, first, respectively, when they're available, then `committer_name` or `committer_email` when not.

I've submitted that request. It'll be a great feature for users who want to be as intentional as you are.
