### ISSUE TITLE
Fluctuating values received from Coveralls even when there is NO change in the code

### ISSUE THREAD

**Issue by estebanzimanyi** [lemurheavy/coveralls-public#1572]
We have integrated Coveralls in our development process. However, the coverage value we receive continuously fluctuates even if we DO NOT CHANGE the code, for example when improving the documentation. This can be seen for example in the last commits from the develop branch
https://github.com/MobilityDB/MobilityDB/commits/develop

For example, in the last commit from on Aug 21, 2021 it is stated that the Coverage decreased (-0.04%) with respect to the previous one even if the only files changed were related to how the multiple versions of the documentation wrt formats (HTML, PDF, EPUB) and languages (EN, ES) are generated
https://github.com/MobilityDB/MobilityDB/commit/0e2a9eebb62790806547b2fcf26208b5559fb229
Similar situation can be seen in multiple commits related to the documentation.

I guess that a possible cause of the problem is how the rounding and the aggregation of the floating point values for individual files are performed.

Solving this issue would help us a lot in our process, because we have continuous fails in our commits due to this problem and we need to verify whether it is really the case that the coverage decreased or if it is just a rounding problem.

**Comment by estebanzimanyi** [comment]
To have a more precise example you can compare the two following coverages
https://coveralls.io/builds/42432062/source?filename=src%2Fgeneral%2Fskiplist.c
https://coveralls.io/builds/42407603/source?filename=src%2Fgeneral%2Fskiplist.c
The non-covered lines are exactly the same but one reports a coverage for the file of 98.6% and the other of 98.57%

**Comment by afinetooth** [comment]
Hi @estebanzimanyi,

Are you primarily concerned with coverage discrepancies between two **builds**? or between the **same file** across two builds?

I ask because, for your example, the details for a discrepancy between the two builds can be found in the **RUN DETAILS** for the build, which show enough differences to justify the coverage discrepancy between the two builds:

![Screen Shot 2021-08-27 at 3 04 22 PM](https://user-images.githubusercontent.com/918667/131193322-95f6ff70-974f-4fe7-830e-687b6c39f594.png)

It _is_ interesting to compare those two files:

![Screen Shot 2021-08-27 at 3 01 06 PM](https://user-images.githubusercontent.com/918667/131193133-c439586f-7ca4-463f-9b83-f749075101e2.png)

They could be considered identical, except for the rounding up of the value on the left (which came after the one on the right). I'm not aware of any particular rule we have about when to round to a certain degree, so it could be a bug.

However, we normally don't see this when all things are equal in your CI environment, beyond actual changes between two builds. Which is to say, if there was no change to a file, the coverage % would be identical.

I suspect the issue is rooted in the fact that you're using two different CI systems, which I noticed from the back-and-forth nature of the build numbers for your builds, like:

- 3067
- 1169994007
- 3068
- 1174232163

I see one is coming from Travis and the other is coming from Github Actions.

What else can you tell me about that? Is the code being built on different versions of OS for instance? Or being generated by different coverage libraries? 

Certainly, because they're different services, we can assume _some_ differences in the execution environment.

I noticed that comparing the same source code file between two builds from the _same_ CI environment, results in identical coverage %:

![Screen Shot 2021-08-27 at 3 18 13 PM](https://user-images.githubusercontent.com/918667/131194175-69dd426e-254d-4db9-8373-9009692fa3ce.png)

I also noticed that between the original two builds, themselves, as opposed to the one source code file shared between them:
https://coveralls.io/builds/42432062
https://coveralls.io/builds/42407603

The builds are not reporting the same source code files, at least not in the same directory structure:

![Screen Shot 2021-08-27 at 3 21 32 PM](https://user-images.githubusercontent.com/918667/131194449-032a39a5-b9ce-4185-9863-a7a56d2b19f8.png)

According to the LIST tab, the more recent build (left) from GHA, has 8 more source files than the earlier build (right) from Travis.

Last thing worth mentioning at this point is that, because your builds have only one (1) job each (they are not parallel), coveralls is not making any coverage calculations for the same file across multiple jobs, so in this respect the coverage calculation is simple and comes directly from what it's given in the report for each file, which is basically `covered lines / relevant lines`.

This doesn't answer why we'd round to a different degree for the exact same file, but it does beg the question as to whether the report inputs are identical since they're coming from two different CI environments. 

The most helpful next step, if the goal is to understand why the difference for one file between the two environments, would be to get a [verbose build log](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) (with debug output) for each build from each system, to compare the coverage for each exact file from each actual JSON object being posted to the coveralls API.

**Comment by estebanzimanyi** [comment]
Dear James
Thanks so much for your detailed message. You may remember that you help me to set up Coveralls on Github actions
https://github.com/lemurheavy/coveralls-public/issues/1567
and was so happy about that that I forgot to shut down the Coveralls on Travis. Now it is done on my commit https://github.com/MobilityDB/MobilityDB/commit/768a5c65b6ba73bdd234834255f54b3fed5b695d

We expect that the workflow fails when the coverage of the build decreases even for a small percentage, that would force us to look into the coverage. Is it implicit when leaving both "COVERAGE THRESHOLD FOR FAILURE" and "COVERAGE DECREASE THRESHOLD FOR FAILURE" to empty ?

However, despite that I looked for thoroughly, I didn't find in the documentation how to set up the debug flag in an environment variable in Github Actions.
Would you kindly help me to set things up ?

I really appreciate your continuous help !

Esteban

**Comment by afinetooth** [comment]
Hi Esteban, sorry I missed this when you posted it.

Since the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood, you can enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) by adding the following CI environment variable to your GHA config yaml:
`NODE_COVERALLS_DEBUG=1`

That should add the JSON you'll post to the [Coveralls API](https://docs.coveralls.io/api-reference) and, potentially as well, the LCOV version of your coverage report, prior to its conversion to JSON.

To answer your question:
> Is it implicit when leaving both "COVERAGE THRESHOLD FOR FAILURE" and "COVERAGE DECREASE THRESHOLD FOR FAILURE" to empty ? 

No, it is not. If you want to catch _any_ decrease in coverage, you'll want to set the COVERAGE DECREASE THRESHOLD FOR FAILURE setting to some very small value, like `0.1%` or `0.01%`.

As I see you have done!:
![Screen Shot 2021-09-07 at 4 24 35 PM](https://user-images.githubusercontent.com/918667/132422605-d6bcdeb4-223d-4e0d-af72-abdd7673a3ec.png)
