### ISSUE TITLE
My project send coverage by github action , coveralls.io is not update

### ISSUE THREAD

**Issue by tu6ge** [lemurheavy/coveralls-public#1577]
this is my last [github action](https://github.com/tu6ge/voyager-excel/runs/3468512669?check_suite_focus=true),

but coveralls.io result is not update , [link](https://coveralls.io/github/tu6ge/voyager-excel)

**Comment by afinetooth** [comment]
Hi @tu6ge, your issue was caused by the general performance issues we are experiencing.

Rest assured that your jobs have been processed. It will just take some additional time for the background jobs related to each job to perform aggregate coverage calculations and render the last elements of your build page. Until then , you may see the "Data Tables" error. Beyond that, coverage will remain "?" (in grey until those jobs complete. 

You can track status here:
https://status.coveralls.io/

Related:
- https://github.com/lemurheavy/coveralls-public/issues/1573
- https://github.com/lemurheavy/coveralls-public/issues/1574
- https://github.com/lemurheavy/coveralls-public/issues/1575
- https://github.com/lemurheavy/coveralls-public/issues/1576

**Comment by tu6ge** [comment]
all right

**Comment by afinetooth** [comment]
Hi @tu6ge, we would like to consider this issue closed since the root cause has been resolved:
https://status.coveralls.io/

If you experience it again, please re-report so we can address it as an individual issue with a different cause. Thanks.
