### ISSUE TITLE
Error: Bad response: 504 when filtering directories with the lcov tool

### ISSUE THREAD

**Issue by estebanzimanyi** [lemurheavy/coveralls-public#1578]
There could be a problem in Coveralls since we receive the error
```
Error: Bad response: 504 
```
when using the standard `lcov` tool for filtering directories on which the coverage information are collected.
Compare the commit
https://github.com/MobilityDB/MobilityDB/commit/2ef7f77335c25c4025884dc6679fa94fb9a725ab
which solved the issue in the previous commit
https://github.com/MobilityDB/MobilityDB/runs/3465656814
Basically, the output of the following command works with Coveralls
```
lcov --capture --directory . --output-file=lcov.info
```
but the output of following commands
```
lcov --capture --directory . --output-file=lcov_temp.info
lcov --extract lcov_temp.info */MobilityDB/src/* --output-file=lcov.info
```
send the above error.

**Comment by afinetooth** [comment]
Hi @estebanzimanyi, it's almost certain your issue was caused by general performance issues we've been experiencing for the past 24-36 hrs.

You can track status here:
https://status.coveralls.io/

For some time, the API was intermittently unavailable, returning 5XX errors. At this point, the API is operational so you can retry your build(s). Please just be aware that we're still experiencing degraded performance with the Web UI so your build pages will not fully render for some time. The background jobs that perform your aggregate calculations and render some interactive elements on each build page are backed up in heavy traffic. 

You can rest assured that any jobs accepted by the API will be processed in time without any further action required from you. We are doing our best to clear the traffic and get back to normal performance by this afternoon.

Related:
- https://github.com/lemurheavy/coveralls-public/issues/1573
- https://github.com/lemurheavy/coveralls-public/issues/1574
- https://github.com/lemurheavy/coveralls-public/issues/1575
- https://github.com/lemurheavy/coveralls-public/issues/1576
- https://github.com/lemurheavy/coveralls-public/issues/1577

**Comment by estebanzimanyi** [comment]
Many thanks for your answer James. Indeed, the problem is solved now. Many thanks for your continuous help !

**Comment by afinetooth** [comment]
My pleasure. Thanks for your patience, Esteban.
