### ISSUE TITLE
Branches not correctly fetched from github - badge not showing

### ISSUE THREAD

**Issue by jhannes** [lemurheavy/coveralls-public#1581]
In one of my repositories, the builds in Coveralls are linked to commit hashes instead of the `main` branch. The repository in question is https://coveralls.io/github/jhannes/logevents?branch=main

I suspected that the reason for this was that I renamed the default branch from `master` to `main` and Coveralls was unable to sync the branch names, so I tried to delete the repository in coveralls and recreate it but the problem persists.

When I try to sync branches, the progress spinner never stops. This is due to a 500 while performing the request https://coveralls.io/repos/351454/sync_branches.json

**Comment by afinetooth** [comment]
@jhannes will look into this asap as the site is currently in emergency maintenance:
https://status.coveralls.io/

I suspect the 500 error you received on Friday related to the root cause for the [original maintenance window](https://status.coveralls.io/incidents/ppvnbpd172gy), which started then.

**Comment by afinetooth** [comment]
Hi @jhannes I checked this morning and your latest build appears normal and your default branch shows as main with no new info detected upon a repo sync. This indicates things should be back to normal. Let me know if not.

**Comment by andyholmes** [comment]
I had the same problem after changing my branch from `master` to `main`, which happened to occur during the maintenance period. I had tried refreshing the repository info without success so I deleted and re-added the repo.

After some time (over an hour at least) I finally got results on coveralls.io. It's possible there's just a backlog after coveralls came back online, so maybe if I had waited if it would have succeeded updating by itself.

**Comment by jhannes** [comment]
@afinetooth I still have a commit hash showing instead of the main branch, the "sync branches" button spinning forever and a failed request to https://coveralls.io/repos/351454/sync_branches.json with 500.

**Comment by afinetooth** [comment]
Hi @jhannes. Thanks for you patience. 

So that `500` you're receiving is because we can't find the branch to sync and (probably obvious) that's because we're not receiving branch names, but rather the hashes you mention.

The [Coveralls API](https://docs.coveralls.io/api-reference) will accept whatever you pass it for `branch` in the `git` hash for your job's POST, so I have every reason to believe the branch value is coming across from your CI as one of those hashes (likely from being in detached HEAD state). which means the tuning needs to be done on the CI side.

We can verify that by running a new build, or re-running an old build in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v), which adds debug output to your CI build log and shows the exact JSON you're POSTing to the [Coveralls API](https://docs.coveralls.io/api-reference).

I can't tell what CI you're using from your build pages, for example:
https://coveralls.io/builds/42996638

But I can see you're building a Java project. 

The way to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) will depend on the integration you're using, so if you are using the community-created Java integration listed [here](https://docs.coveralls.io/java) ([coveralls-maven-plugin](https://github.com/trautonen/coveralls-maven-plugin)), [this](https://github.com/trautonen/coveralls-maven-plugin/blob/8b8995e42768a25c8db6e85ede62238bf4606cb2/src/main/java/org/eluder/coveralls/maven/plugin/logging/JobLogger.java#L91) is the closest thing to a debug flag I can find. 

If you _are_ using [coveralls-maven-plugin](https://github.com/trautonen/coveralls-maven-plugin), you may want to search the project's [issues](https://github.com/trautonen/coveralls-maven-plugin/issues) to see if other users mention it, or ask there how to enable debug mode.

Likewise, if you're using a _different_ Java integration, you can consult _that_ project's README or issues.

Let me know what Java integration you're using and I'll try to help with that.

Another way to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) is available through a couple of CI-specific coveralls tools, like the [Coveralls Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls) and the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action). Those come with their own debug flag, which we can employ if you're using one of those (let me know).

Once we can examine the `git` hash param in the JSON you're sending to the Coveralls API, we can verify your CI is sending a hash (likely from building in detached HEAD state) instead of the current branch, and proceed on fixing that.

Otherwise, if you take my suspicion as a viable assumption and you know how to get your CI to pass the branch name, such as by reverting from detached HEAD state or pulling the branch in a step before running coveralls, the issue might fix itself.

Let me know how I can help from here.

**Comment by afinetooth** [comment]
@andyholmes if you'd like some help with your project, I'll need to know the Coveralls URL for your repo and/or a specific build URL. Thanks.

**Comment by andyholmes** [comment]
@afinetooth All good :) I thought I had the same problem, but it resolved itself. Thanks!

**Comment by afinetooth** [comment]
@andyholmes great.

**Comment by jhannes** [comment]
@afinetooth Thank you for following up. It took me a while to make the necessary investigations.
When I run it on [Github Actions](https://github.com/jhannes/logevents/runs/3729453526?check_suite_focus=true#step:6:2706) the value of branch is `null`. However, when I run it locally, it correctly lists `branch: "main"`.

I am stumped why this may be as I have several other projects with Coveralls that seem run correctly in Github Actions, for example https://github.com/jhannes/action-controller

**Comment by afinetooth** [comment]
Hi @jhannes, unless I'm wrong, it looks like you're getting hashes for branch names in this project too:

https://coveralls.io/github/jhannes/action-controller

![Screen Shot 2021-09-28 at 11 38 09 AM](https://user-images.githubusercontent.com/918667/135146154-0cfa62de-e83c-495d-af5a-9d9e51afa069.png)

This issue crops up from time-to-time and I haven't been able to identify a single cause, only case-by-case solutions. Usually, the issue is related to default CI configuration, using a self-hosted runner, doing a squash merge or rebase right before your build, etc.

Without figuring out why CI is passing a hash instead of a branch name, the solution is usually something as simple as adding a step to your CI config file that does a `git checkout` on the branch, which seems to add the branch name to the appropriate CI env vars.

Unfortunately, since you're not using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), I can't offer a verbose flag to add debug output to your build log. It could be useful to see what CI is providing in the `git` hash. However, it's just as likely all we'll do is confirm that it's populating `git["branch"]` with the hash we're seeing in your build history (like the above screenshot).

Can you try adding a `git checkout` (on the current branch) to your GHA config YAML somewhere before [this line](https://github.com/jhannes/action-controller/blob/main/.github/workflows/maven.yml#L24)? 

You're basically trying to get CI / git out of "detached HEAD" state, which CI may be building in for various reasons (squash merge, rebase, etc.). [This explanation from Bitrise CI docs](https://devcenter.bitrise.io/faq/how-can-i-git-checkout-from-a-detached-head-state/) is as good as any I've seen on what that state is and how to "recover" from it. [This blog post](https://www.cloudbees.com/blog/git-detached-head) is good too.

**Comment by jhannes** [comment]
I made a quick effort to do a git checkout, but it didn't seem to change things. It sounds like using the Coveralls Github Action would be a good way forward, but I can't find a Maven plugin that generates lcov-files. Is there are tutorial anywhere?

**Comment by afinetooth** [comment]
Hi @jhannes, yes, that is a limitation users of some languages run into (Java, Python). On the python side, there's a separate community-created Github Action used by many python devs [here](https://github.com/TheKevJames/coveralls-python).

From [this issue](https://github.com/coverallsapp/github-action/issues/22), I found [this resource](https://github.com/danielpalme/ReportGenerator):
https://github.com/danielpalme/ReportGenerator

> ReportGenerator converts coverage reports generated by coverlet, OpenCover, dotCover, Visual Studio, NCover, Cobertura, JaCoCo, Clover, gcov or lcov into human readable reports in various formats.

Doesn't exactly match your need from that description, but this list of its [Output Formats](https://github.com/danielpalme/ReportGenerator/wiki/Output-formats) indicates LCOV might be an export format:
https://github.com/danielpalme/ReportGenerator/wiki/Output-formats

This [online configuration tool](https://danielpalme.github.io/ReportGenerator/usage.html) also indicates you can pick LCOV as the output format for any input format, like XML:
https://danielpalme.github.io/ReportGenerator/usage.html

Another thing: The tool appears to be for use with .NET, but it looks like they have a [package for Github Actions](https://github.com/danielpalme/ReportGenerator#install-the-package-matching-your-platform-and-needs) here:
https://github.com/marketplace/actions/reportgenerator

Support for Github Actions is something [users of the coveralls-maven-plugin have been asking for](https://github.com/trautonen/coveralls-maven-plugin/issues/136) as well, apparently. You might find something helpful in that regard, in the body of this issue:
https://github.com/trautonen/coveralls-maven-plugin/issues/136

Hope that helps!
