### ISSUE TITLE
Bad response: 405

### ISSUE THREAD

**Issue by Kikobeats** [lemurheavy/coveralls-public#1582]
Hello,

I'm experiencing the following errors:

```
Run coverallsapp/github-action@master
  with:
    github-token: ***
    path-to-lcov: ./coverage/lcov.info
    coveralls-endpoint: https://coveralls.io
  env:
    CI: true
Using lcov file: ./coverage/lcov.info
Error: Bad response: 405 <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

You can see it here: https://github.com/microlinkhq/mql/runs/3644042637

Not sure if it's something I can fix on my side; it worked well in the past 🤔

**Comment by dgw** [comment]
Because of [this database maintenance](https://status.coveralls.io/incidents/ppvnbpd172gy) since Sept. 17 evening (PDT).

**Comment by afinetooth** [comment]
@Kikobeats, @dgw is correct. Apologies, both, for the inconvenience.

### tl;dr:
We are back in maintenance mode right now, with hopes of returning to production in the next hour. However, there's a chance we'll need to remain in maintenance for the bulk of today, in which case, we recommend removing the coveralls steps from your non-crucial CI builds until later today.

Updates posted here:
https://status.coveralls.io/

Feel free to check in here as well.

### More detail:
We took the site out of maintenance mode at about 3am this morning at about 95% complete, but then transactions slowed and started failing. It turns out one index on our largest table is still rebuilding, or perhaps failing---in any case, was taking very very long to rebuild, so we put the site back in maintenance mode to let it finish or troubleshoot.

We have our Postgres consultants and AWS resources on it, so hopefully we'll be able to take it back out of maintenance soon, but the word I have now is that we could be down for most of today as the large index rebuilds. We might be able to rebuild it during production if we complete a Postgres upgrade, which is what the team is looking at right now.

In the scenario where we're down most of today, you might want to disable coveralls steps for any non-crucial CI builds until later today.

---

### Related:
- https://github.com/lemurheavy/coveralls-public/issues/1583
