### ISSUE TITLE
DataTables warning: table id=DataTables_Table_0

### ISSUE THREAD

**Issue by woblerr** [lemurheavy/coveralls-public#1584]
Hi, 
I'm getting an error 
`DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

For example, job: `https://coveralls.io/jobs/87199716`

Perhaps, there are still some problems after db maintenance.

**Comment by afinetooth** [comment]
Hi @woblerr, that may or may not be related to the recent service outage, but it is an effect of degraded performance based on traffic on shared resources. We use a couple of background jobs to complete the render of your build page, which includes a job that calculates your aggregate coverage % after all jobs are received, and a final one that renders the interactive view in the TREE tab of the SOURCE FILES table. Those can be delayed when there is heavy traffic in the background job queues, which there is right now, not only because of the time of day but also because all users are now restarting their builds after the outage. That Data Tables error, specifically, is shown when the final job that renders the TREE view is delayed.

We're keeping an eye on the background queues traffic and may need to take action to clear those if we reach a certain point. Based on current traffic, please check back in an hour or so and let us know if it's still the case.
