### ISSUE TITLE
Random coverage failures

### ISSUE THREAD

**Issue by zeux** [lemurheavy/coveralls-public#1595]
We keep seeing occasional errors during coverage runs on https://github.com/Roblox/luau project.

Here's the latest:
https://github.com/Roblox/luau/runs/4299224527 (11/23)

Here's more:
https://github.com/Roblox/luau/actions/runs/1490911436 (11/22)
https://github.com/Roblox/luau/actions/runs/1488639950 (11/21)
https://github.com/Roblox/luau/actions/runs/1481803053 (11/19)

This happens on different PRs and doesn't seem to happen on master builds.

The action setup (which simply uses the GHA provided by Coveralls):
https://github.com/Roblox/luau/blob/master/.github/workflows/build.yml#L77-L81

In all cases the error log looks like this (with different hashes):

```
Using lcov file: ./coverage.info
Error:  "2021-11-22T04:22:45.062Z"  'error from getOptions'
Error: Error: Command failed: git cat-file -p 8089ae44597a4c95ac193ce0cc2efc28c8036649
fatal: Not a valid object name 8089ae44597a4c95ac193ce0cc2efc28c8036649
```

I initially thought this is a one-off but this happens with alarming repeatability in the last week.

**Comment by afinetooth** [comment]
Hi @zeux.

We've seen this occasionally, but aren't sure of the cause because it's intermittent.

The line that throws the error appears to be [this one](https://github.com/nickmerwin/node-coveralls/blob/565da5f354758903445db6cbee3bdba9ec697b9e/lib/fetchGitData.js#L72).

It indicates the local git repo has no ref as given. Similar to <a href="https://community.atlassian.com/t5/Bitbucket-Pipelines-questions/Cannot-use-git-commands-inside-a-step/qaq-p/1467919#:~:text=The%20git%20error%20%22fatal%3A%20Not,all%20the%20remote%20references%20(incl.">what's described here</a> when the ref is a branch name, like "master."

The best next step will be to re-run those builds (or run some new ones) in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v), which will add debug info to your build logs, which should present some clues.

The way to invoke [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) for the[ Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) is to add the following CI environment variable to your GHA config yaml so that it's available to your coveralls step:
`NODE_COVERALLS_DEBUG=1`

_The "NODE__" part is there because the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood, which is also where [that line of code](https://github.com/nickmerwin/node-coveralls/blob/565da5f354758903445db6cbee3bdba9ec697b9e/lib/fetchGitData.js#L72) comes from.

Please share the verbose build log the next time this happens and we'll look deeper.

**Comment by afinetooth** [comment]
@zeux on the hunch your CI is (occasionally?) building in [detached HEAD](https://www.cloudbees.com/blog/git-detached-head) mode (which would explain why the ref doesn't exist at Github---because CI is creating an ephemeral commit just for the current build), it could be worth trying the suggestions [here](https://www.cloudbees.com/blog/git-detached-head) or [here](https://stackoverflow.com/questions/10228760/how-do-i-fix-a-git-detached-head) (to "recover" from detached HEAD state) to see if that fixes it.

Again, your [verbose build log(s)](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) will help uncover whether that's the issue.

**Comment by zeux** [comment]
Here's a new instance of this which comes with verbose logs that we've enabled:

https://github.com/Roblox/luau/runs/4435306714?check_suite_focus=true

Note that as per above we're simply using GitHub Actions, along with checkout@v1 without arguments; if something is creating a detached HEAD it's the action itself but that would seem surprising.

Also attaching zipped logs from the CI run just in case.

[coverage.zip](https://github.com/lemurheavy/coveralls-public/files/7663215/coverage.zip)

**Comment by zeux** [comment]
The logs don't seem to show anything beyond the error; maybe it would make sense to print GHA-supplied hashes as well as a git log for the last 10 commits? I'm not sure where the hash noted in this run is even coming from.

It's puzzling to me that this issue is spurious. It feels like checkout action either detaches the head or doesn't, and in either case we'd either see the problem always or never...

**Comment by afinetooth** [comment]
@zeux you're right, it does seem like the issue would be persistent if that's the case.

I found [this (solved) issue](https://github.community/t/github-sha-not-always-correct/117863) on the github community board, which mentions intermittently getting incorrect values for `GITHUB_SHA` when using `checkout@v1.0`: 

- [GITHUB_SHA not always correct](https://github.community/t/github-sha-not-always-correct/117863). 

The solution recommends upgrading to version `>= 2.2.0` of the [checkout action](https://github.com/actions/checkout).

The [Coveralls Github Action](https://github.com/coverallsapp/github-action) uses `GITHUB_SHA` if you don't pass a value for its `git-commit` parameter. [Here's the line where it picks that up](https://github.com/coverallsapp/github-action/blob/9ba913c152ae4be1327bfb9085dc806cedb44057/lib/run.js#L49). And [here's where it _would_ be replaced if you passed a value for `git-commit`](https://github.com/coverallsapp/github-action/blob/9ba913c152ae4be1327bfb9085dc806cedb44057/lib/run.js#L57-L61).

FWIW, the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) hands over its inputs for processing to the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration (which as I mentioned above, is running under-the-hood), and [here is where the error you're seeing gets thrown by that code.](https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/getOptions.js#L214-L225)

This is the best I have at the moment. Figured it's worth trying.

**Comment by afinetooth** [comment]
Here's more background on the same issue from [Coveralls Github Action issue board](https://github.com/coverallsapp/github-action/issues):
https://github.com/coverallsapp/github-action/issues/55

**Comment by zeux** [comment]
Thanks! This sounds very similar. I'm going to assume that this is checkout@v1 related and speculatively close this. We've switched to checkout@v2 and added a few more debug logs to the build step in question - if it does fail again I'll reopen this with more information (which would likely be 2022 at this point).

**Comment by afinetooth** [comment]
@zeux sounds good. Good luck.
