### ISSUE TITLE
Repository missing files and showing 0% coverage

### ISSUE THREAD

**Issue by Wiston999** [lemurheavy/coveralls-public#1598]
Hi,
I have a repository that is missing the files content and the coverage is showing 0%.

Repository is https://coveralls.io/github/Wiston999/terraform-visual and the code that uploads coverage report is at https://github.com/Wiston999/terraform-visual/blob/master/.github/workflows/push.yml#L38.

I've tried deleting and recreating the repository in coveralls.io but it still missing the files.

**Comment by afinetooth** [comment]
Hi @Wiston999. 

Recently, we've heard about similar issues with Github Actions.

The best way to diagnose will be to run some new builds (or re-run an old build) in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v), which adds debug info to your build logs, including:

1. Your original coverage report (LCOV)
2. The JSON you're sending to the [Coveralls API](https://docs.coveralls.io/api-reference)

Given the behavior, I suspect we'll see, in (2), an empty array for the value of `source_files` as described in the [Coveralls API Reference](https://docs.coveralls.io/api-reference).

Seeing your coverage report from (1) then will let us know if the problem came up while reading the file, or while converting it into JSON.

To enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) for the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), declare the following CI environment variable in your GHA config yaml so that it's available to the [coveralls step](https://github.com/Wiston999/terraform-visual/blob/master/.github/workflows/push.yml#L35-L42):
`NODE_COVERALLS_DEBUG=true`

(_The "NODE_" part is there because the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood._)

Please share the link to your verbose [GHA build log(s)](https://github.com/Wiston999/terraform-visual/actions).

**Comment by Wiston999** [comment]
Hi,
thanks for your promptly answer.
[Here](https://github.com/Wiston999/terraform-visual/runs/4342839613) you can see a build with DEBUG mode enabled.

**Comment by Wiston999** [comment]
Hi @afinetooth,
did you have the chance to check build logs?

**Comment by afinetooth** [comment]
Hi @Wiston999. So, yes, while your (apparently valid) LCOV coverage report starts [here](https://github.com/Wiston999/terraform-visual/runs/4342839613#step:7:10): 

![Screen Shot 2021-12-03 at 4 08 23 PM](https://user-images.githubusercontent.com/918667/144688187-04031c59-f2ee-444e-a9db-68323768d0f1.png)

The resulting `source_files` collection in the JSON you're submitting to the Coveralls API is empty [here](https://github.com/Wiston999/terraform-visual/runs/4342839613#step:7:986).

Which looks like this:

![Screen Shot 2021-12-03 at 4 04 18 PM](https://user-images.githubusercontent.com/918667/144688069-561828ae-6126-4962-be9b-a163230e260b.png)

That's the reason for 0 files and 0% coverage.

And it indicates the integration had a problem converting the LCOV to JSON.

As I mentioned, the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood. So here is the part of that code that [opens the file (and displays its contents in the debug output)](https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/handleInput.js#L6-L7). And here is the code that [converts the LCOV file to JSON](https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/convertLcovToCoveralls.js#L111-L116). Which is to say, the part that populates the `source_files` array in the JSON you're posting.

Since we know the LCOV file is there, I'm thinking the issue is that the [covertLcovFileObject method](https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/convertLcovToCoveralls.js#L30) isn't finding the individual source files by the paths given in the LCOV file.

I'm going to hand it back to you at this point and ask if you can determine why that might be, since you're more familiar with your setup and the states your CI environment is going through at each step of your workflow.

**Comment by Wiston999** [comment]
Hi @afinetooth ,
I finally found the missing configuration in GH Action.
I had to setup `base-path` variable to the folder containing the `coverage` folder.

Thanks for your help.

**Comment by afinetooth** [comment]
Hi @Wiston999. Ah yes, that makes sense. Glad you got it worked out.
