### ISSUE TITLE
Randomly get 0 of 0 relevant lines covered (NaN%) with no changes from previous build with 94.09%

### ISSUE THREAD

**Issue by mikeebowen** [lemurheavy/coveralls-public#1599]
My test coverage was previously at 94.09% and I haven't removed any tests, but coveralls gives the message: `0 of 0 relevant lines covered (NaN%)` 

The project is a VS Code extension written with TypeScript. This has been happening for sometime now and I can't find why sometimes it works fine and others I get 0%. Here is the [coveralls repo](https://coveralls.io/github/mikeebowen/ooxml-validator-vscode?branch=main).

Let me know if there is more information I can provide.

**Comment by afinetooth** [comment]
Hi @mikeebowen. Sorry for the delay.

I had a look at your repo and it seems you may have worked this out by now, since your last three (3) builds are all at 94%. I don't see anything obvious in your build logs between the last two builds that went from 94% to 0%, but that's not saying much since they are not in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v).

To get a better idea what might be causing this, it would help if you ran your next few builds in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v). The way to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) with the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) is to add the following CI environment variable to your GHA config yaml so it's available to the coveralls step:
`NODE_COVERALLS_DEBUG=1`

(The "NODE_" part is there because the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood.)

In general, going from _some coverage_ to _no coverage_ across two builds indicates the integration wasn't able to find your coverage report (LCOV) the second time around. With [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) enabled, we'll be able to see the LCOV you're using and the JSON you're sending to the Coveralls API in each of your new build logs.

One thing I did notice about your repo that looked unusual is that you have three (3) distinct jobs, each building on a different OS, generating a separate coverage report, and sending that coverage report to Coveralls. However, your builds are not declared [parallel builds](https://docs.coveralls.io/parallel-build-webhook), and therefore, each is job is replacing the other in the build, such that the only one remaining is your third job, which you can see displayed in the JOBS section as job "**.3**":

![Screen Shot 2021-12-06 at 1 13 53 PM](https://user-images.githubusercontent.com/918667/144923548-6925ef90-0df1-4703-8e06-07edf74943fd.png)

I'm thinking this might be the root of your issue. Particularly if those jobs are firing in random order and _one_ of them is generating a 0.0% coverage report.

To configure your workflow for parallel builds, follow the [Complete Parallel Job Example](https://github.com/marketplace/actions/coveralls-github-action#complete-parallel-job-example) from the [Coveralls Github Action README](https://github.com/marketplace/actions/coveralls-github-action).

**Comment by mikeebowen** [comment]
Hi @afinetooth , Thanks for the help. I added verbose logging and used the links you provided to set up the builds as parallel builds, like you recommended, and my first push worked with the new configuration. I will leave the verbose logging in case there is another issue in the future, but it appears to be fixed. Thanks again!

**Comment by afinetooth** [comment]
Hi @mikeebowen. Great! Glad to hear it. Re-post here if you have any further trouble with your parallel build(s).
