### ISSUE TITLE
Moving API-based calls from Travis to Github Actions

### ISSUE THREAD

**Issue by jgebal** [lemurheavy/coveralls-public#1602]
I'm in process of moving our project from Travis CI to Github actions.

Our project is a unit testing framework for Oracle PL/SQL & SQL languages.
The problem I'm facing is that we currently do not have a way to generate LCOV data and with Travis we were relying on API to upload the JSON coverage file to Coveralls.

I cannot find a way to successfully upload to Coverals from Github Actions as the Action available expects LCOV file and it fails when uploading JSON ([see here](https://github.com/utPLSQL/utPLSQL/runs/4400986476?check_suite_focus=true#step:17:16025))

The API call fails with a [different error](https://github.com/utPLSQL/utPLSQL/runs/4400986476?check_suite_focus=true#step:16:67)
{"message":"Couldn't find a repository matching this job.","error":true}

The code responsible for uploading the files can be found [here](https://github.com/utPLSQL/utPLSQL/commit/c4879d467ead6f84b2a4c949ebc280da55ce9c16#diff-cd48710b0e5e848164ad306a00d56b4600b86347780134a8d8339ac03f49512d)

Any help will be greatly appreciated.

**Comment by afinetooth** [comment]
Hi @jgebal.

I'm slightly confused about your original setup. If I understand you correctly, I think you're saying that, rather than employing one of the community-created integrations you can find in the left-hand nav of the [coveralls docs site](https://docs.coveralls.io/), you were using [this uploader script](https://github.com/utPLSQL/utPLSQL/blob/develop/.travis/coveralls_uploader.sh), which calls [this JS file](https://github.com/utPLSQL/utPLSQL/blob/develop/.travis/coveralls_uploader.js), that uploads JSON directly to the [Coveralls API](https://docs.coveralls.io/api-reference). Is that right?

If so, and if that was working, then I think this is the problem:

Different from all other integrations, the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) (actually a wrapper around the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration) uses the Github secret token (`${{ secrets.GITHUB_TOKEN }}`) to identify your repo with the Coveralls API, rather than the coveralls repo token (found at the top of your coveralls repo page).

That said, the value that _identifies_ your post as coming via the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) is:
`service_name = "github"`

So you should be good if you change `github-actions` to `github` [here](https://github.com/utPLSQL/utPLSQL/commit/c4879d467ead6f84b2a4c949ebc280da55ce9c16#diff-cd48710b0e5e848164ad306a00d56b4600b86347780134a8d8339ac03f49512dR18). 

Which is to say, that should fix the `Couldn't find a repository matching this job.` error.

On the other hand, you're right that the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) is looking for an LCOV version of your coverage report, which it will pass to the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration to parse and convert into JSON.

So if you're having trouble finding a library to convert your coverage reports to LCOV, and your current script is successfully generating coverage in JSON and posting it to the [Coveralls API](https://docs.coveralls.io/api-reference), then you could simply stop using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) and just use Github Actions for CI without it.

Of course, in that case, you'll probably want to go back to using the coveralls repo token as your identifier, which you can do by making two (2) changes:

1. Add this environment variable to your GHA config yaml so that it's available to your upload step: `COVERALLS_REPO_TOKEN=<your repo token from coveralls repo page>`
2. Change `service_name` back to `github-actions` (as long as it's not `github` the API will look for the repo token instead of the Github secret token as the identifier).

Hope that helps!

**Comment by jgebal** [comment]
Hi @afinetooth 
Than you for your reply.

I'm trying to follow your advice and use existing API solution and explicitly provide the coveralls token via COVERALLS_REPO_TOKEN env variable that we also used with Travis uploads.

The changes I've done are:
- changed `service_name` to `github`
- added env variable `COVERALLS_REPO_TOKEN` with explicit value of repo token from Coveralls repo page.

With this change, the coverage started uploading.
https://coveralls.io/builds/44925473

I need to explore a bit more to see how can I get more data into coverage.
![image](https://user-images.githubusercontent.com/1398171/145647661-1895bbfc-53ed-4f38-87d8-5beb39a1ff26.png)

**Or maybe it would make more sense to actually have LCOV reporting from utPLSQL done?**


Seems like Coveralls API JSON format is very much proprietary while most testing frameworks support LCOV format in one way or another.

That is a good progress anyways. Thank you for your help.

I might need to explore LCOV output format. 
Do you know any good reference for LCOV format description?

**Comment by afinetooth** [comment]
Hi @jgebal, just a super-quick reply here as I noticed this:

>The changes I've done are:
>
> - changed service_name to github
> - added env variable COVERALLS_REPO_TOKEN with explicit value of repo token from Coveralls repo page.

Not sure if you made those changes at the same time, but I just wanted to clarify:

- When `service_name` is `github` the Coveralls API expects `${{ secrets.GITHUB_TOKEN }}` as the repo identifier
- When `service_name` is `github-actions` (or almost anything else) it expects `COVERALLS_REPO_TOKEN` as the identifier

I did not see you report the expected error:

> 422: Couldn't find a repository matching this job

But if you did, that would be why.

**Comment by afinetooth** [comment]
Also, to gain more insight into what final JSON you're sending to the Coveralls API in your POSTs (to https://coveralls.io/api/v1/jobs), you can enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) on your integration and inspect your new CI build logs (which should also contain your LCOV report).

If you're using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), you can enable verbose mode by adding the following environment variable to your GHA config yaml so that it's available to your `coveralls/upload` step:
`NODE_COVERALLS_DEBUG=1`

If you're using another integration (ie. using Github Actions _without_ the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action)) and don't know how to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v), let me know what you're using and we'll find out how to do that (if possible).

**Comment by jgebal** [comment]
I'm still using Plain Coveralls API with JSON upload composed by our own [coveralls_uploader.js](https://github.com/utPLSQL/utPLSQL/blob/feature/github_actions/.travis/coveralls_uploader.js) file.

I see that it is missing the git info in the JSON file.
Those were not needed when uploading from Travis but for GH actions it is done differently.
I looked at how it's done in [node-coveralls](https://github.com/nickmerwin/node-coveralls/blob/master/lib/fetchGitData.js) and I come to the following conclusions.

- We could extend our own  `coveralls_uploader.js` to enrich JSON with GIT data as per [API documentation](https://docs.coveralls.io/api-reference)
- We could try to leverage parts of `node-coveralls` to achieve the same
- We could implement LCOV reporting and use out of the box integrations for GH Actions and other CIs

Given the options at hand, it seems that it will be most valuable for utPLSQL framework users to have LCOV reporting, so not only utPLSQL itself, but also actual users of framework can benefit from easy integration of their project coverage with coveralls

Thanks a lot for coming back to me so quickly and providing valuable information.

I think I know what needs to happen next.

**Comment by afinetooth** [comment]
Thanks for the update, @jgebal. Sounds good. Let us know if you hit any snags.
