### ISSUE TITLE
unknown coverage, but correct % under details

### ISSUE THREAD

**Issue by marabesi** [lemurheavy/coveralls-public#1603]
I have two repos and both of them presents the same error: the badge says unknown but the coverage shows up when going to the details:

First repo:

![image](https://user-images.githubusercontent.com/2129872/145260215-f8901b18-5175-495e-944e-00ad4b6c3cd3.png)
![image](https://user-images.githubusercontent.com/2129872/145260277-2dad45f6-8af7-43a5-8ea2-49613766d649.png)

Second:
![image](https://user-images.githubusercontent.com/2129872/145260353-b12df7af-a759-4f6c-a308-ffb1e78db769.png)
![image](https://user-images.githubusercontent.com/2129872/145260384-1b052d3f-43e0-40c4-a38a-873021275ac8.png)

**Comment by afinetooth** [comment]
Hi @marabesi. The issue with your badge displaying "unknown" is due to the fact that badge coverage is meant to represent coverage for the _default_ branch of your repo. Your "production" or production-ready" code, as it were.

The issue with your repo(s) in that regard is that you don't _have_ any builds on your default branch(es) (**master** in [marabesi/php-import-checker](https://coveralls.io/github/marabesi/php-import-checker), and **main** in [marabesi/json-tool](https://coveralls.io/github/marabesi/json-tool)).

And the reason for _that_ is that we don't _know_ the value for **branch** on any of your builds. 

From your build histories:

**Repo**:
https://coveralls.io/github/marabesi/php-import-checker
Build history:
https://coveralls.io/repos/358173/builds

![screencapture-coveralls-io-repos-358173-builds-2021-12-09-16_00_27](https://user-images.githubusercontent.com/918667/145494700-b06928c3-da49-4c47-b9ca-cdfef3c8ff70.png)

**Repo**:
https://coveralls.io/github/marabesi/json-tool
Build history:
https://coveralls.io/repos/358063/builds

![screencapture-coveralls-io-repos-358063-builds-2021-12-09-16_00_54](https://user-images.githubusercontent.com/918667/145494708-1300a9c8-775c-48e0-8cd0-df3f78994e2b.png)

Per the[ Coveralls API Reference](https://docs.coveralls.io/api-reference), the value you're missing is for the `git[branch]` parameter. Meaning, the `branch` parameter seems to be missing from the `git` hash we're expecting your integration to pass, along with the rest of the commit data, from Github.

We'll need to find out why that is and fix it.

The best way to do that is to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) on your integration and observe your build log, which will contain debug details, including the JSON you're sending in your posts to the Coveralls API.

It appears the way to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) for the [php-coveralls](https://github.com/php-coveralls/php-coveralls) integration (the integration I assume you're using for your PHP project), is to pass the `--verbose` flag as described [here in the README](https://github.com/php-coveralls/php-coveralls#cli-options). 

Please run a another build or two in verbose mode and share your build log if the root cause doesn't become obvious.

**Comment by marabesi** [comment]
hello @afinetooth thanks for the excellent explanation and the details provided. Adding --verbose showed that indeed, the branch is undefined:

![image](https://user-images.githubusercontent.com/2129872/145677554-bbbf041d-0d5c-40aa-8ca8-d9be502bf0eb.png)

https://github.com/marabesi/php-import-checker/runs/4492909795?check_suite_focus=true


passing the env variable COVERALLS_GIT_BRANCH=master did the trick for me:

![image](https://user-images.githubusercontent.com/2129872/145677610-9021dae2-9666-403a-a9ce-229c0230b628.png)

Anyways, it is not clear wahy some repos the default branch works as expected and those two don't.

**Comment by afinetooth** [comment]
Hi @marabesi. Great. Glad to hear it. 

> Anyways, it is not clear why some repos the default branch works as expected and those two don't.

Sometimes your expected branch can appear undefined when your CI is building in [detached HEAD state](https://www.cloudsavvyit.com/14012/how-do-you-fix-a-detached-head-in-a-git-repository/). This happens to users frequently enough without expectation. The solution is often as simple as putting a `git checkout <branch>` somewhere before your coverage upload step.

Passing `COVERALLS_GIT_BRANCH=master` will work fine when you're on master, but could be fragile if you're on another branch like a PR branch. If you encounter a problem with it, look into the detached HEAD scenario and [recovering from it](https://www.cloudbees.com/blog/git-detached-head). 

I've seen a number of problems like this quickly solved by updating your version of https://github.com/actions/checkout too, so always worth trying that.
