### ISSUE TITLE
No status update in Github PR after successful builds

### ISSUE THREAD

**Issue by elParaguayo** [lemurheavy/coveralls-public#1604]
I'm one of the maintainers for [Qtile](https://github.com/qtile/qtile).

We've recently re-added coveralls to the project via Github actions (I believe it was previously via Travis CI).

When pull requests are submitted to github, the test results are successfully pushed to coveralls but I don't see any status messages summarising the coverage change and level. This is similar to #1565 but I have got thresholds set here.

I'd be grateful if someone could explain what I've done wrong here.

Here's a recent PR with no status message: https://github.com/qtile/qtile/pull/3082
And here are the builds from that PR: https://coveralls.io/builds/44892612

**Comment by afinetooth** [comment]
Hi @elParaguayo.

I was able to force-send a PR comment from my admin console, which means that you should be properly set up to receive PR comments, from Coveralls. (I also see you have the [Coveralls bot](https://github.com/coveralls) on the project as collaborator.)

I suspect there was, at least, an issue with the token of your repo owner (the user who added the repo to coveralls.io), so I made you the owner, since I know you're actively accessing the project.

I do see that your last two PR builds did not receive comments. I was able to force-send them as well (same PR).

Can you please run a few more builds and see if comments aren't coming automatically.

If they aren't, please update me here.

**Comment by afinetooth** [comment]
@elParaguayo actually, I just noticed that PR comments was disabled in your settings:
https://coveralls.io/github/qtile/qtile/settings

![Screen Shot 2021-12-21 at 1 02 43 PM](https://user-images.githubusercontent.com/918667/146997306-4dda012e-46c9-42cd-b164-dce9a433ca1f.png)

I left it as-is, but that explains why they weren't coming on their own.

Please just enable that setting and let us know if that doesn't fix it.

**Comment by elParaguayo** [comment]
Thanks for the replies. I don't actually want the PR comments (so having that unchecked is fine) but I do want the status updates to be reported.

For example, on my qtile-extras repo, I get this when PRs are submitted:
![20211221_210520](https://user-images.githubusercontent.com/946265/146997661-b3b2d194-49b5-4140-a695-cc45ede7b595.png)

The bottom two checks are the bits that I expected/hoped to see on PRs on qtile/qtile, but they're not appearing.

**Comment by elParaguayo** [comment]
Closing this as status messages are now appearing on PRs.

Thanks for your help.

Happy holidays!

**Comment by afinetooth** [comment]
@elParaguayo - glad to hear it. Thanks. Same to you!
