### ISSUE TITLE
Coverage down 6% in summary but no change in details

### ISSUE THREAD

**Issue by andydotxyz** [lemurheavy/coveralls-public#1606]
Can you please help me understand, or fix, why my repo is down 6.6% on coverage despite no files having reduced coverage.
Looking at history this seems to have been happening around once a month.

https://coveralls.io/github/fyne-io/fyne

Thanks!

**Comment by afinetooth** [comment]
@andydotxyz technically there was one (1) file with a reduction in coverage, which you can see in the SOURE FILES table, under COVERAGE CHANGED, although that file had a minimal reduction in coverage and it was counterbalanced by nine (9) other files that were added or increased in coverage.

![Screen Shot 2021-12-21 at 1 07 18 PM](https://user-images.githubusercontent.com/918667/146997799-0d70c1d2-15a8-4fab-8639-79bf3cfa10d6.png)

So the issue remains, and it's a head scratcher.

If you want to compare the build with its previous build, you can follow the previous build link and look at them side-by-side:

![Screen Shot 2021-12-21 at 1 08 29 PM](https://user-images.githubusercontent.com/918667/146998011-971e3580-43db-4aa7-a86d-74565b35dee2.png)

That may give you insight on a file-by-file basis.

But the data to look at to determine the source of the aggregate coverage % is in the RUN DETAILS table:

The coverage % should reflect the math:

> **aggregate coverage = lines hit / relevant lines**

So let's try it:

Previous build:
https://coveralls.io/builds/45165830
![Screen Shot 2021-12-21 at 1 12 24 PM](https://user-images.githubusercontent.com/918667/146998340-f8a9ef8a-721d-403b-ba86-7ee8dd9c1f7a.png)

- aggregate coverage = lines hit / relevant lines
- aggregate coverage = 17142 lines hit / 28077 relevant lines
- aggregate coverage = **61.054%**

Current build:
https://coveralls.io/builds/45165901
![Screen Shot 2021-12-21 at 1 12 50 PM](https://user-images.githubusercontent.com/918667/146998379-e1a35c52-77b2-4ee0-a739-3be63bdbf51d.png)

- aggregate coverage = lines hit / relevant lines
- aggregate coverage = 12394 lines hit / 22772 relevant lines
- aggregate coverage = **54.426%**

So according to that formula and the stats we received / merged, those coverage % are correct for each build.

To see if we had a bug while performing the merge, I re-ran the second build:
https://coveralls.io/builds/45165901

And I did get a different result:
![Screen Shot 2021-12-21 at 1 17 48 PM](https://user-images.githubusercontent.com/918667/146998902-48cb4204-2f2c-4daf-a005-e32b7b3a94d5.png)

**61.054%**, which probably makes more sense to you.

I'm not sure why this would have happened, but I suspect one possible issue:
I noticed each of your builds is non-parallel, meaning only has one build, but that each build is suffixed with `.2`. This indicates we are processing at least one previous job, but it is being replaced by the second job because it appears to be identical to the first (same CI build number, etc.).

It's possible we are performing the calculation at a point when the second job is not complete.

Can you speak to whether there's another job you're sending to the coveralls API and why? TIA.

**Comment by andydotxyz** [comment]
Thanks for the analysis of this, I think I follow :)

> Can you speak to whether there's another job you're sending to the coveralls API and why? TIA.

It is supposed to be only running once per commit, but I will go through and see if I can find a reason why that may not be the case.

**Comment by andydotxyz** [comment]
I found that we were accidentally triggering twice with two different Go versions. Perhaps this was causing the issue?

**Comment by afinetooth** [comment]
@andydotxyz that's my guess. 

It sounds like you might _want_ to perform parallel builds, if you wish to test and track coverage against both language versions. That's a common use case for parallel builds.

If that's the case, to do that you'll typically create a matrix build.

Then as far as your coveralls configuration is concerned, you'll change two things:

1. Declare each job in your build as _parallel_ to the [Coveralls API](https://docs.coveralls.io/api-reference) by adding the env var COVERALLS_PARALLEL=true ([per goveralls usage notes](https://github.com/mattn/goveralls#usage))
2. Add a final, post-matrix step to _close_ the build by sending a [parallel builds webhook](https://docs.coveralls.io/parallel-build-webhook) to the [Coveralls API](https://docs.coveralls.io/api-reference).

Here are the steps:

1. Establish a matrix build in your GHA config yaml
2. Send job 1
3. Send job 2-n
4. Send parallel closed webhook

For an example on how to send the parallel "closed" webhook, have a look at [these lines](https://github.com/coverallsapp/coveralls-node-demo/blob/master/.github/workflows/workflow.yml#L29-L37) in the `.github/workflows/workflow.yml` file in this project, which is a demo project showing how to configure a parallel build:
https://github.com/coverallsapp/coveralls-node-demo

(Note that because you're using [goveralls](https://github.com/mattn/goveralls), instead of the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) as that project is, you'll be declaring your jobs parallel in a slightly different manner. For that step, follow the [goveralls usage notes](https://github.com/mattn/goveralls#usage).)

**Comment by andydotxyz** [comment]
I think it is OK to limit it to just 1 run on 1 version.
We have a matrix in already, and I have updated it to ensure only one combination delivers to Coveralls now.
Thanks for the help

**Comment by afinetooth** [comment]
Sounds good. My pleasure.
