### ISSUE TITLE
Github action workflow returns: Upload error: Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by Ismoh** [lemurheavy/coveralls-public#1613]
https://github.com/coverallsapp/github-action/issues/109

**Comment by afinetooth** [comment]
Hi @Ismoh. 

This error occurs when the **repo identifier** in your CI config is missing or incorrect.

Normally, the repo identifier is your **coveralls repo token**, assigned by https://coveralls.io and found on your repo page (or start page) and settings page for your repo at https://coveralls.io.

However, the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) breaks this pattern and uses the repo's **github token**, `${{ secrets.GITHUB_TOKEN }}`, to identify your repo to the Coveralls API.

Sometimes this is missed when users switch an existing project to Github Actions for CI. Sometimes the issue is that customers are using a different integration with Github Actions (instead of using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action)), but are sending the value `github` for the parameter, [`service_name`](https://docs.coveralls.io/api-reference) (described [here](https://docs.coveralls.io/api-reference)), which is reserved by the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action).

I'll need the Coveralls repo URL for your project, and to see your config yaml to best help you resolve the issue.

If that's something you don't wish to make public, please email us at support@coveralls.io and reference this [issue](https://github.com/lemurheavy/coveralls-public/issues/1613).

**Comment by afinetooth** [comment]
@Ismoh whoops, apologies. I see the issue you referenced contains _your_ project details. Looking at it now, please give me a few moments...

**Comment by afinetooth** [comment]
@Ismoh ok, now referring to https://github.com/coverallsapp/github-action/issues/109:

I see you _are_ using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), which is fine. You'll just want to remove the line, `repo_token: ${{ secrets.coveralls_repo_token }}`, from your [config yaml](https://github.com/Ismoh/NoitaMP/blob/master/.github/workflows/ubuntu-latest-lua-unit-testing.yml#L86-L92).

Also, just to maintain sanity, why not change [this line](https://github.com/Ismoh/NoitaMP/blob/master/.github/workflows/ubuntu-latest-lua-unit-testing.yml#L90) to `github-token: ${{ secrets.GITHUB_TOKEN }}` in strict adherence to the [Coveralls Github Action usage instructions](https://github.com/marketplace/actions/coveralls-github-action#usage).

As far as I can tell, from what I see, that should work.

If not, here's how to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) with the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action):

The [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood, so add this environment variable to your config yaml somewhere so it's available to your coveralls step(s):
`NODE_COVERALLS_DEBUG=1`

If you continue having issues, please share your verbose build log.

**Comment by Ismoh** [comment]
@afinetooth I really appreciate your detailed help!
This is awesome! It is working since yesterday, but your explanations and referring to docs is really good, because it's new to me and I didn't understand everything fully!
Now I do!
Thank you very much!

I think there won't be any problem anymore, but if so, I'll would reopen the ticket!

**Comment by afinetooth** [comment]
@Ismoh great! Glad to hear it.

**Comment by Ismoh** [comment]
Just for reference and for future request from other ppl:
https://github.com/moteus/luacov-coveralls/issues/29

**Comment by afinetooth** [comment]
That's great, thank you.
