### ISSUE TITLE
How can I fix path issues? 

### ISSUE THREAD

**Issue by Ismoh** [lemurheavy/coveralls-public#1614]
How can I fix path issues without the webinterface on coveralls.io?
https://coveralls.io/github/Ismoh/NoitaMP

https://coveralls.io/builds/46179227/source?filename=%2Fhome%2Frunner%2Fwork%2FNoitaMP%2FNoitaMP%2F.testing%2Ftests%2Ffiles%2Fscripts%2Futil%2Futil_test.lua

You can see, that I already tried to do some fixing in luacov-config, but looks like I have no idea to get this working:

https://github.com/Ismoh/NoitaMP/blob/8e460231b20bac962552a6fa9de7a3ebcee2adc1/.luacov

**Comment by afinetooth** [comment]
@Ismoh TBH, I'm not sure I understand your particular use case 100%, but I think what you may be looking for is the `base-path` param as described in the [Coveralls Github Actions usage instructions](https://github.com/marketplace/actions/coveralls-github-action#usage).

That is used to correct paths if they diverge between Github and CI.

However, I'm not sure you're having that problem, since I can see other files in your project, like this one:
https://coveralls.io/builds/46179227/source?filename=mods%2Fnoita-mp%2Ffiles%2Flib%2Fexternal%2Fbitser.lua

In fact, I'm seeing most of your _source code_ files return `200` success from the Github API when requested.

If I'm correct about _this_ file:
https://coveralls.io/builds/46179227/source?filename=%2Fhome%2Frunner%2Fwork%2FNoitaMP%2FNoitaMP%2F.testing%2Ftests%2Ffiles%2Fscripts%2Futil%2Futil_test.lua

It's a _test file_. And it's in its own [`.testing/` directory](https://github.com/Ismoh/NoitaMP/tree/master/.testing/), separate from the rest of the source code in your repo.

Typical best practice is to _exclude test files_ from the files processed by your coverage library, so they don't impact the line and hit counts of your source files.

So, if you're just having trouble with your test files, the best solution might be to exclude those. That would mean, first, excluding them from coverage reports by finding out how to tell your coverage library to do that. Then, you won't be sending any test files to coveralls at all, only the source files that are _covered_ by those tests, as this is the common use case.

Hope that helps. let me know if I didn't quite understand your question.

**Comment by Ismoh** [comment]
I thought code coverage is the result of the unit tests.

But, if I understand correctly you mean to exclude the test files itself, although the test are more or less providing the code coverage.

I think I have to set the base-path of the githubs actions runner, which is different to the repo paths. It's like /home/runner/NoitaMP/NoitaMP (or similiar, unable to have a look right now)

In addition to this, there is a slight difference to normal testing and lua coding, because I am using a mod API which usually has a look into a mods directory, which isnt usefull to add to my repo, because it's the "global" / "main" folder for all installed mods.
This is why I added a symlink 'mods' to have kinda similiar behaviour on dev coding and ci testing.

And furthermore I have an ubuntu testing and windows testing, but I currently just do ubuntu stuff regarding to coveralls.io. If this is working, I'll want to add windows. Is there a 'merge' function like codecov provides (well, codecov merging doesnt work, this is why I add coveralls.io)

That's the reason I need to fix pathes somehow.

I'll try base-path and excluding test files.

If I fail, I let you know!

Thanks for your help, I really appreciate it!

**Comment by Ismoh** [comment]
@afinetooth 
I was able to fix the issue by removing the symlink and putting everything into a new directory 'mods'. (this is due to modding api and doesn't have anything to do with coveralls.io)

base-path didn't work, I put it to '' (nothing) on coveralls.io web interface
and in addition to this I change .luacov config to exclude testing files and now it's working!

Thanks a lot!

**Comment by Ismoh** [comment]
Just noticed, that I am not able to expand the "mods/" directory of "TREE" on coveralls.io:

https://coveralls.io/jobs/94019695

Trying to fix it with base-path

EDIT:
base-path didn't help.

This is the result of develop console:
![image](https://user-images.githubusercontent.com/12631485/152702601-d1697a3f-8fce-409a-96f5-6ae0aa6276e9.png)

**Comment by afinetooth** [comment]
Hi, @Ismoh. Glad you got it working. Thanks for the update.

As for the current issue with TREE view not expanding, this is a known issue, but it only affects the job pages for your build, for example:
https://coveralls.io/jobs/94019695

Expanding the TREE nodes still works on the build page itself. For the above job page, this is the related build page:
https://coveralls.io/builds/46269446

![Screen Shot 2022-02-07 at 11 24 34 AM](https://user-images.githubusercontent.com/918667/152857513-aebd68ec-8cbc-43d1-b9d3-ffcb91e2a8bf.png)

Thanks for your patience until we can fix it in the job page.

Let me know if you have any further issues.

**Comment by Ismoh** [comment]
Ah okay. I thought it might be an issue related to my repo.
Nice to know. Then this issue is solved!

Thanks for your help!
