### ISSUE TITLE
Please switch owner from personal to service account

### ISSUE THREAD

**Issue by pdurbin** [lemurheavy/coveralls-public#1634]
Hello! We've been using Coveralls since 2015 and are finally getting around to trying to switch the "owner" (from the Coveralls perspective) from my account (@pdurbin) to a service account (@dataversebot). Are you able to help us with this?

Here's the repo in question: https://coveralls.io/github/IQSS/dataverse

Because we are also no longer seeing "coveralls/coveralls" in our list of checks on pull requests (after messing with GitHub OAuth stuff this week), and the following issue talked about switching owners, I hope I'm on the right track:

- #1591

We'd also like our service account to have access to settings in Coveralls. That's another reason to get the owner switched. My understanding is that only the owner can access these settings.

Obviously, if I can switch the owner myself, I'm happy to! I couldn't find any docs on this and other issues seem to suggest that contacting the Coveralls team here is the best approach. Thanks!!

**Comment by afinetooth** [comment]
Hi @pdurbin. Yes, sorry, right now that's not a feature that's available via the UI. It may be in the future.

I have made your service account (**dataversebot**) the owner of:
https://coveralls.io/github/IQSS/dataverse

I did notice that recent builds failed to send status updates, and this is usually due to the repo owner having an expired (or corrupted) Github API access token (which is set in place during OAuth login).

I don't know what the issue might have been prior, but after switching the owner to **dataversebot**, I was able to force-send a status update from this build:
https://coveralls.io/builds/49031474

Which indicates you're good to go with **dataversebot** as the new owner.

But let me know if you have any issues. And let me know if you need the status updates from any of those previous builds. (You can do that yourself by re-running the build in CI as well.)

**Comment by pdurbin** [comment]
@afinetooth thanks! Yes, from @dataversebot I can now see a "Settings" link and the "coveralls/coveralls" check is back!

![Screen Shot 2022-05-12 at 2 07 56 PM](https://user-images.githubusercontent.com/21006/168142545-3529b96b-23c2-446c-adbe-743bd278e2ab.png)

Much appreciated! I'll go ahead and close this issue. Thanks again!
