### ISSUE TITLE
API for getting a list of all repos per organisation

### ISSUE THREAD

**Issue by ErnestFistozz** [lemurheavy/coveralls-public#1639]
Does Coveralls have an API to get a list of repos in an organisation, Take `apache` for example:
I tried using the following but doesn't return any useful response.

`https://coveralls.io/github/apache?page=1`   with the general form being `https://coveralls.io/github/<org-name>?page=<page-no>`

even `https://coveralls.io/github/apache.json?page=1` does not work. 

NB: I am interested in open source projects/organisation so there is no need for any authentication.

**Comment by ErnestFistozz** [comment]
also tried this endpoint:
`https://coveralls.io/api/repos/github/apache?page=1`. still no success. However, the following endpoint 
`https://coveralls.io/github/apache?page=1` leads to a web-page.

**Comment by afinetooth** [comment]
Hi, @ErnestFistozz.

Unfortunately, we don't have an index route for the /repos endpoint.

You are able to see all of the apache org repos because they are public and the Github access permissions carry over to coveralls.io.

It is true that individual Coveralls repo URLs will take a `.json` extension and provide repo data in JSON format, and, with the addition of a `page=n` URL parameter, include the repos build data, but that pattern does not carry over to the organization level. 

In fact, we don't really have the concept of an _organization_ at coveralls.io, just a _subscription_ that can be associated with a Github org. All the repos that a particular user sees are those they have access to at Github, which is not necessarily all of the repos in the org (except, of course, in the case where all the org's repos are public). Another way of saying this is that there is no "organization" scope at coveralls.io, only a "user" scope.

We have a number of cards in our backlog to supplement the API with a full complement of REST routes for each endpoint. I'm happy to +1 you on those that relate to repos.

**Comment by ErnestFistozz** [comment]
@afinetooth Thanks. I was able to gather the information i needed through a web-scrapping approach. however, it would definitely be have that API. so, please do add it as part of the backlog tickets.

**Comment by afinetooth** [comment]
Hi @ErnestFistozz. Glad you found a solution. I have added your request / use case to the existing card in our backlog. Thank you.
