### ISSUE TITLE
circle-ci + public/open-source repo requires token?

### ISSUE THREAD

**Issue by powersj** [lemurheavy/coveralls-public#1641]
Hi,

I am a maintainer of [telegraf](https://github.com/influxdata/telegraf) and I would really like to use coveralls to report code coverage as a part of our CI and PR process. Per the docs, it sounds like we need to set up the circle-ci environment variable, but that does not work for forks and PRs from our community contributions

What is the process for setting up a coveralls for a public repo?

Thanks!

**Comment by afinetooth** [comment]
Hi @powersj.

I hope I understand your question correctly, but it sounds like you're concerned about the Coveralls **repo token** that identifies your coverage report POSTs to the [Coveralls API](https://docs.coveralls.io/api-reference) as belonging to the correct repo.

BTW, the CI-agnostic environment variable the API will always pick up if sent to it, is:
`COVERALLS_REPO_TOKEN=<token>`

I think you have two options here as far as supporting PRs from forks:

1. You could simply add `COVERALLS_REPO_TOKEN=<token>`, as an env var, to your CircleCI config file (so it's available to all coveralls steps), or you can add it to a `.coveralls.yml` file at the root of your repo, which all coveralls integrations look for as an optional config file. Since your repo is public, the repo token may not be too sensitive. IMHO, there's a low likelihood of a bad actor sending faulty test coverage reports to coveralls.io on your behalf. 

2. You can keep `COVERALLS_REPO_TOKEN=<token>` as a CircleCI secret and, [according to this resource](https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/#:~:text=To%20enable%20CI%20for%20forked,builds%20from%20forked%20pull%20requests%E2%80%9D.), make it available to forked pull requests. Quoted from [that resource](https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/#:~:text=To%20enable%20CI%20for%20forked,builds%20from%20forked%20pull%20requests%E2%80%9D.):

> **Enabling CI for forked pull requests**
> To enable CI for forked pull requests, we go to the settings page for our project within CircleCI and choose **Build Settings > Advanced Settings** and enable the “[Build forked pull requests](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories)” option.
>
> While we’re there, notice the next option, “Pass secrets to builds from forked pull requests”.

**Comment by powersj** [comment]
Hi @afinetooth,

Thanks for the detailed response!

Unfortunately, option 2 is not an option as it seems it shares all secrets for our project, which is not something we want to share. I will talk to our team and security about option 1.

I will go ahead and close this and again thanks for taking the time to respond!

**Comment by afinetooth** [comment]
P.S., @powersj:

In terms of setting up your project at CircleCI, I would recommend utilizing the purpose-built [Coveralls Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls). Just follow the [usage examples in the README](https://circleci.com/developer/orbs/orb/coveralls/coveralls#usage-examples).

The Coveralls Orb uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood, so if you're familiar with that integration, some utilitarian aspects still apply, such as enabling [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) with the env var: `NODE_COVERALLS_DEBUG=1`.

Finally, if you want to see an example of CircleCI setup for a public project, check out this repo:
https://github.com/coverallsapp/coveralls-node-demo

Specifically, check out its [.circleci/config.yml](https://github.com/coverallsapp/coveralls-node-demo/blob/master/.circleci/config.yml).

The actual purpose of that repo is to demonstrate setting up a project with [parallel builds](https://docs.coveralls.io/parallel-build-webhook) at any of the popular CI services (CircleCI, Github Actions, Travis). So if your project is _not_ parallel, you can just extrapolate back to the [non-parallel usage example](https://circleci.com/developer/orbs/orb/coveralls/coveralls#usage-coveralls_simple) from the Coveralls Orb README.

**Comment by afinetooth** [comment]
> Hi @afinetooth,
> 
> Thanks for the detailed response!
> 
> Unfortunately, option 2 is not an option as it seems it shares all secrets for our project, which is not something we want to share. I will talk to our team and security about option 1.
> 
> I will go ahead and close this and again thanks for taking the time to respond!

@powersj that makes sense and I've confronted that limitation at CircleCI, but it's also been a while since I've used CircleCI and I think I've heard that there are some options for limiting the scope of which secrets you're sharing.

Not entirely sure this works as it reads, but from that same [resource I quote above](https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/#:~:text=To%20enable%20CI%20for%20forked,builds%20from%20forked%20pull%20requests%E2%80%9D.), it seems you can set _project-specific_ environment variables, and _context-specific_ environment variables to be shared across projects. I'm not sure if that will give you what you need, though:

> **Adding secrets**
> We make our AWS credentials available to trusted builds by setting them as [project-specific environment variables](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project). Note that it’s also possible to create a [Context](https://circleci.com/docs/2.0/contexts/) that is shared by multiple projects.

If that doesn't work, though, another good solution would be to create a `.coveralls.yml` file in the base directory of your repo and add `COVERALLS_REPO_TOKEN=<token>` there:

```
# .coveralls.yml
COVERALLS_REPO_TOKEN=AbCdE12345...
```
