### ISSUE TITLE
No status check for jobs

### ISSUE THREAD

**Issue by danepowell** [lemurheavy/coveralls-public#1649]
We report coverage to Coveralls on the open-source [Acquia CLI](https://github.com/acquia/cli) project.

Up until a few days ago, Coveralls would report back coverage as a status check to GitHub, such as on this PR: https://github.com/acquia/cli/pull/1075

However, Coveralls jobs no longer report status checks, as in this newer PR: https://github.com/acquia/cli/pull/1079

The [Coveralls jobs](https://coveralls.io/builds/50879415) do still run on PRs, they just aren't reporting a status check to GitHub.

A member of our organization with admin access to this repo left the org this week, it seems likely this is related?

**Comment by afinetooth** [comment]
Hi, @danepowell. Thanks for the details, they help a lot.

Yes, that is the most likely cause. We leverage the Github API token of your repo "owner" (the user who added the repo to coveralls.io) for certain actions, like status updates and some other checks against the repo at Github. So if your current owner left, that could be the cause.

I won't specify your previous owner here, but since I know you are active at coveralls.io and have Admin access to the repo, I transferred ownership from them to you.

Upon doing that and force re-sending the status updates, all is well. I did that on your two most recent builds:
https://coveralls.io/builds/50879415
https://coveralls.io/builds/50877868

If you need me to do that for any other builds, let me know.

If you end up leaving the project or the org, this could happen again, at which point you can just let us know and we'll transfer ownership to someone else.

As a best practice to avoid having to do that, and surprises like this, it's a good idea to use a service account (accessible by multiple people at your org) to add repos to coveralls.io.

If you want to do that retroactively, I'll be happy to bulk transfer all the org's repos to such an account. Just lmk.

**Comment by danepowell** [comment]
Thanks so much for the quick response. I can confirm that Coveralls status checks are working again on acquia/cli.

Thanks for the tip, I am pursuing creating a bot account. To return status checks, does this account just need push access on every Coveralls-integrated repository? I couldn't find documentation on this.

**Comment by afinetooth** [comment]
Technically, as long as the user is a collaborator, it should be fine. Occasionally, I've encountered anecdotal issues if the user does not have Admin access to the repo, so that's ideal, but shouldn't be a requirement.

But yes, should be a member of all Coveralls-integrated repos. (You can try making them an org admin without explicitly adding them to all repos, since AFAIK they would have automatic access, and try that first without going to all the trouble.)

**Comment by danepowell** [comment]
@afinetooth could you please make the @acquia-jenkins user the Coveralls owner for our org?

**Comment by afinetooth** [comment]
Hi, @danepowell.

Happy to do that, however, right now I can't find an account in our system for `acquia-jenkins`. That account will need to login to https://coveralls.io at least once to be in our system.

If you want to let me know when someone has logged into coveralls.io (via Github Oauth) as `acquia-jenkins`, I'll transfer ownership of all repos to that account.

In the meantime, one clarification:
Do you also want to make `acquia-jenkins` the owner of the acquia _subscription_? I can do that as well, but just want to make sure.

Thanks.

BTW, feel free to email your reply to support@coveralls.io. That way I can also return you a log of all previous repo owners prior to the change, if you like.

**Comment by danepowell** [comment]
Thanks, I will move this discussion to email.
