### ISSUE TITLE
coveralls still considering old paths after using `source` setting

### ISSUE THREAD

**Issue by Panaetius** [lemurheavy/coveralls-public#1650]
We gather parallel coveralls data in multiple Github Actions jobs. Since some of the tests shell out to test our CLI application, we have some code in `<job-root>/renku` and some in `<python-dir>/site-packages/renku`.

To consolidate those paths, we add this to pyproject.toml
```
[tool.coverage.paths]
          source = [
              "renku/",
              "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/renku/"
         ]
```

specifically with a step like this in the actions
```
- name: Set coveralls path mapping
        run: |
          echo "

          [tool.coverage.paths]
          source = [
              \"renku/\",
              \"$(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')/renku/\"
          ]" >> pyproject.toml
```

That sort of works. Where coverage before was something like
![image](https://user-images.githubusercontent.com/664486/179179858-07414c69-5c3c-4c05-bdc1-2b85e62c83cc.png)
now it's
![image](https://user-images.githubusercontent.com/664486/179179929-78599478-8cd6-4347-ba5d-7544fb6e2d80.png)

But coveralls still considers those 0.0% and shows the overall coverage as 29% (down from 43% before), even though it should be 86.78%

Is there some way to have coveralls not consider the /opt/... paths and just use the consolidated code?

**Comment by afinetooth** [comment]
Hi, @Panaetius. I'm assuming you resolved the problem since you closed this issue. However, just wanted to let you know that, when you see 0.0% and 0 files for a particular job, that usually indicates a mismatch in source file paths, as declared in the "SF:" lines of your LCOV report, between your CI directory structure and Github directory structure. 

Basically, the integration is looking for your source files at the paths given in your LCOV report, relative to your Github root directory. Check out your report, and, If that's off, that's the reason, and you can correct for it by passing a value for the Coveralls Github Actions's **`base-path`** input option (as described [here](https://github.com/marketplace/actions/coveralls-github-action#inputs)).

**Comment by Panaetius** [comment]
Hi @afinetooth, thank you for your reply.

I haven't solved the issue (I closed the issue in the github-action repo and created this one here, as I thought it's probably not related to the action directly and this repo is a better place for the issue).

just to clarify a bit, essentially what we do in tests is
``` bash
$ pip install . # this installs our python module as an executable `renku` on the system
$ pytest ...
```
and some tests are like
``` python
process = Popen(["renku", "arg")
``` 
calling the command in a subprocess. Because of this, the executed code is the one installed with pip, in the `site-packages` folder, not the source code in the local folder/working directory of the CI action. But the files in `site-packages` and in the repo root have the same content/directory structure, just in two different locations. So to get an accurate coverage report, we needed to let coverage know that these different paths are the same thing, which we tried with the 
```
[tool.coverage.paths]
          source = [
              "renku/",
              "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/renku/"
         ]
```
setting. This should say that the files in `<workdir>/renku` and `/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/renku/` are the same even though they're in different locations. And it looks like coverage correctly applies coverage data gathered from `/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/renku/` to the files in `<workdir>/renku` instead, but now shows 0.0% for files in `/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/renku/` instead of just not showing/ignoring those files.

Maybe the screenshots in the original issue don't show this properly, but you can see it here:
![image](https://user-images.githubusercontent.com/664486/179471070-90486ae7-260e-4dd2-ad8f-6f3ad821d3ba.png)
These are two separate folders on disk that contain the same python files and should be treated as being the same path as far as coverage is concerned.

I tried to set your suggestion in the aggregation action 
```
coveralls-final:
    name: Aggregate coveralls data
    needs:
      [...]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
          base-path: renku/
```
(base-path towards the end) but that doesn't change the result.

For reference, we have some steps that gather coverage data and then the step above that aggregates it. Here's the relevant config (the whole file is rather long):

Setting up the source path mapping:
https://github.com/SwissDataScienceCenter/renku-python/blob/develop/.github/workflows/test_deploy.yml#L454

Uploading the data for one parallel task:
https://github.com/SwissDataScienceCenter/renku-python/blob/develop/.github/workflows/test_deploy.yml#L475

Combining the data of the different steps:
https://github.com/SwissDataScienceCenter/renku-python/blob/develop/.github/workflows/test_deploy.yml#L1056


and coveralls is run with `coverage==6.3.3` and `pytest-cov==3.0.0` and the relevant options are `--cov=renku --cov-report=term-missing` as well as
```
[tool.coverage.run]
omit = ["renku/conftest.py", "renku/data/*"]
```
in `pyproject.toml` (in addition to the setting mentioned above).

Could also be that this is an issue in `coverage`?

**Comment by Panaetius** [comment]
After a lot of trial&error, the issue is that pytests `--cov=<name>` setting overrides the [tool.coverage.paths].source setting, so those paths were still checked, but then in the coveralls finish step, I think they were consolidated, leading to paths still showing up, but with 0.0%.

Changing `--cov=renku` to just `--cov` in the pytest command fixes this.

Thank you for your help!

**Comment by afinetooth** [comment]
Hi, @Panaetius. I'm glad you got it worked out.

Just as some additional input, AKAIF, `base-path` is not a relevant input for the "Coveralls Finished" step, which tells coveralls to close your parallel build. It's really only relevant when passed with one of the "parallel jobs" (or "upload steps"), because it tells the integration how to translate the files it find in your LCOV report. There is no such report (no upload) in the "Coveralls Finished" step.

That should at least rule out the possibility of the paths being consolidated in the finished step, for you.

Another tip here:
If you're trying to understand what's happening with your POSTs to the `/jobs` endpoint of the [Coveralls API](https://docs.coveralls.io/api-reference), invoke [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) in your integration, which, for the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), means adding this CI environment variable to your GHA config YAML so it's available to all coveralls steps:
`NODE_COVERALLS_DEBUG=1`

(The `NODE` part is there because the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood.)

That will add debug output to your CI build logs, and you'll be able to examine both your LCOV content, and the JSON the integration finally POSTs to the API.

When you're seeing `TOTAL FILES: 0` in your build page, look at the JSON to see what the value is for the `source_files` parameter. If it's an empty array (`"source_files": []`), it means the integration can't find the files in your LCOV report for that POST. Then you can go about correcting the `base-path` for that particular job.
