### ISSUE TITLE
Coveralls doesn't pulls source files on master list

### ISSUE THREAD

**Issue by MichaelZaslavsky** [lemurheavy/coveralls-public#1651]
**Goal**
My goal is to display a status badge of coverage in my project's README.md file.

**The Issue**
I have a Github workflow that generates the `coverage.info` report and publishes it at my coveralls.io.
All this works well but the coverage shows 0% due to the source files not being pulled to coveralls for some reason.
Why my source code is not shown in the coveralls list?

**Info**
- Coveralls: https://coveralls.io/github/MichaelZaslavsky/social-event-manager
- GitHub: https://github.com/MichaelZaslavsky/social-event-manager/pull/187
- Workflow run: https://github.com/MichaelZaslavsky/social-event-manager/runs/7371590014?check_suite_focus=true
   Under Run Tests the result is:
   ![image](https://user-images.githubusercontent.com/6709378/179363753-349c5e14-94aa-4776-a9b4-87c9ebad5b4e.png)

**Possible Reason**
I think Coveralls doesn't have the proper access to my repo because it requests access to my organization. I can't grant access to my organization because my organization is not related to this. I have a personal project (for learning purposes) that I use and in that public project, I want to add the Coveralls code coverage status badge.

I read that Coveralls needs a full access to all the public and private repos (https://github.com/lemurheavy/coveralls-public/issues/1645) which might be problem in my case.

If this is the issue, is there anything I can do (except ask my organization to allow the access)?
Maybe upload the source files a different way?
Or let the code coverage read the generated report without the need to have the source code? (As you can see in the image above, the generated report in my workflow already has the coverage percentages per project).

**Comment by afinetooth** [comment]
Hi, @MichaelZaslavsky.

Reasonable theory, however I think we have full access to your repo since it's for your personal "org" (personal account) and you have Admin-level access to the repo.

I think, instead, what's happening is that the integration can't find your source files at Github. That's usually the cause when you know you're exporting full coverage reports that reference many files, but your coveralls report shows TOTAL FILES: 0:

https://coveralls.io/github/MichaelZaslavsky/social-event-manager

<img width="672" alt="Screen Shot 2022-07-18 at 8 37 49 AM" src="https://user-images.githubusercontent.com/918667/179548736-7891fceb-22ac-4342-94e6-52e7e26d8e46.png">

The way to confirm this is to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) on the integration, which, for the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), requires adding the following environment variable&mdash;in your config YAML, or as a secret&mdash;so long as its available to all coveralls-related steps in your config:
`NODE_COVERALLS_DEBUG=1`

(The reason for the `NODE_` part is that the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood.)

If, in the debug output, the JSON you're sending to coveralls.io shows an empty array for the `source_files` parameter. (`source_files: []`), this is the issue.

The root cause is that the paths to the source files in your LCOV file do not match the paths to the same files at Github., relative to your Github root directory.

The fix is to supply a value for the `base-path` input, as described here in the [Coveralls Github README](https://github.com/marketplace/actions/coveralls-github-action#inputs).

Steps for the fix:

1. In your verbose build log, look at the output for your LCOV file (or save it as an artifact and examine it). Note the current base path for source files listed in your `SF: /path/to/filename.ext` entries.
2. Compare this to the paths to the same files at Github, relative to your repo's root directory.
3. Correct for the actual base path to the files by passing the correct base path in the `base-path` input.

Good luck and let us know how it goes.

**Comment by MichaelZaslavsky** [comment]
Hi @afinetooth,

Thank you very much for your super helpful explanation.
Indeed the issue was with empty `source_files` as you assumed. Though the solution was to fix my tests directory path. It was directed to `src/src` instead of `SocialEventManager/src` and caused the issue.
After fixing the directory path to the right one, everything started working as expected! :)

**Comment by afinetooth** [comment]
Hi @MichaelZaslavsky. Great, glad to hear it!
