### ISSUE TITLE
Frequent 504 timeouts for reporting and UI

### ISSUE THREAD

**Issue by danepowell** [lemurheavy/coveralls-public#1652]
In the last week or so, our jobs are frequently failing with 504 Gateway Timeout errors when uploading results to Coveralls. Additionally, I'm getting 504 errors trying to view coveralls.io.

Example failing job: https://github.com/acquia/cli/runs/7435074966?check_suite_focus=true#step:9:138

That is the php-coveralls CLI attempting to upload results from a GitHub Actions run.

Example failure on coveralls.io:

![Screen Shot 2022-07-20 at 11 06 16 AM](https://user-images.githubusercontent.com/1984514/180052099-9de575eb-84d2-45a3-a4ca-9db0afb55ae3.png)

**Comment by afinetooth** [comment]
Hi, @danepowell.

We're aware and actively working on this issue. You can track it and subscribe to updates, here:
https://status.coveralls.io/

We have not identified root cause, but suspect one and are in-progress on an immediate solution, which will take about 10-15 min to implement.  We will hopefully stop seeing intermittent outages at that point.

Thanks for your patience.

**Comment by danepowell** [comment]
Oh great, sorry I missed that. Your Cloudflare 504 page has your Twitter feed embedded (yay! 😁 ) but it wasn't updated with this outage (boo 😢 ). Might be good to embed the status page there as well / instead.

**Comment by afinetooth** [comment]
Agreed. Thank you. :)
