### ISSUE TITLE
PR comments not posted

### ISSUE THREAD

**Issue by qnighy** [lemurheavy/coveralls-public#1663]
In our internal repos (e.g. wantedly/wantedly, wantedly/users-rails), PR comments are not posted despite they're configured to do so.

![image](https://user-images.githubusercontent.com/41755/189261634-e1db5270-6ff7-42e9-a696-fd0451f9fe7f.png)

<details><summary>possibly related issue (1)</summary>

In our internal repo (wantedly/wantedly), Coveralls fails to get commit messages and commit authors:

![image](https://user-images.githubusercontent.com/41755/189261838-a438b35a-8dca-40bb-97fb-7f0d5afc3c61.png)

</details>

<details><summary>possibly related issue (2)</summary>

In our internal repos (e.g. wantedly/wantedly, wantedly/users-rails), Coveralls fails to load file contents from the repository:

![image](https://user-images.githubusercontent.com/41755/189261947-6bfb48de-0bf4-4057-ad42-f93a6e2cda58.png)

</details>

I suspect that there is some problem with GitHub access tokens used in Coveralls for these repos.

**Comment by afinetooth** [comment]
Hi, @qnighy.

We're experiencing an unusually high volume of support requests this week and are working through a backlog, so we'll need to reply in greater depth if necessary as soon as possible.

In the meantime, this is a common issue with several common causes. In your case, given the lack of commit details from Github, the issue is probably that you are building in [detached HEAD state](https://circleci.com/blog/git-detached-head-state/) in CI. What this means is that CI is building from an ephemeral commit, created just for the purpose of the CI build, rather than from the HEAD of the PR branch.

In addition, since the commit does not relate to the commit the PR was initiated for, the ID (aka. commit sha) of the **base build** is also not known. (The **base build** is the build to which your PR build's commit is targeted for a merge, typically a **push** type commit at the HEAD of your default branch.)

Why this affects PR comments:
The content of a PR Comment comes from a comparison between a **pull_request** build and its **base build**, so if coveralls.io cannot get the commit sha of the **base build** from your CI build, it can't find that build and can't derive the content of the PR Comment (and, so, can't / won't send one).

Please see this article from the CircleCI Blog on how to recover from detached HEAD state:
https://circleci.com/blog/git-detached-head-state/

Once you do that, you should start seeing PR comments.

Hope that resolves the issue for you. If not, let us know here.

**Comment by qnighy** [comment]
I have investigated the CI process and yes, we didn't even have the `.git` directory when sending data to Coveralls. Ensuring `.git` directory fixed one of our problems (missing commit messages).

However, the other problems are continuing even though HEAD points to a branch now. Could you investigate the remaining problems?

- That Coveralls doesn't post PR comments, and
- that Coveralls cannot show file contents in its UI

**Comment by afinetooth** [comment]
Hi @qnighy. Can you please share the Coveralls URL(s) for the repo(s) you're having trouble with? If your repo is private or the information is sensitive you can email that to us at support@coveralls.io and mention [this issue](https://github.com/lemurheavy/coveralls-public/issues/1663). Thanks.

**Comment by qnighy** [comment]
@afinetooth Thanks, I sent an email containing the additional information.

**Comment by afinetooth** [comment]
Thanks @qnighy. I got your email to support@coveralls.io. I'll respond there.

**Comment by qnighy** [comment]
Update: we privately discussed the issue through emails, and the conclusion was the following:

## Cause 1: too many parallel coverages

Coveralls' parallel coverages are meant to be used on meaningful separation of tests (like unit tests vs. E2E).

We have been using the feature to send data from each thread of 40 randomly-split parallel tests. Coveralls seemingly had been failing to correctly finish the coverage due to this usage.

We changed the CI configuration to aggregate coverage on our side and then send the aggregated result to Coveralls. It greatly stabilized the test result.

## Cause 2: owner permission

Coveralls internally has the notion of ownership of a repository, which may differ from the one managed by GitHub.

Our repositories' previous owner in Coveralls was no longer an employee of our company. We asked @afinetooth to change the owner so that Coveralls uses the access token with the correct permission.

**Comment by qnighy** [comment]
Thank you for the long investigation and support!
