### ISSUE TITLE
Upload multiple files by command line

### ISSUE THREAD

**Issue by rsharma02-entrata** [lemurheavy/coveralls-public#1666]
Uploading around 20 .xml files but only 3 files uploaded and then it's failing with no any specific error

**Comment by afinetooth** [comment]
@rsharma02-entrata I will need some more information to help:

1. The Coveralls URL for your project
2. Any Build URL(s) showing the issue
3. The name of the Coveralls integration you're using
4. The name of the CI service you're using
5. A CI build log showing the errors, if that's where they appear (rather than surfacing in the coveralls.io app) - Ideally, this would be a verbose build log, given you know how to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) for your Coveralls integration.

I can gather a lot of this info from (1) alone, but it all helps.

If your repo is private or contains any sensitive info, you can send your answer in email to support@coveralls.io and just mention [this issue](https://github.com/lemurheavy/coveralls-public/issues/1666).

**Comment by rsharma02-entrata** [comment]
@afinetooth Sent email to support@coveralls.io.

**Comment by afinetooth** [comment]
Thanks, @rsharma02-entrata. Received and replied.

**Comment by afinetooth** [comment]
@rsharma02-entrata I'm going to close this. Just re-open if you're still having the same issue. Thanks.

**Comment by rsharma02-entrata** [comment]
> @rsharma02-entrata I'm going to close this. Just re-open if you're still having the same issue. Thanks.

Its Resolved thanks @afinetooth
