### ISSUE TITLE
Builds are not processed or shown for multiple days now

### ISSUE THREAD

**Issue by mfittko** [lemurheavy/coveralls-public#1667]
Our GitHub repo did not receive any coverage comments for almost two working days now although there should be a decent amount of builds pending (we got like 100+ builds per day normally). Builds are also not shown on coveralls.io

We wonder why this is not reflected on the status page, as there is clearly a problem on coveralls side. we did not change anything in our CI setup and as you can see from the second link, the builds are successfully created at your end, they just don't seem to be processed any further.

https://coveralls.io/github/sofatutor/sofatutor
https://coveralls.io/builds/52463058

**Comment by afinetooth** [comment]
@mfittko we're not aware of any general issue right now.

Sounds like you're reporting two (2) issues (correct me if I'm wrong):

**1) Slow PR comments**:
If there is no associated Build URL for one of these builds where comments took that long to arrive, then the build was probably not processed / saved. But if they did finally arrive, then they were processed, in which case, please share the Build URL(s) for any such builds.

**2) Missing builds**: 
You say:
> there should be a decent amount of builds pending (we got like 100+ builds per day normally). Builds are also not shown on coveralls.io
As I say above, if the builds have not appeared at coveralls.io, they were probably not processed, unless they are parallel builds in "pending" state. You can verify this by going to your CI build log and visiting the URL in the message with your 200 HTTP status code response from the Coveralls API. If you follow that link and the related Job/Build page reads "Pending" that's why it does not appear in your build history (which only includes closed builds). A "Pending" build usually means coveralls.io did not receive your [parallel builds (close) webhook](https://docs.coveralls.io/parallel-build-webhook).

One clue is that, while most of your builds are non-parallel (have one job), like these:
https://coveralls.io/builds/52414484
https://coveralls.io/builds/52403200
https://coveralls.io/builds/52415107

![Screen Shot 2022-09-14 at 11 15 06 AM](https://user-images.githubusercontent.com/918667/190231300-9b6b2ecf-7328-4bd5-a53a-6655aa4937b4.png)

This most recent build has four (4) jobs, making the build parallel:
https://coveralls.io/builds/52463058

![Screen Shot 2022-09-14 at 11 15 22 AM](https://user-images.githubusercontent.com/918667/190231343-b650dacc-82ff-43ba-b771-3f60c1a6ee7a.png)

Seems like your CI config changed between one of your last two builds, potentially to parallel builds without sending the webhook.

I see, in our DB, `57` builds created in the last 24 hours, but none of those were completed. 

Please let me know what you discover on your side.

**Comment by mfittko** [comment]
Hi, thanks for getting back to me. The one build with four jobs had three jobs triggered manually by me during debugging. There are no coverage results shown. Also there are none of these builds listed on the primary page of the repository. I could only access that build page by looking into the api response when pushing the results.

**Comment by mfittko** [comment]
I think it's neither parallel builds nor a performance issue, the build are just not processed and therefore the comments are not posted to GitHub.

**Comment by mfittko** [comment]
I was not aware of any parallel build feature at coveralls. We never had to do anything else than pushing the results. We are merging the results of our parallel CirleCI runs into a single lcov file before pushing them to coveralls.

**Comment by afinetooth** [comment]
Ok, thanks for the update. So you've made no changes to your CI config to enable parallel builds (in terms of what coveralls.io would consider a parallel build---I understand your build may be _parallelized_ at CircleCI).

So the other clue I'm seeing about these `57` builds created in the last 24 hours is that all of them show `0` coverable files in  the coverage report received. 

Example:

```
> Build.find(52443332)
[...]
 coverable_files_count: 0,
[...]
 covered_lines: nil,
 missed_lines: nil,
[...]
```

And the one job associated with the example build also shows no coverage stats received:

```
> Build.find(52443332).jobs.first
[...]
 coverable_files_count: 0,
[...]
 covered_lines: nil,
 missed_lines: nil
[...]
```

So it seems we're receiving an empty coverage report.

Can you please enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) for your integration, which I presume is the [Coveralls Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls), which uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood. In that case, the way to enable verbose mode is to add this environment variable to your CI project (or directly to your `config.yml`) so that it's available to any/all coveralls steps:
`NODE_COVERALLS_DEBUG=1`

Then run a new build and, if it results in the same issue, please send me the ([verbose](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v)) CI build log so we can examine the debug info there together. We can at least verify whether you're sending any coverage stats in your attached coverage report.

Again, if sensitive, you can email support@coveralls.io and reference [this issue](https://github.com/lemurheavy/coveralls-public/issues/1667).

**Comment by mfittko** [comment]
Thanks for getting back to me again. I already wrote to support yesterday and did not hear back. Builds are still stuck and we're starting to get kinda nervous.

I just re-ran the last successful [coveralls build on master](https://coveralls.io/builds/52387972) via CircleCI and it [again is not showing any results](https://coveralls.io/builds/52479710). Dont get confused by the two jobs, I just again triggered a second one manually here.

I checked the generated coverage artifacts in the build of the re-run and they are identical!

Simplecov html results of the re-run also show the coverage (93.52%), too. Your theory that the transmitted coverage files are not containing the coverage just cannot be true @afinetooth 

I checked the node libraries we are using for the coverage processing and there was no major version change or anything and their GitHub pages also don't show any issues, so it also cannot be an accidental (broken) upgrade on our end.

```
{
  "dependencies": {
    "coveralls": "^3.1.1",
    "lcov-result-merger": "^3.3.0",
    "nyc": "^15.1.0"
  }
}
```

**Comment by mfittko** [comment]
In order to prove my assumption that the error lies on your end, I now added codecov integration in our CI and voila, it's processing the exact same lcov result file, which I upload as follows:
```
cat coverage/lcov.txt | yarn codecov --pipe --disable=gcov
yarn coveralls -v < coverage/lcov.txt || echo 'Failed to upload coverage results!'
```
![codecov-success](https://user-images.githubusercontent.com/326798/190275746-59335aab-2a81-43c4-84e9-e3545ae4a05c.png)

Coveralls remains broken though:
![coveralls-fail](https://user-images.githubusercontent.com/326798/190275750-0e833cb6-2e8a-48ac-9fef-5fd177e093a5.png)

**Comment by mjchang** [comment]
I am seeing this issue as well. This only appears to be happening for select repos in my org though. This is a screenshot of the coveralls run for the latest master run. This run occurred at about Sep 15th 1am GMT.
<img width="1388" alt="Screen Shot 2022-09-14 at 9 23 04 PM" src="https://user-images.githubusercontent.com/6496667/190313944-611db828-7e7b-488e-b880-4d78a42a1909.png">

And here's a screenshot of the latest build in coveralls which is almost 2 days ago 
<img width="1388" alt="Screen Shot 2022-09-14 at 9 23 07 PM" src="https://user-images.githubusercontent.com/6496667/190313953-3d0004e0-ff06-4e12-a28e-11729d29b741.png">

**Comment by mfittko** [comment]
Any updates? What else can I try @afinetooth ?

**Comment by mjchang** [comment]
Update - my builds seem to be coming in again. Not sure if it will backfill.

<img width="1388" alt="Screen Shot 2022-09-16 at 12 47 37 PM" src="https://user-images.githubusercontent.com/6496667/190718756-35d2bf44-432b-441a-adeb-045f7c23d292.png">

**Comment by mjchang** [comment]
Everything seems to be back to normal for me. Seeing latest builds on coveralls app and seeing the coverage comments on PRs ✅

**Comment by mfittko** [comment]
I can confirm that everything is back to normal now for any new builds although builds in that timeframe could not be recovered.
