### ISSUE TITLE
layout of UI

### ISSUE THREAD

**Issue by sdarwin** [lemurheavy/coveralls-public#1669]
Hi,

As someone who has only be using coveralls.io for a short time so far, and not really being an expert, here is feedback about the UI.

When looking at a list of builds, or a list of jobs, you expect the emphasis to be on the most recent jobs. And then to progressively go back to the older ones in a logical order.     Or maybe, as an alternative to that, showing a list of branches that are covered.

We can use github.com/biojppm/rapidyaml as a random example.

https://coveralls.io/github/biojppm/rapidyaml

On the main page, in the list called "RECENT BUILDS", it shows the second most recent build is 

```
master | 93.32 | Merge pull request #88 from biojppm/update_c4core [chore] update c4core | web-flow | push | 26 Oct 2020 01:30AM UTC | travis-ci 
```

What is "recent" about the year 2020?  (nothing)
What is "recent" about the commit message "Merge pull request #88 from biojppm/update_c4core [chore] update c4core".  (nothing)
Is that the most recent build? (no)       (unless, you might be using the word "build" in an unexpected way to mean "branch". ok.)

Checking the github actions page https://github.com/biojppm/rapidyaml/actions the most recent job was

``` 
{'url': 'https://coveralls.io/jobs/106779483'}
```

Searching the main page https://coveralls.io/github/biojppm/rapidyaml which should show recent builds, there is no link to 106779483. 

Visiting the actual link https://coveralls.io/jobs/106779483 it shows a date in a very prominent place, at the top "REPO ADDED
30 MAR 2018 12:36AM UTC".       Is this info, 2018, important?  Perhaps it only catches my attention, because it superficially appears that old out-of-date timestamps are on all pages.    

On the page, there is a link `Prev Build on master (#233)`.  Ok, this should be the "previous" build, right?  Like the one yesterday. The name is, after all, "Prev Build on Master". I click that, and it goes to https://coveralls.io/builds/39282129  which says "01 May 2021 10:22AM UTC".     In the year 2021.

Was the previous build in May 2021? That is a long time ago.  Checking https://github.com/biojppm/rapidyaml/actions there have been numerous jobs more recent.  Such as  {'message': 'Job ##248.25', 'url': 'https://coveralls.io/jobs/105884423'}  .    So it seems that 2021 is wrong.

Then if you click https://coveralls.io/jobs/105884423 and it says "WE CAN'T FIND THAT PAGE".     which is not uncommon..  Just a dead link.

everywhere I click, it's old timestamps (2018, 2020, 2021) and dead links.

So, that is just an first impression.   It's probably badly informed and incorrect, if I learn more about the UI it will make sense over time.

**Comment by afinetooth** [comment]
Hi @sdarwin. Sorry for the delay in getting back to you on this. There's a lot of good feedback here and, for my part, I have missed the opportunity to trace some of your examples because they relate to job pages that have, apparently, since been deleted. That is my bad, so I apologize for that.

First of all, thanks for this feedback. Even though we sometimes get really slammed here and fail to show it, we really value this sort of input because it's essential when trying to design a solution to a problem, be it a bug or a feature. We're working on a lot of features right now, so understanding how the UI feels for a new user is super helpful.

To address your questions / comments:

### "Recent Builds"

> What is "recent" about the year 2020? (nothing)
> What is "recent" about the commit message "Merge pull request https://github.com/lemurheavy/coveralls-public/issues/88 from biojppm/update_c4core [chore] update c4core". (nothing)
> Is that the most recent build? (no) (unless, you might be using the word "build" in an unexpected way to mean "branch". ok.)

Good point. In your use case, "Recent" is not the best descriptor for this list.

By "RECENT BUILDS" we mean the "most recent" builds Coveralls has received for this repo. They should, therefore, be listed in reverse chronological order.

In your case, it's a little confusing because of the large gap in time represented there. While, according to the list, Oct 2020, is the date of your second-most-recent build, you're right. There's nothing recent about 2020 now.

The typical use case is continuous use, where the last five (5) builds in that RECENT BUILDS section likely shows builds from the last few days, or from the last few hours or even minutes.

I have noted the use of the term "RECENT" and will ask our UI/UX designer to consider better ones.

> Searching the main page https://coveralls.io/github/biojppm/rapidyaml which should show recent builds, there is no link to 106779483.

Yes. Also a good point. This is something I've noted myself. There's a disconnect between receiving a "Job URL" in your CI build log and then going to the web app and not seeing that job (or "Jobs" in general) listed anywhere. 

Even if you follow the link from your CI log, or you paste the URL into your browser window, one may lose the fact that Jobs comprise Builds.

I think we should consider landing the user in a different place when they follow that URL from our API response in the CI build log. Do you have any specific ideas in mind about that?

I know that we are redesigning our Job Pages right now, so the rest of this input is spot on. I have passed it to our UI/UX designer:

> Visiting the actual link https://coveralls.io/jobs/106779483 it shows a date in a very prominent place, at the top "REPO ADDED
> 30 MAR 2018 12:36AM UTC". Is this info, 2018, important? Perhaps it only catches my attention, because it superficially appears that old out-of-date timestamps are on all pages.

Good point. We are reconsidering the most important information to put at the top of a Job page. 

Again, I'm curious if you have any ideas, but I'm more curious if you'd be willing to spend any more time on feedback, such as by taking a usability survey or doing a UX research meeting with our designer. Absolutely not necessary to have this feedback considered, but if you're open to it I'll share your Github handle, and if you'd like to share your email you can email us at support@coveralls.io and reference [this issue](https://github.com/lemurheavy/coveralls-public/issues/1669).

> On the page, there is a link Prev Build on master (#233). Ok, this should be the "previous" build, right? Like the one yesterday. The name is, after all, "Prev Build on Master". I click that, and it goes to https://coveralls.io/builds/39282129 which says "01 May 2021 10:22AM UTC". In the year 2021.

Unfortunately, I have missed the opportunity to trace some of your examples because it looks like the original job has been deleted at https://coveralls.io/jobs/106779483.

The feedback is still useful though and I will share it with our designer.

Please feel free to share further thoughts after using the app, but I sense that, from the state of your project, you haven't continued using coveralls.io and for that I'm sorry. We're taking steps to increase our bandwidth here in support, and I personally will try to do better about identifying UX feedback and routing it to someone working on design here.

**Comment by sdarwin** [comment]
Hi @afinetooth, 
Thanks for the reply. Not sure I have any more feedback for the designers, than just the few points already mentioned. I guess, from my perspective, the clearest presentation is something that is happening in Github Actions, Travis, CircleCI, Drone, which is to display a very very long, scrollable list of jobs. Consider this page:  https://github.com/biojppm/rapidyaml/actions. A long list of jobs. Great. 
On the other hand, coveralls distinguishes between two concepts which are "builds" and "jobs". which is which. On one repo that we have, in build <span>#</span>1 it shows job <span>#</span>1.211. Where are jobs 1.210, 1.209, 1.208, 1.207, 1.206, 1.205 etc??  Only one job is shown.
The most recent "job" ran 21 Nov 2022 06:13PM UTC. Yet it also prominently says on the page, that the build is "COMMITTED 19 SEP 2022 - 14:32".  So, the build is from September. The job is from Nov 21.   The "job" is Nov 21, but the "build" page mentions a very specific old commit message from September.  what is the purpose of the old commit message.  Well, we might have removed coveralls from the github actions script in Sept. so that could explain why the build is frozen in time.  But there have been 211 "jobs" since then, in which case it's not frozen.
