### ISSUE TITLE
No PR comments on private repo

### ISSUE THREAD

**Issue by iyotetsuya** [lemurheavy/coveralls-public#1673]
We set up a new repo and plan to use the PR comment feature, but face a problem which is no pr comments.

Here's what we already check:
- Enable the "LEAVE COMMENTS?" option on the settings page.
- Invite coveralls bot with `write` access permission as a repos's contributor
- [Job created on the dashboard](https://coveralls.io/builds/54221563) with "Pull Request" type

I also find an other issue that mentions it may cause by the owner's permission. 
https://github.com/lemurheavy/coveralls-public/issues/1663#issuecomment-1274073234

Since someone in our company maybe tried to use it before, it may be the root cause in this case. Could you help us find out the problem? 
Let me know if any information need to provide. 🙇

**Comment by afinetooth** [comment]
Hi @iyotetsuya.

The issue in your case is that Coveralls can't find the **base build** for your **PR build**.

The content of a **PR Comment** comes from a comparison of coverage details between a **PR build** and its **base build**, typically a **push** type build on your _default_ branch (**develop** in your case).

Right now, you don't have any builds in Coveralls from your **develop** branch:
https://coveralls.io/repos/387481/builds

![Screen Shot 2022-11-21 at 3 48 13 PM](https://user-images.githubusercontent.com/918667/203180769-989dda29-571a-4240-b17b-4db30ae3bdc1.png)

Once you send coverage to Coveralls from your first **push** build on **develop**, all future PR builds with **develop** as their target should receive PR Comments.

You can probably achieve this by:

- Merging your coveralls setup branch to **develop**
- Configuring your CI service to build **push** builds on develop (if not already)

One clue that this is your issue is any build tables on your build pages that read:
`FIRST BUILD ON ...`

Coveralls tracks changes in coverage between successive builds (commits) in your repo. In other words, every Coveralls build gets compared to its _previous_ build. That said, in the case of **PR builds**, the "previous" build is actually the **base build**, because that's what we're comparing. So when you see "FIRST BUILD ON..." it indicates that Coveralls can't find the build's "previous" build. (Or in your case, the **base build**.)

Let me know if sending coverage reports from **develop** doesn't solve your issue.

**Comment by iyotetsuya** [comment]
@afinetooth 

Thank you for the solution in detail. Since our development policy, I couldn't merge the setup branch to develop at this moment, so I tried two ways that should fit the condition, but still had no luck:

- Merge the setup branch (`feature/test_coverage`) into the local `develop` branch and make a push build via terminal instead of CI
- Make a PR that compares a test branch(`feature/coveralls_showcase`) with the setup branch(`feature/test_coverage`)

Both have base build here: 
- https://coveralls.io/builds/54438598
- https://coveralls.io/builds/54438738

Is there anything I did wrong? 
Thank you again. 🙇

**Comment by afinetooth** [comment]
Hi @iyotetsuya.

Regarding the workarounds to complete your POC, they're ingenious:

## Scenario 1

> - Merge the setup branch (`feature/test_coverage`) into the local `develop` branch and make a push build via terminal instead of CI

Yes, I see the build that was created here:
https://coveralls.io/builds/54438598

![Screen Shot 2022-11-22 at 2 30 03 PM](https://user-images.githubusercontent.com/918667/203434487-cb63663b-c07e-4ea7-81d0-142073bdd7f3.png)

_Just FYI, that build was given the build number `#1` because the context of your CI service (and its numbering system) is missing. So no build number was sent from your Terminal push, and, when that happens, Coveralls assigns a sequential integer as the build number:_

![Screen Shot 2022-11-22 at 2 29 33 PM](https://user-images.githubusercontent.com/918667/203434411-67390653-2deb-4a8d-a31b-db143c6a8216.png)

Unfortunately, PR Comments don't work for the same reason as before: Coveralls can't find you **PR build**'s **base build**. 

I'm not 100% sure, but I think that's because the commit for _your_ build only existed in your local dev environment (presumably as the `HEAD` commit of your local `develop` branch) and never existed at Github because you never pushed it to your remote.

When I query to find the Pull Request information Coveralls received for this **pull_request** build:
https://coveralls.io/builds/54438737

It reads:

```
{:title=>"[マージ不要] Coveralls PRテスト用", :head=>{:sha=>"212922c468e75b074dbf71edf1892046dc40cb74", :label=>"fastmedia:feature/coveralls_showcase", :ref=>"feature/coveralls_showcase"}, :base=>{:sha=>"7989ad3a39b4edf15dc41cf5124106f237e64b67", :label=>"fastmedia:develop", :ref=>"develop"}}
```

Note that the _**PR**_'s commit sha is:
`212922c468e75b074dbf71edf1892046dc40cb74`

And the sha of its _**base commit**_ is:
`7989ad3a39b4edf15dc41cf5124106f237e64b67`

So Coveralls is looking for a **base build** at coveralls.io with a **commit sha** of: 
`7989ad3a39b4edf15dc41cf5124106f237e64b67`

But it's not finding it.

Here is the **commit sha** of _your_ build, BTW, [Build `#1`](https://coveralls.io/builds/54438598), pushed from Terminal:
`b69e5d75bb7e5234dd549bee8de19e4e9ab56827`

Again, I'm pretty sure the reason we couldn't find a build for _that_ commit is because it only existed in your local environment, and, when you created a PR at your remote origin with `develop` as the target, your CI service built a PR targeting the `HEAD` commit of the _remote_ `develop` branch.

Yes, this does mean that Coveralls uses **commit sha** to find **base builds**. That's done so that Coveralls always represents the reality at your repo host (ie. Github).

I added your use case to a discussion card in our backlog about using additional means to identify a PR build's base build; but, as it stands, that's how Coveralls works.

---

## Scenario 2

> - Make a PR that compares a test branch(`feature/coveralls_showcase`) with the setup branch(`feature/test_coverage`)

Also ingenious.

So you've created this **push** type build (from CI this time) to be your new base build:
https://coveralls.io/builds/54438738

And created a couple of PRs with that build as target:
https://coveralls.io/builds/54439154
https://coveralls.io/builds/54439387

So why aren't we finding the base build this time?

Let's look at the PR info from Github, for the _first_ build:
https://coveralls.io/builds/54439154

```
{:title=>"[マージ不要] Coveralls PRテスト用", :head=>{:sha=>"212922c468e75b074dbf71edf1892046dc40cb74", :label=>"fastmedia:feature/coveralls_showcase", :ref=>"feature/coveralls_showcase"}, :base=>{:sha=>"7989ad3a39b4edf15dc41cf5124106f237e64b67", :label=>"fastmedia:develop", :ref=>"develop"}}
```

So we're looking for a build with **commit sha** of: `7989ad3a39b4edf15dc41cf5124106f237e64b67`.

And not finding it. Why?

First, to check the **commit sha** of the build you _intended_ as the **base build**:
https://coveralls.io/builds/54438738

It is: `b69e5d75bb7e5234dd549bee8de19e4e9ab56827`.

When I check Coveralls for any builds with the referenced base commit sha, `7989ad3a39b4edf15dc41cf5124106f237e64b67`, I get no results.

Did you push the commit you intended to use for your second base build to your remote origin? 

If not, then the same thing might be happening as happened above.

However, I think it's different because you said:

> Make a PR that compares a test branch(`feature/coveralls_showcase`) with the setup branch(`feature/test_coverage`)

But both of these PR builds:
https://coveralls.io/builds/54439154
https://coveralls.io/builds/54439387

Are targeting the `develop` branch. As you can see from their PR info at Github:

https://coveralls.io/builds/54439154

```
{:title=>"[マージ不要] Coveralls PRテスト用", :head=>{:sha=>"212922c468e75b074dbf71edf1892046dc40cb74", :label=>"fastmedia:feature/coveralls_showcase", :ref=>"feature/coveralls_showcase"}, :base=>{:sha=>"7989ad3a39b4edf15dc41cf5124106f237e64b67", :label=>"fastmedia:develop", :ref=>"develop"}}
```

And:
https://coveralls.io/builds/54439387

```
{:title=>"[マージ不要] Coveralls PRテスト用 into develop", :head=>{:sha=>"212922c468e75b074dbf71edf1892046dc40cb74", :label=>"fastmedia:feature/coveralls_showcase", :ref=>"feature/coveralls_showcase"}, :base=>{:sha=>"7989ad3a39b4edf15dc41cf5124106f237e64b67", :label=>"fastmedia:develop", :ref=>"develop"}}
```

Both reference `fastmedia:develop` as their base branch.

If you pushed your local commit to the `feature/test_coverage` branch on your remote, then created your PR on `feature/coveralls_showcase` with `feature/test_coverage` as the target, then I suspect you'll receive some PR Comments.

**Comment by iyotetsuya** [comment]
Cool, I didn't know the comparison depends on the SHA. I should check the request's response by myself fist.
After pushing a new commit, get the PR comments this time! 
We appreciate your fantastic work, thank you for the support again. 👍
