### ISSUE TITLE
Unexpected commit metadata and no comment in PR

### ISSUE THREAD

**Issue by miquelruiz** [lemurheavy/coveralls-public#1680]
Hello!

I'm having trouble integrating coveralls with our GitHub Actions workflow. We have a private GitHub repo and we're using the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action?version=1.1.3). We also have a coveralls subscription.

The commit message looks like garbled HTML rather than the expected one, and the "committed by" field shows as "GitHub" instead of the original author. This is what it looks like (some of the "html" in the commit message removed):

![coveralls-capture](https://user-images.githubusercontent.com/433636/210772957-ee825181-e4b8-45d6-acf8-2d7b0aae4b7e.png)

Link to that example: https://coveralls.io/builds/55667525
The branch also seems to be wrong, and has the following pattern: refs/pull/\<pull req id\>/merge
This is how it looks in the list of builds (some of the "html" removed):

![coveralls-capture-2](https://user-images.githubusercontent.com/433636/210772568-ffb75f44-c274-46ca-b9f4-473314da425c.png)

Besides that, we're not receiving the usual comments in the PR.

I've found [other similar issues](https://github.com/lemurheavy/coveralls-public/issues/1609) where it's pointed out that coveralls doesn't identify the build as a **pull_request**, but in this particular instance the coveralls UI links just fine to the PR, so I'm not sure this is the same issue.

**Comment by miquelruiz** [comment]
Forgot to mention: We've been integrated with coveralls using Drone CI on that same repo successfully (currently migrating this use case over to GitHub Actions, just in case it's relevant), and coveralls is a contributor to the repo.

**Comment by afinetooth** [comment]
Hi @miquelruiz. Sorry for the delay here. First, as a paying customer, I'd like to encourage you to use support@coveralls.io for support requests like this, just because you'll likely receive a faster turnaround. 

Let me take the three (3) separate issues I see here one-by-one:

1) Garbled HTML in commit message
This one can actually be hard to resolve. I'd like to see if any of the other changes we make after this have a beneficial effect on that issue. If so, then maybe it will handle itself. If not, I suspect it will be the last thing we tackle.

2) Branch value:
I see this is resolved since about Jan 5/6 per [your build history here](https://coveralls.io/repos/229669/builds?page=65). That's good. Let's see if it's related to the third issue.

3) Missing PR Comments:
I see you began receiving PR Comments for [your very next pull_request build on Jan 6](https://coveralls.io/builds/55701744), after the branch names were corrected. That's good and points to that as the cause. 

However, looking at more recent pull_request builds, like [this one](https://coveralls.io/builds/57696575), I see you're _not_ getting PR Comments. But the reason appears to be different. 

In all the cases I see, the reason for that is that Coveralls can't find the base build for your pull_request build. The base build for a pull_request build will typically be a push-type build on your default branch. Typically, a build for the HEAD commit of your default branch at the time your pull_request was created (the PR's target).

The content of a PR Comment is a comparison between the coverage in a pull_request build and it's based build, so when we can't find the base build, we can't generate the comment and, so, won't send one.

Again, in all the cases I can see, the reason Coveralls doesn't appear to be able to find your base builds is because you have almost no push-type builds in your build history. Example:
https://coveralls.io/repos/229669/builds?page=2

![screencapture-coveralls-io-repos-229669-builds-2023-03-10-17_02_02](https://user-images.githubusercontent.com/918667/224455740-77ad33a5-2854-47e8-a90a-2ec9780505b1.png)

^^ Those are all pull_request builds with no push-builds intermixed, and it goes back like that for weeks and weeks until [around Feb 6](https://coveralls.io/repos/229669/builds?page=24), where you have your [last push-type build](https://coveralls.io/builds/56647579). [Your first PR build after that](https://coveralls.io/builds/56648636) received a PR Comment. So, I think the issue is that we just stopped receiving related base builds.

Usually, checking Ci and updating your config to continue building push builds on your default branch will fix the problem.

**Comment by afinetooth** [comment]
Forgot to say:
re: (1) above, commit messages look pretty good all the way up until recently, considering your last two builds as of this comment:

<img width="980" alt="Screenshot 2023-03-10 at 5 07 39 PM" src="https://user-images.githubusercontent.com/918667/224456098-6b6489c9-8800-4769-a44e-cf45a9478fe2.png">

I don't expect the missing base builds to be the cause of this, but I do wonder if this will persist after you rectify that issue.

BTW, you don't _have_ to build push builds. You can choose to just build pull_requests; you just won't receive PR comments without the base builds to compare the delta in coverage with each PR. In that case, you may even want to turn off PR Comments in your [settings](https://coveralls.io/github/xgen-cloud/gosre/settings):

<img width="694" alt="Screenshot 2023-03-10 at 5 10 13 PM" src="https://user-images.githubusercontent.com/918667/224456261-dff546df-5d19-4c50-b55d-cd27ebee5897.png">

**Comment by mrexox** [comment]
I would also recommend upgrading to the latest `coverallsapp/github-action@v2` Github action version. I believe that many issues can disappear then.

**Comment by miquelruiz** [comment]
I'm upgrading to action v2 and changing the config to report push events as well. Will report back when we start seeing results.
Would be nice to have the need of push-type builds documented somewhere, though.

**Comment by miquelruiz** [comment]
This seems to be working after we started sending builds on push events.
