### ISSUE TITLE
PR comments not working

### ISSUE THREAD

**Issue by pedrofs** [lemurheavy/coveralls-public#1685]
This build failed https://coveralls.io/builds/55930380, but no PR comments. Any idea? Thanks.

**Comment by afinetooth** [comment]
Hi @pedrofs. Sorry for the delay.

I don't know if this was the case when you reported, but PR Comments are disabled in that repo's [settings](https://coveralls.io/github/CollateralXP/collateralxp/settings):

<img width="756" alt="Screenshot 2023-03-10 at 3 57 42 PM" src="https://user-images.githubusercontent.com/918667/224450847-9d6b50b1-4048-45c9-bf8e-3c248b91bcae.png">

I looked at one of your most recent PRs:
https://coveralls.io/builds/57747660

Which references a build with commit_sha `b51c6b60a9e878c6d91a56b9be42c9bfef6bcdb1` as its base build, which is here:
https://coveralls.io/builds/57747033

Therefore, you should be able to receive PR Comments, since the most common reason, when set up properly, is that we're missing the base build.

Let us know if enabling the setting doesn't fix it.

**Comment by waterkip** [comment]
I'm experiencing the same problem. Based on issue #1553, I think my permissions are correct. The coverall user has read access to the repo, and our settings[^1] on coverall allow for posting comments. Yet my test PR[^2] does not include comments from coveralls. 

[^1]: https://coveralls.io/github/perl-net-saml2/perl-Net-SAML2/settings
[^2]: https://github.com/perl-net-saml2/perl-Net-SAML2/pull/187

**Comment by afinetooth** [comment]
Hi @waterkip. The issue appears to be that Coveralls can't find the **base builds** for your **pull_request builds**.

Taking [your last **pull_request build**](https://coveralls.io/builds/61216831) as an example:

<img width="941" alt="Screenshot 2023-07-10 at 1 23 19 PM" src="https://github.com/lemurheavy/coveralls-public/assets/918667/a5602a39-d2da-4c1f-8193-05ae97e22915">

When you see "FIRST BUILD" in the header of your Build Info table, it means Coveralls couldn't find the _previous_ build. In the case of a `push` build, the _previous_ build is literally the previous build on the same branch; while, with a `pull_request` build, the "_previous_" build is the PR build's **base build**---the build it's trying to compare coverage to.

**Reason**:
The reason appears to be that we don't have the commit shas for the previous builds---`push` builds on `master`. Example:

```
Build.find(61216947).commit_sha
=> ""
```

This usually means that there's some issue with the configuration of your [Coveralls integration](https://docs.coveralls.io/integrations). 

I can see you're using Github Actions. Are you also using the Coveralls Github Action as your Coveralls integration? If not, what Coveralls integration are you using? One of our community-created [language integrations](https://docs.coveralls.io/integrations#language-integrations)?

If you want to share the relevant portion of your Github Actions workflow file, I can probably help tweak it. If you _are_ using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), you can set the input option, [`debug: true`](https://github.com/marketplace/actions/coveralls-github-action#:~:text=debug,enable%20debug%20logging.) to get a verbose build log, which will show you the exact JSON the Action is trying to the [Coveralls API](https://docs.coveralls.io/api-jobs-endpoint).

Let me know how I can help from here.

**Comment by waterkip** [comment]
Hello,

we use https://metacpan.org/pod/Devel::Cover::Report::Coveralls

This is the relevant snippet of the our github actions config:

```
  if: ${{ matrix.coverage  }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      cpm install -g Devel::Cover::Report::Coveralls
      cover -test -report Coveralls
```

**Comment by afinetooth** [comment]
@waterkip OK, thanks. I know that integration by the alternate name, [coveralls-perl](https://github.com/kan/coveralls-perl).

Given [this source code from coveralls-perl](https://github.com/kan/coveralls-perl/blob/master/lib/Devel/Cover/Report/Coveralls.pm#L128-L149), I believe you may just need to set your **CI service name** to `github-actions`, rather than `github`, which is being set by default, I believe, and which is _reserved_ by the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action).

So try this:

```
  if: ${{ matrix.coverage  }}
    env:
      GITHUB_ACTIONS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      cpm install -g Devel::Cover::Report::Coveralls
      cover -test -report Coveralls
```

Alternatively, it looks like you could also set it like this:

```
  if: ${{ matrix.coverage  }}
    env:
      COVERALLS_PERL_SERVICE_NAME: github-actions
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      cpm install -g Devel::Cover::Report::Coveralls
      cover -test -report Coveralls
```

If that doesn't work, or you end up needing to do something more complicated, I would recommend one of three things next:

1. Adding your [Coveralls Repo Token](https://docs.coveralls.io/api-jobs-endpoint#authentication-coveralls-repo-token) as a [Github Actions secret](https://docs.coveralls.io/ci-services#as-a-secure-environment-variable-recommended) and add it to your config, like this:`COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}`; as done [here](https://github.com/kan/coveralls-perl/blob/master/.github/workflows/master.yml#L42C11-L42C68) in this [coveralls-perl workflow](https://github.com/kan/coveralls-perl/blob/master/.github/workflows/master.yml).
2. Setting your [Coveralls parameters](https://docs.coveralls.io/api-jobs-endpoint#parameters) in a `.coveralls.yml` file as described [here](https://docs.coveralls.io/ci-services#option-2-use-a-coverallsyml-file).
3. Switching to the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action). It supports [these coverage report formats](https://github.com/coverallsapp/coverage-reporter#supported-coverage-report-formats), so it should just be a matter of converting to one of those if your coverage report format is non-standard (`LCOV`, etc.).

**Comment by waterkip** [comment]
Thanks, it was the `COVERALLS_PERL_SERVICE_NAME: github-actions` that did the trick. It added coveralls to the CI.

**Comment by afinetooth** [comment]
@waterkip Great, glad to hear it. Thanks for the update!
