### ISSUE TITLE
Cryptic "Nothing to report, exit code 1" happens, is inconsistent across repositories.

### ISSUE THREAD

**Issue by srivarra** [lemurheavy/coveralls-public#1704]
Hello, a little while ago we bumped the coveralls GitHub Action to `v2` in many of our repositories, and it works well for those ones. One of them however is experiencing the "Nothing to report, exit code 1" error as seen in #1702. I'm not entirely sure how to apply the solution seen in that thread in this instance.

- [Coverage Upload step which is working](https://github.com/angelolab/ark-analysis/actions/runs/4601884850).

- [Coverage Upload step which is _not_ working](https://github.com/angelolab/cell_classification/actions/runs/4633512798).

For both we use a reusable `test` workflow called from the `ci` workflow which gets the coverage and archives it. Then back in the `ci` workflow we download the archive, and upload it coveralls with the `v2` action. Thank you!

**Comment by afinetooth** [comment]
Hi @srivarra. looking into this for you. Someone will get back to you asap.

**Comment by mrexox** [comment]
Hi @srivarra! I've downloaded the `coverage` artifact from your workflow, and here are the first lines:

```
TN:
SF:/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/cell_classification/__init__.py
DA:1,1,1B2M2Y8AsgTpgAmY7PhCfg
LF:0
LH:1
end_of_record
TN:
SF:/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/cell_classification/application.py
DA:1,1,IWWjrCeOtk8NNtrE95++2g
DA:2,1,YyLAJvKtrnVgI03SPkh6bA
```

As you notice the paths are absolute, and they contains python installation path. When you save the artifact and download it on another workflow (another runner) these files are absent. Coverage reporter checks if files exist before reporting their coverage. In your case all files are absent and "Nothing to report" error is returned.

Coverage file from the **ark-analysis**:

```
TN:
SF:src/ark/__init__.py
DA:1,1,1B2M2Y8AsgTpgAmY7PhCfg
LF:0
LH:1
BRF:0
BRH:0
end_of_record
TN:
SF:src/ark/analysis/__init__.py
DA:1,1,1B2M2Y8AsgTpgAmY7PhCfg
LF:0
```

As you see these paths a relative. That's why it is working OK.

If you could change the configuration so that LCOV file contains relative paths - this would help.

**Comment by srivarra** [comment]
@afinetooth @mrexox Thanks! This helped me realize that I never removed  the `.coveragerc` file causing a conflict with the `[tool.coverage]` section in the `pyproject.toml` file. Deleting that `.coveragerc` solved my issue!

**Comment by afinetooth** [comment]
@srivarra Excellent. Glad to hear it. 

Thanks, @mrexox!

Closing this. Just re-open if you need anything else.
