### ISSUE TITLE
Inconsistent status update type

### ISSUE THREAD

**Issue by shark0der** [lemurheavy/coveralls-public#1712]
We've been using Coveralls with CircleCI for a long time already but lately we've noticed that sometimes we'd get a status update named `coverage/coveralls (push)` but we'd previously only have `coverage/coveralls` instead. As far as we know nothing has changed on our CI scripts and the "push" status update only shows up sometimes. We've configured our repo to depend on the checks (including the `coverage/coveralls`) to be able to merge the PRs so this is rather annoying.

The repository is open-source: https://github.com/NexusMutual/smart-contracts

Right now I'm working on migrating from CircleCI to GitHub Actions and so far I've only seen the push one. I would appreciate if you have any hints on how to make this behavior consistent! Migration WIP PR: https://github.com/NexusMutual/smart-contracts/pull/869

We want to have this checks running on every PR because we have protected branches but we also want them to run on the parent branch after the merge has happened.

To view the status checks click "View details" at the bottom of the page of the PRs.

**PRs with `coverage/coveralls` status:** 
- https://github.com/NexusMutual/smart-contracts/pull/826
- https://github.com/NexusMutual/smart-contracts/pull/828

![image](https://github.com/lemurheavy/coveralls-public/assets/528959/f6e322a4-bc18-4f9c-98bc-12d6f9ba4843)

**PRs with `coverage/coveralls (push)` status:**
- https://github.com/NexusMutual/smart-contracts/pull/862
- https://github.com/NexusMutual/smart-contracts/pull/857

![image](https://github.com/lemurheavy/coveralls-public/assets/528959/a1d080fd-a1f4-4860-b002-e90462e7ff51)

**Comment by mkushner** [comment]
thx for the report @shark0der , we're investigating the issue.

**Comment by afinetooth** [comment]
Hi @shark0der. Yes, we made a change somewhat recently because we were seeing race conditions between status updates to PR's when users sent coverage reports for both `push` commits and `pull_request` commits on PR branches. Whichever status update arrived last for the PR (the last `push` commit, or the new `pull_request` commit), would replace the other and become the only coverage status on the PR, and the information in the status/check would be different depending on which made it.

So, now, whenever we see a `push` commit related to a PR we send it with the type declared (`coverage/coveralls (push)`), which leaves the `pull_request` status in place (does not replace it).

That said, I think we may have more work to do here to clarify this pattern and make it consistent. My feeling is that we should probably include type on all status updates, which would allow users to reliably build branch protection rules around our different types of checks.

@mrexox  WDYT?

**Comment by mrexox** [comment]
We got this change on April, 24th, and for the further builds the status name should be consistent - `coverage/coveralls (push)`.

Yes, there were issues with CI triggered for both `push` and `pull_request` events, they had the same status name, so the resulting PR status was unpredictable (`push` and `pull_request` coverages have different base for comparison).

@shark0der, I think in your case you can configure the check with name `coverage/coveralls (push)` since you use `push` event in Github Actions. If you change the event to `pull_request`, the check name will be `coverage/coveralls`, as before.

@afinetooth, I agree, for consistency we should probably add `(pull_request)` to the status name built for pull requests.

**Comment by shark0der** [comment]
Thank you @afinetooth @mrexox! In our scenario it would make sense to have `push` for both pushes and pull requests since technically both push new code to a branch. I'm not sure how would you know that the type `pull_request` should be sent when a workflow triggers it via `pull_request` as opposed to `push`, but maybe I'm missing some context, you should know better.

I'll change the repo settings to use `coverage/coveralls (push)` and will keep an eye on it. I will close this issue for now and will reopen it if there's anything odd or unexpected happening. Thanks again!

**Comment by afinetooth** [comment]
Hi @shark0der, sounds good. 

Here's more background on `push` vs `pull_request` commits in relation to PR's:

- Only `push` commits represent actual additions of code to a repo, on a particular branch. For us, Coveralls' "**push builds**" are built atop `push` commits, and, for the purpose of coverage comparison, these builds are compared to the _previous_ `push` build on the _same_ branch, if any.
- On the other hand, `pull_request` commits represent _proposed_ / _projected_ changes to a repo, when a given branch is merged into another (target) branch. They are built upon an "ephemeral commit" known as a _merge commit_, which is created temporarily in CI to show what would happen _if_ the HEAD of the PR branch was merged into the HEAD of the target branch. Given that, Coveralls' "**pull_request builds**" are different from Coveralls' "**push builds**" because they are built atop these (ephemeral) _merge commits_, and their basis of comparison---_rather than being the _previous_ commit on the same branch_---is their _base commit_, aka. whatever commit they would have been merged into, typically the HEAD of the PRs target branch at the time the PR was created.

That's a lot of info, so I hope it makes sense.

Suffice to say that Coveralls knows what type of commit / build it is receiving from your CI service and creates an appropriately matching build, and sends an appropriately matching status update to Github on behalf of that build.

For this reason, in the future I think it will be most clear if we always send the type with the status, like:

- `coverage/coveralls (push)`
- `coverage/coveralls (pull_request)`

Eventually, we hope to send status updates related to "patches"---just the _new code_ represented by a PR---which would look like this:

- `coverage/coveralls (patch)`

But, for now, you can count on the pattern being:

- `coverage/coveralls (push)`

Whenever we're talking about a `push` commit on a PR branch.

**Comment by shark0der** [comment]
hey @afinetooth, that's actually very useful info, thanks a lot!

> They are built upon an "ephemeral commit" known as a merge commit, which is created temporarily in CI to show what would happen if the HEAD of the PR branch was merged into the HEAD of the target branch

Oh wow, this one is surprising. It makes sense but I didn't expect it to actually perform the merge on the CI itself and for this reason we require the working branch to always be rebased on top of target branch before merging so the tests we run on the PR would match whatever state we'll have after the PR is actually merged. At the same time our tests aren't running on an "ephemeral merge" so whenever the branch is not up to date with its target (base) branch the coverage report will reference different code, which is inconsistent. I suspect using `push` instead of `pull_request` avoids this kind of issue in our case?

**Comment by shark0der** [comment]
bump @afinetooth

**Comment by afinetooth** [comment]
Hi @shark0der. 

TBH, I'm not sure I understand your question, but rebasing your PRs is a common scenario, so let me explain what happens with Coveralls when you're sending coverage reports for _either_ type, or _both_ types, of commit on your PR branches:

1. **Scenario 1: Building `pull_request` commits on PR branches (most common)** - Users configure CI to build `pull_request` commits (only) on their PR branches. In this case, each time you rebase your PR branch, a new `pull_request` build is created in CI, which sends a coverage report to Coveralls, and Coveralls sends a status update of type `coverage/coveralls` (which will later become `coverage/coveralls (pull_request)`) to Github, which compares the PR's latest coverage to its _base commit_ (new HEAD commit of target branch).
2. **Scenario 2: Building both `push` and `pull_request` commits on PR branches (less common)** - Users configure CI to build _both_ `push` commits _and_ `pull_request` commits on PR branches. In this case, when a PR branch is rebased, the following happens: (1) A new `push` commit is built in CI, which sends a coverage report to Coveralls, which sends a status update of type `coverage/coveralls (push)` to Github, comparing the new "**push build**"'s coverage to the _last_ "**push build**" on that PR branch; and then, immediately after that, (2) A _new_ `pull_request` build is generated in CI, which sends a coverage report to Coveralls, which sends a status update of type `coverage/coveralls` (and later, `coverage/coveralls (pull_request)`) to Github, which compares the new "**pull request build**"'s coverage to the coverage of it _base commit_  (new HEAD commit of target branch).

Hope that clarifies the behavior of those two scenarios.

In general, we find **Scenario 1** to be most common and least "noisy."

The only difference from the Coverall standpoint is that, with **Scenario 2**, you're _also_ tracking coverage between individual `push` commits on the same PR branch; which can get noisy.

Re: this:

> [...] our tests aren't running on an "ephemeral merge" so whenever the branch is not up to date with its target (base) branch the coverage report will reference different code, which is inconsistent.

I understand what you mean here, but just to clarify, CI actually _does_ run the same test suite on your `pull_request` builds that it runs on your `push` builds. 

In that regard, you can think of the `pull_request` build as just like a `push` build, but one that will not be committed to your git tree until you decide to merge `push` (HEAD of PR branch) into `push` (HEAD of target branch). 

Or the reverse, which is what you're doing with a _rebase_, in that you are merging from target branch to PR branch, but `push` (HEAD of PR branch) is still applied on _top_ of `push` (HEAD of target branch).

But, if your CI is configured to build `pull_request` commits, upon each rebase, CI and Coveralls take care of updating the "coverage picture" so it represents latest HEAD commits of both the PR branch _and_ the target branch.
