### ISSUE TITLE
Parallel Builds broken - push receives all builds, pull doesn't

### ISSUE THREAD

**Issue by jrfnl** [lemurheavy/coveralls-public#1714]
Okay, so this is a weird one and I have confirmed the behaviour with multiple repos.

Given a (GitHub Actions) workflow which runs both on `push` as well as `pull_requests` events...
... and given that this is exactly the same workflow for both `push` as well as `pull`...
... and given that the workflow runs severals test runs with different configurations...
... and sends the reports with a unique name to Coveralls with the `COVERALLS_PARALLEL: true` flag set...
... and runs `parallel-finished: true` after all test runs have finished...
... and that all builds succeed and the GH Action logs show that all reports have been send to Coveralls and have received a `status: 200 OK`....

I'd expect:
* Both the `push` build and the `pull` Coveralls runs to show they have received all builds and show the same Coverage %.

While in practice:
* The `push` build on Coveralls shows all received builds correctly and show the correct coverage %
* While the `pull` build on Coveralls only shows one received build, which leads to a wildly incorrect coverage %

This worked fine previously, but looks to have been broken sometime in the past 48 hours.

Please let me know any additional information I can provide you.

Example of a repo in which I am seeing this behaviour:
* https://coveralls.io/repos/403794/builds?page=1 (Coveralls Pro Account Customer)

**Comment by afinetooth** [comment]
Hi @jrfnl. Thanks for reporting this. In the last 48-hrs we released functionality that merges jobs with the same `flag_name` (aka. env var `COVERALLS_FLAG_NAME`). I'm not seeing that would be at play given [your workflow](https://github.com/Yoast/wordpress-seo/blob/386718d0cde626a618ff8b98b00b542cb80fc25b/.github/workflows/test.yml#L122-L132), but it is the most conspicuous change in that time frame that would result in a sudden, lower number of jobs.

I see [this is the value you're sending for `COVERALLS_FLAG_NAME`](https://github.com/Yoast/wordpress-seo/blob/386718d0cde626a618ff8b98b00b542cb80fc25b/.github/workflows/test.yml#L278). It has two separate matrix vars in the name so I can't imagine them resulting in a repeated `flag_name`, particularly since we can see how they look in this recent `push` build:
https://coveralls.io/builds/60309664

<img width="983" alt="Screenshot 2023-05-25 at 10 02 16 AM" src="https://github.com/lemurheavy/coveralls-public/assets/918667/47fb0f5c-fe18-433c-86d7-d515507e2358">

Still, I'd like to ask if you see any possibility of that before we move on to another possible root cause.

As I wait for your answer I'll look into the details on our end further.

**Comment by jrfnl** [comment]
@afinetooth Thanks for your quick response. A duplicate name is not possible with the setup in these workflows. It's the same workflow for push and pull and the names are set up to be unique and this has worked like a charm in all previous builds (before the last 48 hours) and still works the same in the `push` builds.

Note: I've also done a test run with another repo in a completely different organisation which had no pushes at all in the last 48 hours and I'm seeing the same pattern - only one build is shown as received for a PR, while four were send: https://coveralls.io/repos/280231/builds

**Comment by afinetooth** [comment]
@jrfnl Got it. Thanks for confirming that.

I can confirm this is a bug. Someone is looking into it right now.

Will update you here (and in our related email thread).

**Comment by jrfnl** [comment]
@afinetooth Thanks for letting me know and for looking into it. I look forward to the fix ;-)

**Comment by afinetooth** [comment]
Hi @jrfnl. We believe this issue has been fixed. 

I have confirmed a successful build on this project:
https://coveralls.io/builds/60350682

But your [other project](https://coveralls.io/github/PHPCSStandards/PHPCSUtils) has no builds for today, so please let us know if it's not fixed after you build your next pull request.

Forgot to mention that you could have tracked / subscribed to the incident here:
https://status.coveralls.io/

The particular incident URL is:
https://status.coveralls.io/incidents/qd47758yl1fh

I will close for now, but please just re-open or comment back and we'll re-open this.

**Comment by jrfnl** [comment]
@afinetooth Thank you so much for getting this fixed quickly!

For the account where the issue was first discovered, the dev team has gone home for a long weekend, so I won't get confirmation from them until Tuesday at the earliest.

I'll keep an eye on the issue in other repos I'm involved with which use Coveralls over the next few days.

I'm going to presume all is fine now, but will let you know if we still see anything untowards.

**Comment by afinetooth** [comment]
@jrfnl Sounds good. Let us know, here or at support@coveralls.io.

**Comment by jrfnl** [comment]
FYI: I've just ran a PR build on one of the other projects on which I was seeing the same issue and all looks good ❤️ : https://coveralls.io/builds/60362716

**Comment by afinetooth** [comment]
@jrfnl Great, glad to hear that.
