### ISSUE TITLE
Coveralls not posting coverage comment

### ISSUE THREAD

**Issue by lordzsolt** [lemurheavy/coveralls-public#1719]
I have read through multiple issues about Coveralls not posting PR comment, but still unable to resolve my issue.

On the Coveralls platform, I see a `?` where the branch name should be, therefore I assume it could not be posting it because it doesn't have a base coverage to compare it against.

<img width="1353" alt="Screenshot 2023-07-05 at 23 33 11" src="https://github.com/lemurheavy/coveralls-public/assets/8976891/f74ffdc2-308c-49f1-a39b-c19d7fd65a4b">

Looking at the CI, I see the `HEAD` is at a SHA that I have confirmed to exist in the repo, so I am a bit lost on what could be wrong.
<img width="424" alt="Screenshot 2023-07-05 at 23 34 32" src="https://github.com/lemurheavy/coveralls-public/assets/8976891/4f9bf500-fc51-42a5-804d-ef6ddde0166a">

Any ideas what I should debug further?

**Comment by afinetooth** [comment]
Hi @lordzsolt. By "coverage comment," do you mean a [PR Comment](https://docs.coveralls.io/app-notifications#pull-request-comments), or a [Status Update](https://docs.coveralls.io/app-notifications#status-updates)?

In this case, the build would not receive a **PR Comment** because it is a build of type `push` rather than `pull_request`. We only send **PR Comments** for `pull_request` builds.

I have looked at what I think is the [build](https://coveralls.io/builds/61135474) you're referencing here and, in addition to no value for branch (which comes from the [`git` hash](https://docs.coveralls.io/api-jobs-endpoint#parameters:~:text=String-,git%0Arequired,Hash,-run_at) we're looking for in the JSON of your incoming `POST` to [the `/jobs` endpoint](https://docs.coveralls.io/api-jobs-endpoint)), there's no value for the build's associated `commit_sha`, which is required by Coveralls to post the status update. (Not to mention, to determine the coverage diff in the message in the first place.)

It looks like your CI setup is not providing these key environment variables to your [Coveralls integration](https://docs.coveralls.io/integrations) (which one are you using, BTW?) If you can share your **CI service**, your **CI config file** and the **CI build log** for [that build](https://coveralls.io/builds/61135474), I can help determine the issue. (If it's sensitive or a private repo, just email us at support@coveralls.io and reference [this issue](https://github.com/lemurheavy/coveralls-public/issues/1719). I will get your message.)

Sometimes, the issue relates to lacking permissions on the part of your repo owner (which is you, if I have the right [repo](https://coveralls.io/github/ricardo-ch/ricardo-ios-app)), but in those cases, usually only _some_ data is missing, as opposed to virtually all the required data from your CI environment and git.

**Comment by lordzsolt** [comment]
HI @afinetooth,

Thank you for the very detailed post. I really appreciate the effort you put in linking everything to the right place.

- By "coverage comment", I meant PR Comment. The Status Update appears correctly.
<img width="337" alt="Screenshot 2023-07-07 at 00 11 37" src="https://github.com/lemurheavy/coveralls-public/assets/8976891/337989e5-a3f2-41c7-8771-cef2eb2c5941">

- I am using CircleCI as the CI Service
- I am using the `slather` integration
- Builds coming from PRs are correctly identified as `pull_request`, I get the nice `Pull #` button that I can click, to lead me to the PR
<img width="103" alt="Screenshot 2023-07-07 at 00 14 52" src="https://github.com/lemurheavy/coveralls-public/assets/8976891/34835a9b-f635-404c-9039-e2046cb7d040">

- However, when I visit the PR, it's missing any comment from Coveralls
- **My assumption was that this is because there's no coverage data from the default `master` branch, which should've been posted from another build** 

-  Builds coming from merge commits are marked as `push`
- The `push` type builds have the correct link to the commit, but they have a `?` as `Branch`.
- I assume this means the `git.head.id` is set in the `/jobs` payload, but somehow `git.branch` is missing?

- I dug through the `slather.rb` file, and it's trying to read `CIRCLE_SHA1` env variable, and sending it in the payload as `id`
- It reads `CIRCLE_BRANCH` env variable, and sends it as `branch`
- Looking through the CI log, and both of these env variables are set

**Comment by lordzsolt** [comment]
I managed to fix my issue! 🥳 

I needed to add `ci_service: circleci` into the `slather.yml` file.

Something which is missing from the [slather documentation](https://github.com/SlatherOrg/slather). 🤦 
(I will make a PR tomorrow updating the documentation)

-----

You nudged me into the direction of looking at the JSON payload sent in the `slather.rb`, and then I noticed it was not finding the CI service, so it was defaulting to `other`, and reading different env variables than it's supposed to.
