### ISSUE TITLE
Documentation is linking to localhost

### ISSUE THREAD

**Issue by backspace** [lemurheavy/coveralls-public#1741]
The three links under “JSON-Format Web Data” are pointing to `localhost:4000` for me:

![Common Issues   Troubleshooting | Coveralls Docs 2023-12-19 15-28-02](https://github.com/lemurheavy/coveralls-public/assets/43280/ec73d5af-19a4-462e-b908-eb5221a1a31d)

Thanks for all the work on this!

**Comment by afinetooth** [comment]
@backspace thanks so much for catching that! We'll update those ASAP. (Will update you here.)

In the meantime, you can find the content for those sub-links on the same page as the parent link, [JSON Format Web Data](https://docs.coveralls.io/api-introduction#json-format-web-data):

They are just links to subsections of that page.

Also, it's not very clear there because we're due for another update: All of that same data is also available via the API now. 

In each case, you simply call the same URL, you just need to also pass your `repo_token`, for example:

```
curl --location 'https://coveralls.io/builds/64337895.json?repo_token=toK5M7Ee5DoXgC4IpmKCTlaaU9KNYRnVL'
```

**Comment by afinetooth** [comment]
@backspace docs changes submitted. They should be up in the next 24-hrs. 

Thanks again!

**Comment by afinetooth** [comment]
I'm going to close this. Feel free to re-open if you find any more. 🙏
