### ISSUE TITLE
Coveralls status stays in pending in one of my repos

### ISSUE THREAD

**Issue by elchininet** [lemurheavy/coveralls-public#1756]
Hi, opening this issue following the recommendation provided [here](https://github.com/lemurheavy/coveralls-public/issues/1754#issuecomment-2045849816).

I have an issue in one of my repositories in which several merge requests are waiting the status to be reported by Coveralls. The Coveralls job ended correctly and sent the report but the report status is never sent back.

Merge requests that are hanging:

* https://github.com/elchininet/postcss-rtlcss/pull/295
* https://github.com/elchininet/postcss-rtlcss/pull/296
* https://github.com/elchininet/postcss-rtlcss/pull/299 (same changes as the first MR but I submitted to see if it made any difference)

This merge request finished successfuly after the second one:

* https://github.com/elchininet/postcss-rtlcss/pull/298

In Coveralls, all these MRs (that I have restarted several times) are reported as pending completion:

https://coveralls.io/github/elchininet/postcss-rtlcss

![image](https://github.com/lemurheavy/coveralls-public/assets/3728220/b5b2d97b-52a7-402f-b05e-31cb636ccecf)

Regards

**Comment by afinetooth** [comment]
Hi @elchininet. Thank you. I'll be responding to your email request but will backfill solutions here for other users.

**Comment by afinetooth** [comment]
@elchininet as I stated in our email thread, our engineering team thinks this error is specific to you right now because we are seeing an error on your PR builds that your PR diffs exceed the allowable size for GitHub requests. I suspect this might be do to a BLOB in your project that is not being excluded from tests? Not sure, but hopefully that will provide some insight for more investigation on your side.

I would love to know when this started occurring for you, either by date or build number so we can look into those specific cases. It does still feel a little too coincidental that it started happening during [last week's incident](https://github.com/lemurheavy/coveralls-public/issues/1754).

**Comment by elchininet** [comment]
Hi @afinetooth,

It seems that the starting of the issue during the last week incident was just a fatal coincidence. I didn't know anout that limitation about allowable size for GitHub requests. If I understand well what the engineers say, I just need to split that pull request into smaller chunks and it should be OK.

I‘ll do a first pull request just taking a small portion of the original one and it it goes well, I will report back so we can surely assess that the problem is indeed that.

Regards

**Comment by elchininet** [comment]
Hi @afinetooth,

Confirmed!

I submit [this one](https://github.com/elchininet/postcss-rtlcss/pull/300) and the coverage was reported back without issues.

I‘ll keep into account that limitation with the size of the Gihub requests to avoid doing pull request with too many changes.

Closing this issue.

Regards
