### ISSUE TITLE
Coverage stays unknown and no branches or committers are shown

### ISSUE THREAD

**Issue by patri9ck** [lemurheavy/coveralls-public#1780]
https://coveralls.io/github/patri9ck/durak

I pushed onto the main branch, coverage is added to Coveralls using Travis CI. Coverage stays unknown, neither the branches or the committer is shown.

**Comment by afinetooth** [comment]
Hi @patri9ck. It looks like you're using a [language integration](https://docs.coveralls.io/integrations#language-integrations), specifically, [sbt-coveralls](https://github.com/scoverage/sbt-coveralls), is that right?

Are you following [these configuration instructions for TravisCI](https://github.com/scoverage/sbt-scoverage?tab=readme-ov-file)?

The first and most likely issue is the value you're passing for `service_name`, which is currently `travis-ci`, which is defunct since the closure of travis.org.

**Possible quick fix**:
Try changing your `service_name` to `travis-com`, either [this way](https://github.com/scoverage/sbt-coveralls?tab=readme-ov-file#using-travis-pro), or by using this [Coveralls Environment Variable](https://docs.coveralls.io/ci-services#the-coveralls_-env-vars-newer-spec):

```
COVERALLS_SERVICE_NAME=travis-com sbt coveralls ...
```

If you're still having trouble after that, let me know here.

**Alternative: Official Integrations**
Another option is to switch to one of our [official integrations](https://docs.coveralls.io/integrations#official-integrations). If you're using Travis CI, then you'll need to use the [Coveralls Universal Coverage Reporter](https://github.com/coverallsapp/coverage-reporter), which is a cross-platform binary that will find your original-format coverage report, convert it to Coveralls-format JSON, and upload it to the Coveralls API.

You install **Coverage Reporter** with a one-liner [like this](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#linux), and then, usage instructions are [here](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#usage):

```
curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
coveralls report --repo-token=rg8ZznwNq05g3HDfknodmueeRciuiiPDE
```

**Coverage Reporter** supports [these original coverage report formats](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#supported-coverage-report-formats), so if you're coverage reports are generated in a different default format, you'll want to convert into one of these. **LCOV** and **Cobertura XML** are two good and ubiquitous formats.

**Comment by patri9ck** [comment]
Hey, thanks for the quick answer! Setting service_name to travis-com fixed it. I will also definitely try out the binary, thank you for pointing that out!

**Comment by afinetooth** [comment]
@patri9ck Great, glad to hear it.

> I will also definitely try out the binary, thank you for pointing that out!

Sounds good. Reach out if you have any questions or issues when you're ready to implement. I'm going to close this issue, so feel free to open a new one.

In the meantime, you can check out this doc for guidance: 
[Coveralls Docs](https://docs.coveralls.io) > [Getting Started](https://docs.coveralls.io/index) > [Integrate Coveralls with your codebase](https://docs.coveralls.io/index#integrate-coveralls-with-your-codebase) > **Steps 2.3 & 3**.
