### ISSUE TITLE
Source not available

### ISSUE THREAD

**Issue by elasticiodev** [lemurheavy/coveralls-public#263]
I just realized that the source code is not available and we can't see the coverage. I'm getting the following message.

> SOURCE NOT AVAILABLE
> Either the source has been removed from GitHub, or the owner of the Coveralls repo needs to re-authorize. Read More .

Unfortunately, resync and refresh of repos doesn't work

**Comment by mohawk2** [comment]
I'm using Coveralls on a Perl library (https://github.com/PDLPorters/pdl). It's showing:

```
The file "lib/PDL/Graphics/PGPLOT/Window.pm" isn't available on GitHub. [etc]
```

This is strictly correct, since the repo (following a valid EUMM layout) locates that file in `Graphics/PGPLOT/Window/Window.pm`. Is there a way to tell Coveralls where to find its files? I'd like to see where it's covered and where it's not.
