### ISSUE TITLE
Add "comment on pull requests" support for codeship.io

### ISSUE THREAD

**Issue by shuber** [lemurheavy/coveralls-public#366]
It's only available for Travis CI currently

**Comment by kphelps** [comment]
+1

**Comment by jwalton** [comment]
+1

**Comment by jwalton** [comment]
I read somewhere that you only support comments on PRs for CI services which give you the PR number.  You don't actually need the PR number, though, because you can look up the PR associated with a branch via the github [list pull requests](https://developer.github.com/v3/pulls/#list-pull-requests) API.  If you're building the foocompany/project repo, and `${CI_BRANCH}` is 'my-pr', you just need to pass up:

    {
        user: 'foocompany', 
        repo: 'project,
        head: 'foocompany:my-pr'
    }

This should give you back a list of PRs for the branch.  This won't help with PRs from third parties, but Codeship doesn't build PRs from third parties, so that's not a big deal.  :P

**Comment by charlietran** [comment]
+1 to this, sorely needed!

**Comment by charlietran** [comment]
FYI, I think this issue can be closed because the fix is on Codeship's side, not Coveralls. I wrote in to their support regarding this issue and they said "we have upgrades to our PR handling planned for later this year", i.e. they're going to start setting the `CI_PULL_REQUEST` env var correctly.

**Comment by rogerkk** [comment]
So is this supposed to work out of the box now? Did you eventually get it running, @charlietran ?
