### ISSUE TITLE
How to make coveralls.io "comment on pull request"

### ISSUE THREAD

**Issue by tunnckoCore** [lemurheavy/coveralls-public#396]
Hi, I surfing around, but cant find how to make this. Some help, please? :)

**Comment by chamnap** [comment]
@nickmerwin, why it doesn't support semaphoreci?

**Comment by nickmerwin** [comment]
@tunnckoCore hey did you ever get this working? If not could you let me know the name of the repo in question and I'll see what's up.

@chamnap it's because Semaphore doesn't provide the PR number in the build environment:
https://semaphoreci.com/docs/available-environment-variables.html

Other CI's like Travis and Circle do so Coveralls knows which PR thread to comment on.

**Comment by tunnckoCore** [comment]
> @tunnckoCore hey did you ever get this working?

mnope, cuz I cant find how, this is the question in this issue.

**Comment by chamnap** [comment]
@nickmerwin, I talked to the guys at semaphore. Now, they provide PR number in the build environment already. Could you make it happen with semaphore?

**Comment by marktheunissen** [comment]
What are the steps for granting access to the @coveralls bot?

**Comment by tunnckoCore** [comment]
@nickmerwin, ping

**Comment by maxrimue** [comment]
Hello @nickmerwin, I'm having the same issue, for me, 'leaving comments' and 'status API' are not working. This applies to my repository <a href="https://github.com/maxrimue/node-autostart">node-autostart</a>. I'm using travis, the coverage reports work, and both options are activated in the repo settings on coveralls.io. Any clue what's the problem here?

**Comment by diraulo** [comment]
Anyone here ever had luck setting this up with semaphore? Or it's still not supported?

**Comment by erasmo07** [comment]
I have the same issue, but on bitbucket, I want to config @coveralls bot comment bitbucket PR, how can I do?

**Comment by osman** [comment]
I have the same issue on github, how do I allow the @coveralls bot to comment on PRs?

**Comment by msolimans** [comment]
@nickmerwin does it work with CircleCI? Is there any special configs needed
