### ISSUE TITLE
Source Not Available, even though relative path names

### ISSUE THREAD

**Issue by cmouse** [lemurheavy/coveralls-public#442]
Hi!

I have build https://coveralls.io/jobs/4150402 with files that have relative paths exact to my repository, but I am getting Source Not Avaible for my files, such as https://coveralls.io/files/440564923. This would appear to be a bug, since setting build root and repo root to various values won't fix this.

**Comment by nickmerwin** [comment]
Hi @cmouse this is fixed, the issue was that your Coveralls integration library is including a newline character in the commit SHA, which was getting passed along to the Github API when looking for the file; I'm stripping those out now and we're finding and loading the the file properly.

Thank you for the heads up!
