### ISSUE TITLE
coverage is reported for an unrelated repo

### ISSUE THREAD

**Issue by kmike** [lemurheavy/coveralls-public#445]
Hi,

Could you please check https://coveralls.io/r/scrapy/scrapy? There are some builds. But Scrapy doesn't use coveralls, and never used it as far as I know. If you check these builds, they are all for different unrelated repositories. 

Noticed this because of this coveralls comment: https://github.com/scrapy/scrapy/pull/446#issuecomment-72486858 - it is on a very old PR, and all the "Files" in the coveralls UI are unrelated.

**Comment by laedit** [comment]
I think it's due to the release of Coveralls Pro last night which has replaced Coveralls (at least in GitHub authorization).
I have the same issue with my repo: https://coveralls.io/r/Code52/pretzel
It count only 9 builds but the updates show the build 10, 11 and 12 wihtout any data.
The data was submitted with [coveralls.net](https://github.com/jdeering/coveralls.net).

Have the repo token changed?

You can see the coveralls.net log in AppVeyor: https://ci.appveyor.com/project/laedit/pretzel/build/0.2.1.70#L124
