### ISSUE TITLE
Can I just fail builds and have them reported as such if less than 100%?

### ISSUE THREAD

**Issue by sontek** [lemurheavy/coveralls-public#448]

**Comment by nickmerwin** [comment]
@sontek do you mean a PR build's status?

If the last build was already at 100%, any decrease will cause a "failure" status.

**Comment by sontek** [comment]
@nickmerwin My problem is the current builds (on some environments) aren't 100% right now but I don't want them to be considered ok, I want to report they are failing until they get up to 100%

**Comment by nickmerwin** [comment]
@sontek I see, ok I'm going to work on adding finer grain controls over how we update a build's status.

Here's what I'm thinking:

1. Fail when coverage decreases, succeed when it stays the same or increases.
2. Fail when coverage is below X%, succeed otherwise.

Your usage case would be (2) set to 100%.

Does that work for you?

**Comment by velo** [comment]
I would really love to see my build status as failed if coverage decreases!
