### ISSUE TITLE
coveralls.io asks for public & private repo access

### ISSUE THREAD

**Issue by coagulant** [lemurheavy/coveralls-public#450]
After I revoked old token (read-only) and granted commit data access, visiting coveralls.io now asks me to give full access to all of my repos.

Is it really necessary?

**Comment by dannil** [comment]
I tried to login after one of my Travis CI builds finished but same situation for me; it wants full access now, perhaps related?

**Comment by nickmerwin** [comment]
Hi @coagulant and @dannil, we recently updated our OAuth scope to include "commit:status", but didn't touch the "repo" scope. Is there a possibility you guys came to the site using this link?

https://coveralls.io/refresh?private=true

Otherwise I'm not sure why we would have asked to upgrade your OAuth, unless you're part of an organization with private repos already with us -- which I checked, and neither of you are.

Another user reported this and said logging out / logging back in may have fixed it. Could you give that a try?

Closing ticket for now, lets keep convo going though. Thanks!

**Comment by coagulant** [comment]
I managed to work around the problem, visiting public page on coveralls and deleting cookies.
And I wasn't using /refresh url at first, it was /
