### ISSUE TITLE
Error sending to Coveralls.io (RequestEntityTooLarge - Request Entity Too Large

### ISSUE THREAD

**Issue by mmitche** [lemurheavy/coveralls-public#473]
Hey, I'm bringing up uploading coverage data for the dotnet/corefx repo.  I get the above error when uploading about 73 megs of coverage xml data using the coveralls.io tool.  Am I hitting a hard limit?

**Comment by nickmerwin** [comment]
Hi @mmitche yes looks like it. Is your Coveralls integration library posting the entire source code in addition to the coverage data? It would be better to switch to only posting the ```source_digest``` (md5 hash) parameter.

I'm not familiar with the dotnet Coveralls library but will help however I can to get it up to speed on our API best practices.

Otherwise I'll increase our client_max_body_size. Let me know, thank you!
