### ISSUE TITLE
"Couldn't find a repository matching this job" for public fork

### ISSUE THREAD

**Issue by jawshooah** [lemurheavy/coveralls-public#478]
I'm working on a fork of [SublimeLinter3](https://github.com/SublimeLinter/SublimeLinter3) and have enabled my [fork](https://github.com/jawshooah/SublimeLinter3) on coveralls.io. But unless I explicitly specify `repo_token`, I always get the error `"Couldn't find a repository matching this job."` Isn't this only necessary for private repos?

I'm using [python-coveralls](https://github.com/z4r/python-coveralls) with [pytest-cov](https://github.com/schlamar/pytest-cov). Any pointers?

**Comment by feuGeneA** [comment]
I'm experiencing this problem too, in a fork of [0x-monorepo](https://github.com/0xProject/0x-monorepo). 
 And it looks like all of this repo's PR's from pubic forks experience the same error.

Here's what I've tried:
* Enabled [my fork](https://github.com/feuGeneA/0x-monorepo) on coveralls.io
* Configured my own CircleCI jobs (that's what 0x-monorepo uses), and set the COVERALLS_REPO_TOKEN environment variable, and that worked for builds that happen in my own Circle CI instance, but of course it doesn't affect the 0x Circle instance.

([That comment](https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-387698861) mentioned by @paras20xx doesn't seem to apply to me.  I was already committing from my local filesystem, and not using GPG commit verification.)

Is it even possible to configure a repo to allow coveralls to run on PR's that are sourced from public forks?  The way the repo token is handled (either by .coveralls.yml or env var) seems to preclude this from working.

**Comment by feuGeneA** [comment]
I got this use case working for [0x-monorepo](https://github.com/0xProject/0x-monorepo), which uses CircleCI.  Here's how to do it:

After creating your fork, but before creating the branch for your PR, do the following:

1.  Log in to [coveralls.io](https://coveralls.io/), go to Add Repos, and enable your fork. Then go to the settings for that repo, and copy the Repo Token identifier.
2.  Log in to [CircleCI](https://circleci.com/login), go to Add Projects, click the Set Up Project button corresponding to your fork, and then click Start Building. (Assuming the repo you're forking already has a `.circleci/config.yml`, you can ignore all of the instruction/explanation given on the page with the Start Building button.)
3.  In CircleCI, configure your project to add an Environment Variable, with name `COVERALLS_REPO_TOKEN`, and for the value paste in the Repo Token you copied in step 1.

Now, when you push to your branch, CircleCI will automatically run all of the checks in your own instance, and the coverage check will work since it has the proper Repo Token, and the PR will magically refer to your own checks rather than running them in the CircleCI instance belonging to the project you forked.
