### ISSUE TITLE
Specifying wrong service name shows commits from unrelated repos

### ISSUE THREAD

**Issue by bruno-fiksu** [lemurheavy/coveralls-public#482]
I mistakenly specified `service_name: travis-ci` instead of `service_name: travis-pro` in .coveralls.yml.  This resulted in some random other repos' commits showing up on our coveralls dashboard.  Seems like a pretty bad bug potentially leaking proprietary information?

**Comment by nickmerwin** [comment]
Hi @bruno-fiksu sorry that this ticket slipped through the cracks. There's no way for the private info to leak the other direction; it's just pulling in Travis-CI public job info instead of the Pro.

More info here:
https://coveralls.zendesk.com/hc/en-us/articles/201342479-Quick-help-For-Common-Problems

> Travis uses non-unique job id's between its free and pro services, so when Coveralls doesn't know that your service-name is Travis-pro, it looks up the info for those job ids using the free Travis API -- that's why they will show random committers, etc. The opposite cannot happen with the proper credentials, so you don't need to worry that your data is leaking out. Once your ENV var is set to specify travis-pro, the correct info will be pulled from Travis's pro API.
