### ISSUE TITLE
Error while adding a new public repo: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by h2non** [lemurheavy/coveralls-public#496]
I'm getting a 422 Unprocessable Entity when adding a new repository and calling via XHR to `https://coveralls.io/repos.json`

You server is replying with:
```json
{"base":["Couldn't determine GitHub settings."]}
```

It happens with any new repository that I tried to add.
As far I remember, this happens since yesterday.

**Comment by nickmerwin** [comment]
Hi @h2non could you try logging out and logging back in?

Your OAuth token may have rolled.

Thank you!

**Comment by h2non** [comment]
I tried that without any result (also with a private browser session). Any ideas?

**Comment by clphillips** [comment]
I have the same problem. It appears to be triggered by any one or more organizations on your github account that have one or more private repositories. Coveralls wouldn't allow me to add **any** new repos until I clicked **REFRESH PRIVATE REPOS**, then it requested read and **write** access for Coveralls Pro.

As per another issue, I accepted, then removed access for the Coveralls Pro application from my account because why the f would I give coveralls write access? 

While Coveralls now lists my other public repos, it returns the 422 error when attempting to add any public repo. So, back to the drawing board...

**Comment by lmaccherone** [comment]
I am having this same problem. Any update?

**Comment by nickmerwin** [comment]
@clphillips Github doesn't have an OAuth scope to only *read* private repos unfortunately -- only read/write.

@lmaccherone I see added repos for your account, did you resolve the issue?

**Comment by lmaccherone** [comment]
Yep, just now I was able to reset my GitHub connection and get it added. Thanks.

**Comment by clphillips** [comment]
@nickmerwin I'm aware of that. But that's not the problem. Why does coveralls **FORCE** coveralls pro if it detects your account has a private repo (or had, removing orgs with private repos made no difference)?

It is so incredibly annoying that I can't get coveralls to add **PUBLIC** repos simply because I belong to an org that has private repos. What's up with that?

**Comment by nickmerwin** [comment]
@clphillips that's true, we should add the option to upgrade (or not) your OAuth scope when we detect you have access to an org that has a Pro account. Good call, thanks.

@h2non I've just deployed better token reauth handling. Could you try again?

Thanks!

**Comment by clphillips** [comment]
@nickmerwin Whatever you did solve my issue. THANK YOU!
