### ISSUE TITLE
Adding more unit tests causes Coveralls coverage to *decrease* 

### ISSUE THREAD

**Issue by mgoelzer** [lemurheavy/coveralls-public#501]
This is the same as my previous issue #499.  @nickmerwin closed that issue because he said it was the result of Travis having failed on the base build (see his comment at #499).  

However, I don't agree that this is the root cause of the problem.  Here is a new example where the base build *passed* Travis perfectly (https://coveralls.io/builds/2358243), but the same coverage percentage miscalculation is occurring as I described in #499.  (In this case, the only change in the PR is addition of a single line to .travis.yml, yet Coveralls says coverage decreased by 7.72%.  In fact, coverage did not change at all.  Where is the 7.72% figure coming from?)

I'm sorry to be a pest about this, but I don't think the diagnosis in #499 was the real cause.  Can you think of any other ideas I could try to solve this?

**Comment by vieux** [comment]
Also on a related note, look at this PR: https://github.com/docker/swarm/pull/637 it adds a bunch of shell scripts and the coverage went down 7%, this doesn't look right.

**Comment by nickmerwin** [comment]
Hey guys, I'm seeing a large discrepancy in the total number of relevant lines between your branches:

DOCKER / SWARM / 1270
https://coveralls.io/builds/2358243
![image](https://cloud.githubusercontent.com/assets/1129/7206591/d115c032-e4e7-11e4-9ab0-9bd798e4664f.png)

-- compared to --

MGOELZER / SWARM / 10
https://coveralls.io/builds/2358099
![image](https://cloud.githubusercontent.com/assets/1129/7206609/f9230c4c-e4e7-11e4-9aec-95e1ba0476db.png)

And since the build above failed (https://travis-ci.org/mgoelzer/swarm/builds/58847607) it looks like only 6 files were executed:

![image](https://cloud.githubusercontent.com/assets/1129/7206650/57096176-e4e8-11e4-863b-cfd439e029b5.png)

as opposed to 30 in the base branch.

Does that sound like a reasonable explanation?

**Comment by vieux** [comment]
@nickmerwin docker/swarm#637 should be related to any fork, it's just a pr that doesn't touch go and decrease coverage

**Comment by nickmerwin** [comment]
Ok guys thank you for helping sleuth this! I've figured out the issue; the pull request base build was incorrectly being considered @mgoelzer's (https://coveralls.io/builds/2358099) when it should have been this one on the main repo: https://coveralls.io/builds/2358086

I've updated that build and status API / PR comment.

https://github.com/docker/swarm/pull/637

Cheers guys, thanks again!
