### ISSUE TITLE
Coveralls returning 422 no matching repository for pull request travis build

### ISSUE THREAD

**Issue by jlouns** [lemurheavy/coveralls-public#522]
I'm using [gulp-coveralls](https://github.com/markdalgleish/gulp-coveralls) to push coverage data from my travis builds to coveralls. This [build](https://travis-ci.org/jlouns/gulp-requirejs-optimize/builds/62158232) for a pull request to my repository got a 422 response from coveralls when trying to push the coverage data to coveralls. Here's the response:

```
{
  "message":"Couldn't find a repository matching this job.",
  "error":true
}
```

Not sure where to start looking for issues on this one. Thanks!

**Comment by mblayman** [comment]
I am getting the same behavior on Travis with a build that finished around 3:30pm EST 2015/5/14. I can see from closed issues that this was a problem that was appearing last week as well. The problem was resolved in those cases, but it appears to have returned.

Here is my Travis build log for context: https://travis-ci.org/handroll/handroll/jobs/62595820.

**Comment by sivakumar-kailasam** [comment]
Same on mine https://travis-ci.org/sivakumar-kailasam/gradle-npm-wrapper/builds/71675089
