### ISSUE TITLE
No coverage, no data, yet data is shown.

### ISSUE THREAD

**Issue by devinivy** [lemurheavy/coveralls-public#579]
I'm not able to enable coverage for my repo.  Here's a build that shows the relevant files, and when I go to each file's coverage page, it does show how many times each line was hit.  However, coveralls does not display this data in the table, and it doesn't generate a coverage report.

Hovering the coverage icon for each file reveals both "No Data" and "New Coverage".  So I'm a bit confused!

Build: https://coveralls.io/jobs/7245803

**Comment by tweithoener** [comment]
Can confirm the problem.

Or better I could up until a few hours ago. Now the Updates tab just says: "Coveralls doesn't have any delicious details for you yet!" Well, it had them earlier today. But in the state @devinivy described.

**Comment by cashman04** [comment]
Same for me.  First time ever using travis ci today and have been trying to figure out what I'm doing wrong.  It is showing no coverage, and no data from any of my builds.  I'll assume it is due to their infrastructure changes mentioned on their twitter.  

https://coveralls.io/github/cashman04/lita-directions

**Comment by caleb531** [comment]
+1. It seems the same issue is affecting my repos as well. The Updates tab lists a number of builds which all indicate that there is no coverage data. Considering that building and coverage reporting (with Travis and Coveralls) has worked just fine for me in the past, I assumed this might be a Coveralls issue, and I am somewhat relieved that it seems to be just that (as opposed to a fault of my own). ;)

**Comment by cep21** [comment]
http://status.coveralls.io/#week

PROCESSING QUEUE BACKLOG - seems unhealthy

I imagine the best course is to monitor that graph for some kind of update on when we can expect a resolution.

**Comment by mikeryz-rosie** [comment]
Does anyone know the rate at which jobs usually get processed? It's hard to know what the queue size means without that. Has anyone seen data show up after an appreciable delay? I just signed up today and I'm trying to figure out if our data is missing because our configuration is wrong or because of this issue...

**Comment by caleb531** [comment]
@mikeryz-rosie I bet nothing's wrong with your configuration, because nothing is wrong with *my* configuration and the issue is still affecting me. :P

I think right now, all we can really do is wait for the Coveralls team to finish whatever migration and infrastructural changes they are in the process of making, at which point the job queue should decrease in size. In other words, just keep a watchful eye on the [Coveralls Status page](http://status.coveralls.io/).

**Comment by caleb531** [comment]
I believe the issue has been resolved now. The Coveralls Status page indicates that all systems are operational. It also seems that all queued jobs have been processed. :+1:

**Comment by nickmerwin** [comment]
We're all back to date now, thank you everyone for your patience, the great Coveralls Migration of 2015 has finished!

**Comment by devinivy** [comment]
:+1: thanks!

**Comment by gnzlbg** [comment]
I still have this issue.

**Comment by kako-nawao** [comment]
Yep, still happening.

**Comment by pylover** [comment]
Still happening
