### ISSUE TITLE
Coverage dropped to 0% even though it's around 91% ?

### ISSUE THREAD

**Issue by simov** [lemurheavy/coveralls-public#586]
The relevant [TravisCI job](https://travis-ci.org/simov/purest/jobs/72786845) see at the bottom:

```
=============================================================================
Writing coverage object [/home/travis/build/simov/purest/coverage/coverage.json]
Writing coverage reports at [/home/travis/build/simov/purest/coverage]
=============================================================================
=============================== Coverage summary ===============================
Statements   : 91.14% ( 329/361 )
Branches     : 85.14% ( 252/296 )
Functions    : 71.05% ( 54/76 )
Lines        : 91.3% ( 315/345 )
================================================================================
[warn] "2015-07-27T07:17:17.470Z"  'Repo token could not be determined.  Continuing without it.This is necessary for private repos only, so may not be an issue at all.'
Done. Your build exited with 0.
```

And I got this [report in Coveralls](https://coveralls.io/builds/3146030) stating that:

```
COVERAGE DECREASED (-87.6%) TO 0.0%
```

**Comment by gterzian** [comment]
I also can see just now that when a file goes to 100% coverage, the relevant lines drop to 0, resulting in a drop of overall coverage for the project

![screen shot 2015-07-27 at 3 28 17 pm](https://cloud.githubusercontent.com/assets/2792687/8900609/2564983a-3474-11e5-800e-b79436d58f53.png)

**Comment by gterzian** [comment]
actually @simov your issue seems to be the repo token could not be determined.

**Comment by simov** [comment]
Nope, the token is not a problem, read the entire message:

> Repo token could not be determined.  Continuing without it. **This is necessary for private repos only, so may not be an issue at all.**

It was always like that, but definitely the coverage was correct up until now.

**Comment by simov** [comment]
Oh, yeah I can't view the file sources too, but that's since forever.

Stating that:

> SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

**Comment by simov** [comment]
Now it's showing `100%` but then again that's not true either.

**Comment by simov** [comment]
Back to normal for me https://coveralls.io/github/simov/purest

**Comment by enekomartinmartinez** [comment]
@afinetooth
I have a similar problem to the one stated in this issue.
I just moved PySD's CI from Travis to GitHub Actions. The coverage seems to be updated properly, however, 0% of coverage is shown. I tried removing the repo from coveralls and some other "tricks" explained here.

My branch: [enekomartinmartinez/pysd/GHActions](https://github.com/enekomartinmartinez/pysd/tree/GHActions)

Open draft PR on PySD with the changes in CI: [PySD#288](https://github.com/JamesPHoughton/pysd/pull/288)
Actions result: [PySD Actions](https://github.com/JamesPHoughton/pysd/actions/runs/1066531233)

Thank you for your support and sorry if this issue is duplicated :)

**Comment by afinetooth** [comment]
Hi @enekomartinmartinez it looks like the `source_files` hash was empty in your POST to https://coveralls.io/api/v1/jobs. (See [API Reference](https://docs.coveralls.io/api-reference) for more info on `source_files` hash.)

To verify that (and find out why), we'll want to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) in your build logs so we can see what exact JSON is being sent to the [Coveralls API](https://docs.coveralls.io/api-reference).

Enabling [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) depends on what integration you're using, as different integrations provide different command flags or environment variables to enable it. 

Since you're using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) right now, you can add the following environment variable to your Github Action config YAML:
`NODE_COVERALLS_DEBUG=1`

That should add debug output to your next build log.

(The `NODE_` there is because the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood.)

In addition to trying that, though, I'd recommend considering this integration, since it's the most popular among python users:
https://github.com/TheKevJames/coveralls-python

**Comment by enekomartinmartinez** [comment]
@afinetooth thanks a lot for your reply.
It finally worked :)
The integration of [https://github.com/TheKevJames/coveralls-python](https://github.com/TheKevJames/coveralls-python) did not work for me, as the coverage of the lines visited with subprocesses is not taken into account. But I was able to make it work with the previous instruction (pytests --cov=pysd tests/)

**Comment by afinetooth** [comment]
HI @enekomartinmartinez glad to hear it's working.

If you run into any issues going forward, it will be a help to examine the verbose build log or share it with us so we can examine it.

If your repo is private or any info in your log is sensitive, you can email it to us at support@coveralls.io.
