### ISSUE TITLE
Coverage showing as 0%

### ISSUE THREAD

**Issue by mikefrancis** [lemurheavy/coveralls-public#589]
Just testing out Coveralls and tried it on a [small repo](https://coveralls.io/github/mikefrancis/tokenizr)

If I go into the latest build (34), I see one file has 100% coverage, yet the repo has 0%.

I'm sure this is probably just an issue with how I've got PHPUnit set up, however I'd be willing to share any fixes with the larger PHP community.

Could anyone help?

**Comment by telemachus** [comment]
I don't think that it's just your set up.

See also:

+ https://github.com/lemurheavy/coveralls-public/issues/586
+ https://github.com/lemurheavy/coveralls-public/issues/589
+ https://github.com/lemurheavy/coveralls-public/issues/590
+ https://twitter.com/telemachus/status/625392252601389057
+ https://twitter.com/BenjaminCoe/status/625403728183439360
+ https://twitter.com/BenjaminCoe/status/625404259522097152

The issue seems to be similar across all of these:

+ Actual coverage not shown. Instead 0% is shown (though tools report higher coverage, often far higher).
+ Source files are not available/uploaded. (Unsure whether that is related since one person reports that as "since forever". It's new to me and only on the repo where I have this problem, I think.)

**Comment by jimdelois** [comment]
Same here.  Coverage shows 0% despite actual coverage of 100% on my PHP project.

**Comment by lo1tuma** [comment]
Same here.

**Comment by nickmerwin** [comment]
Hi all, we're working on this now.

**Comment by bcoe** [comment]
thanks @nickmerwin. I'm projecting good vibes from the npm offices in Oakland, looks like a frustrating ops weekend.

**Comment by simov** [comment]
Now I'm getting `100%` test coverage, which would be great if it was true https://github.com/lemurheavy/coveralls-public/issues/586

**Comment by telemachus** [comment]
I'm also showing 100% coverage ([here's the latest job](https://coveralls.io/builds/3157178)). In my case it's true, but still a problem if it's just flipped from 0% to 100%!

**Comment by simov** [comment]
Back to normal for me https://coveralls.io/github/simov/purest

**Comment by jimdelois** [comment]
No change here.  Project is 100% covered, but showing 0%.  [ https://coveralls.io/github/improvframework/http-constants ]

**Comment by simov** [comment]
@jimdelois rebuild https://travis-ci.org/improvframework/http-constants/builds/72867556

**Comment by jimdelois** [comment]
@simov Yes!!  That seems to have worked for me, thanks for the tip.  I joined Coveralls over the weekend so am hoping the shaky onboarding was isolated - seems like a great product otherwise.

**Comment by nickmerwin** [comment]
Thanks @jimdelois and @simov! yeah I think the dust has finally settled from the **The Great Coveralls Migration**.

Cheers!

**Comment by SRombauts** [comment]
HI @nickmerwin I am sorry to report that the problem is still there, at least with my newly added repo  https://coveralls.io/builds/3779070

I've done some tests, removed old build results and rebuild them, but still no success.
