### ISSUE TITLE
Coverage is shown as 0% 

### ISSUE THREAD

**Issue by reflexdemon** [lemurheavy/coveralls-public#590]
I have an open source [node project slush-angular-gulp](https://github.com/reflexdemon/slush-angular-gulp) and when I pushed the builds from Travis. The build from Travis logs reports 97% coverage and https://travis-ci.org/reflexdemon/slush-angular-gulp/jobs/72813531. I am not sure if I am missing something. Please advise.

**Comment by squidfunk** [comment]
Same here. New build, 100% coverage in all individual files but total coverage shown as 0%:
https://coveralls.io/builds/3147647

**Comment by jails** [comment]
Same here for my [kahlan](https://github.com/crysalead/kahlan) repo. The 03 Jul 2015 I pushed a commit on my dev branch which reached 99.75% coverage.
Today I merged my dev branch on master (so with the same configuration and everything) and the coverage dropped to 0%.
It looks like a BC break occured in since the 03 Jul 2015.
Here is the build I'm talking about on travis https://travis-ci.org/crysalead/kahlan/builds/72825311

**Comment by leodido** [comment]
Same here.

**Comment by jimdelois** [comment]
Same here.  Coverage shows 0% despite actual coverage of 100%.

**Comment by DanielHKim** [comment]
Not sure if I have the same issue exactly but I randomly had half of the files in my repo drop to 0% for no apparent reason and it's stuck that way at the moment.

**Comment by nickmerwin** [comment]
Hey everyone, your builds should be processing as normal now. Please let me know if you see any come in still showing this behavior. 

@DanielHKim could you link me to your repo?
