### ISSUE TITLE
Coverage Shows 0% Despite 100% in Files

### ISSUE THREAD

**Issue by jimdelois** [lemurheavy/coveralls-public#592]
This project is somewhat new on Coveralls:  https://coveralls.io/github/improvframework/http-constants

Clicking into any build's source files reveals 100% coverage.  Yet for some reason, all badges and graphs show 0% coverage.  Obviously this is a very significant issue.  Please advise.

**Comment by robinandeer** [comment]
Hi,

did you get this working? I seem to have a similar issue where the build show 100% coverage but the individual job shows 0% - and badges show 0%

https://coveralls.io/builds/3572910

**Comment by SRombauts** [comment]
Exact same problem today for me here:
https://coveralls.io/builds/3779070

**Comment by nicolaasuni** [comment]
I am experiencing the same issue as detailed here:
https://github.com/lemurheavy/coveralls-public/issues/668

**Comment by sprowell** [comment]
Ditto.  All files report 100%, but overall is 0%.  Project is sprowell/he4, building on Travis and hosted on Github.

**Comment by jwillemsen** [comment]
Have a similar issue when having a directory with only C++ header files, each header has 100% but the directory stays at 0%, would expect that to be 100%, see https://coveralls.io/github/DOCGroup/ACE_TAO
![coveralls_dir](https://user-images.githubusercontent.com/47353/55797764-940a2880-5acd-11e9-87ba-287b96d54978.png)

**Comment by scalableprototyping** [comment]
Exact same problem here, any walk around?

**Comment by diehlpk** [comment]
I experienced the same problem:

https://coveralls.io/github/nonlocalmodels/nonlocalheatequation?branch=master

**Comment by afinetooth** [comment]
HI @diehlpk, while I agree that looks like a bug, I think the underlying issue is that your test coverage library considers _zero_ lines of your code relevant. (Or appears to.)

Note the columns next to each file name in the source files table: LINES, RELEVANT, COVERED, MISSED, HITS/LINE. After LINE, each of the columns is zero for each of your files:

![Screen Shot 2020-08-18 at 6 10 42 PM](https://user-images.githubusercontent.com/918667/90580605-23255700-e17e-11ea-9937-9d2a45fada64.png)

While "100% coverage" certainly doesn't feel right for those files, it's possible the algorithm is injecting some logic to _prefer_ "perfect" coverage when, as in this case, the situation is "0 LINES MISSED" and, perhaps, _Undefined_, or _NaN_, is the alternative from calculation. 

Not saying it's the best choice, but I think your use case is fixable by checking your coverage results, which I think you'll be able to resolve locally, even before getting into CI/CD.

Are you familiar with coverage library options for your language? I am not, but looking at [our community-contributed libraries for C/C++](https://docs.coveralls.io/c), I see [this project (cpp-coveralls)](https://github.com/eddyxu/cpp-coveralls), which uses [gcov](http://gcc.gnu.org/onlinedocs/gcc/Gcov.html).
