### ISSUE TITLE
Repo name with an extension

### ISSUE THREAD

**Issue by kkamkou** [lemurheavy/coveralls-public#652]
Example: https://coveralls.io/github/kkamkou/collection-json.php
Output: 403 Forbidden / Nginx
Works: https://coveralls.io/github/kkamkou/collection-json.php/

**Comment by kkamkou** [comment]
up?

**Comment by jbboehr** [comment]
I'm having this issue as well:
- https://coveralls.io/github/jbboehr/handlebars.php
- https://coveralls.io/github/jbboehr/zsql.php

If you're using nginx, a potential solution is to hard-code the script name instead of using rewrite or `location ~ \.php$`. This prevents access to any file in the docroot that isn't whitelisted by another rule.

```nginx
  location /assets/ {
  }
  location / {
    fastcgi_pass unix:/tmp/php5-fpm.sock;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /path/to/index.php;
  }
```

**Comment by kkamkou** [comment]
it looks like nobody cares. facepalm... closing it.
