### ISSUE TITLE
[Possible Security Issue] - Incorrect Commit and Build In Coverage

### ISSUE THREAD

**Issue by devdazed** [lemurheavy/coveralls-public#657]
I just added a new repo to coveralls and after running the first test run, I have incorrect information in the display.  A completely unrelated commit for a completely unrelated and unknown project is getting reported in my repo.  I know nothing of the commit reported, or the person committing.

This issue can be dangerous because not only is other peoples commit getting mixed up to other accounts, there may be (I'm hoping not), the possibility of code leakage as well. 

The build in question is: https://coveralls.io/builds/4061869

Please look into this as soon as possible, I am concerned that my code and commit and build could have ended up in someone else's account.

**Comment by anjin** [comment]
Make sure you have "service_name: travis-pro" in your .coveralls.yml.

Travis uses non-unique job id's between its free and pro services, so when Coveralls doesn't know that your service-name is Travis-pro, it looks up the info for those job ids using the free Travis API -- that's why they will show random committers, etc. The opposite cannot happen with the proper credentials, so you don't need to worry that your data is leaking out. Once your ENV var is set to specify travis-pro, the correct info will be pulled from Travis's pro API.

**Comment by devdazed** [comment]
Thanks for the quick response.  I am glad to hear that there is not data leak possibility. I currently have this in my .coveralls.yml:

service_name: travis-pro
parallel: true

And set COVERALLS_REPO_TOKEN in the Travis UI.

I am using this coveralls package: https://github.com/coagulant/coveralls-python

I’m not sure if there is anything else I should set up.
