### ISSUE TITLE
-0.0 coverage change reported with zero line net delta (+2 -2)

### ISSUE THREAD

**Issue by kortschak** [lemurheavy/coveralls-public#708]
We see a coveralls coverage reduction failure [where there is a -2 +2 change](https://github.com/gonum/internal/issues/25); this is a net zero line count change and with no change in test coverage. Note that that PR now shows no failure as we have set the coveralls failure threshold to 1% reduction being acceptable.

**Comment by arstrube** [comment]
I have a similar issue. In my case, coverage (percentage) has not changed at all (100% for the file in question), not in the least, but what did change is that in that source file, the total number of times each line was executed, dropped from 119,200 (or so) to 119,108. 

I find this is NOT a useful criterium (it might happen due to code optimization, or more efficient testing).

At least I would like to be able to disable Coveralls considering line counts when reporting coverage decrease.

**Comment by arstrube** [comment]
see https://github.com/cpputest/cpputest/pull/904

**Comment by kortschak** [comment]
Any movement on this other than a bot wanting to close it?
