### ISSUE TITLE
500 Error when attempting to push report from travis-ci

### ISSUE THREAD

**Issue by shahdewang** [lemurheavy/coveralls-public#723]
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.1.0:report (default-cli) on project algorithms: I/O operation failed: Report submission to Coveralls API failed with HTTP status 500: Internal Server Error (Coveralls API interal error)

**Comment by jdcrensh** [comment]
+1
Travis CI is reporting a 500 error from Coveralls from a previously passing build:

```
=============================== Coverage summary ===============================
Statements   : 27.94% ( 57/204 )
Branches     : 5% ( 2/40 )
Functions    : 6.82% ( 3/44 )
Lines        : 31.15% ( 57/183 )
================================================================================
Done

/home/travis/build/jdcrensh/node-force-coverage/node_modules/coveralls/bin/coveralls.js:18
        throw err;
              ^
Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
npm ERR! Test failed.  See above for more details.
```

**Comment by kujenga** [comment]
+1 for us as well, we're seeing the same error

```
Bad response status from coveralls: 500 - {"message":"Build processing error.","error":true,"url":""}
```

**Comment by desilinguist** [comment]
Same for [us](https://github.com/EducationalTestingService/skll) since this morning, pretty much.

**Comment by shahdewang** [comment]
Issue progress status: http://status.coveralls.io/

**Comment by at15** [comment]
@kujenga have you fixed the problem for [goveralls](https://github.com/mattn/goveralls)? I am still getting same error, see https://travis-ci.org/at15/overalls/jobs/144131942#L177 . Thanks~

**Comment by kujenga** [comment]
@at15 I'm pretty sure this was an issue with the Coveralls backend rather than with the goveralls tool itself. It doesn't look like there are any reported issues ongoing though: http://status.coveralls.io

Since code coverage reports are a nicety for us rather than a necessity, we just modified our CI configuration to not fail when coveralls is down. e.g.

```bash
goveralls || echo "push to coveralls failed"
```

**Comment by at15** [comment]
@kujenga thanks a lot, I put the coverage report in `after_success` for travis_ci, I guess I need more commit and some of them might work XD.

**Comment by valendesigns** [comment]
This issue is back for me. Any idea how to address this?
https://travis-ci.org/wptide/wptide/builds/433176187#L620

**Comment by waterplea** [comment]
Starter happening for me today on 2 different projects. Also login with Github redirects to 500 error page.

**Comment by nickmerwin** [comment]
Hi @waterplea, sorry about that -- we had a Redis server outage earlier today and are back to normal now.

Thanks.

**Comment by NullVoxPopuli** [comment]
I've been getting 500 errors for the past couple hours. Did Redis barf again?

**Comment by AbhigyanKumar** [comment]
This issue is still there. How can I prevent this? https://coveralls.io/builds/33837967/source?filename=format.go

**Comment by afinetooth** [comment]
Hi @AbhigyanKumar. I can't find the build associated with that build URL:
https://coveralls.io/builds/33837967

By that I mean, either in the web UI or in our database. That indicates to me that if it did exist, it's been deleted. Can you double-check the build ID there to verify?

Also, this version of 500 error relates to a failure response (system error) from our API. If you're talking about getting a 500 error when requesting a source file through the web UI, this is the relevant issue:
https://github.com/lemurheavy/coveralls-public/issues/1426

If the issue is with a Gitlab repo, I'm looking into that for you and will reply there.

**Comment by AbhigyanKumar** [comment]
I fixed it. Thanks!
