### ISSUE TITLE
Golang + TravisCI + Version "tip"

### ISSUE THREAD

**Issue by andygrunwald** [lemurheavy/coveralls-public#745]
Hey,

I have a Golang Repo at https://github.com/andygrunwald/go-jira
TravisCI offers a `tip` version of Golang. This is the latest golang version available.
A typical travis ci file could look like:

```
language: go

sudo: false

go:
  - 1.4
  - 1.5
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
```

But with this the push to Coveralls fails with `Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}`.
See https://travis-ci.org/andygrunwald/go-jira/builds/118809127

When i switch `tip` to `1.6` everything is fine. Here is the complete travis ci file:

```
language: go

sudo: false

go:
  - 1.4
  - 1.5
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
```

The commit is here: https://github.com/andygrunwald/go-jira/commit/d41b1618b8cc81ead62f4277b7dfaf05fd3ab592
The TravisCI build here: https://travis-ci.org/andygrunwald/go-jira/builds/118809444

**Comment by dsoprea** [comment]
I was getting this error too, but it wasn't version specific. 

Due to my lack of familiarity, I had created a token under the "Personal API Tokens" area of the account settings. Instead, I should've taken the repository-token from the page for the specific repository (under Coveralls). Also, defining a token is not necessary with Travis-CL+Coveralls.
