### ISSUE TITLE
Don't report coverage until all builds are finished

### ISSUE THREAD

**Issue by lbergelson** [lemurheavy/coveralls-public#761]
We have a travis build matrix that runs several builds for each commit and then uploads coverage from each of them.  This makes our master branch coverage badge jump erratically from 13% -> 84% and back.   It also means every pull request gets a stream of "coverage has decreased comments"

What we need is a way of having each build register with coveralls and say "I am currently building, don't report coverage until I am complete"  That way each travis build could initially register itself, and coveralls would wait for all builds to finish before reporting any coverage. 

See https://github.com/lemurheavy/coveralls-public/issues/491 for other people having a similar issue.

Is there any possibility of adding this feature?  We're thinking of removing our badge/potentially dropping coveralls since the wildly fluctuating numbers cause a lot of pull request spam, and the badge showing 13% makes us look bad.

**Comment by devurandom** [comment]
I have some questions regarding your setup, since I am also trying to setup a build matrix with coveralls:
* Do you somehow merge the coverage results of your builds, or do you just run `coveralls` once for each build?
* Is there a way to insert an indicator into the report, *which* build I am looking at? I am testing with several different versions of the language runtime, and would like them to be tagged with the respective version number in coveralls, and comparisons should also only happen per version-number and not averaged over all versions. Do you know whether that is possible?

**Comment by lbergelson** [comment]
@devurandom Since I never got a satisfactory resolution to this problem I ended up switching to [codecov.io](codecov.io).   
It has two features that address these problems. 
1. It knows about the travis matrix and will wait until all the builds are done before reporting coverage 
2.  It lets you add tags to your builds and then display coverage by tag.

It's possible that coveralls lets you do this now, but as I said, we never heard back from them and ended up switching to a more responsive service.

**Comment by devurandom** [comment]
Independently of you, I also switched to Codecov, because on Coveralls I had trouble submitting some of my test results (I'd get a server error after the first requests were successful).

Thanks for the hint with "tags" (they call them "flags" in their documentation; one specifies them by passing the command-line flags `-F myflag` to their uploader) - that will help a lot with [CircleCI](http://circleci.com/), where I am using [CircleCI Matrix](https://github.com/michaelcontento/circleci-matrix) to create a build matrix.

**Comment by lbergelson** [comment]
Oh, CircleCI matrix looks interesting, that might be a convinient bridge for projects that want to move from travis to CircleCi.

**Comment by devurandom** [comment]
Flags (`-F ...`) only allow `\w` characters. Thus I went with setting the build name (e.g. `-n "Language v1.2.3"`) and attaching some environment variables (`-e BUILD_VARIANT`), which makes CircleCI look pretty much the same as Travis on the coverage side.
