### ISSUE TITLE
Continuous pending status is Travis does not send coverage

### ISSUE THREAD

**Issue by Soullivaneuh** [lemurheavy/coveralls-public#795]
We set up a rule to not run check and exit directly if no php file is modified.

In this case, a Coveralls status appears anyway and is stuck on pending:

![image](https://cloud.githubusercontent.com/assets/1698357/15869979/ef988f4e-2cee-11e6-9a34-e571657375af.png)

Any idea of why?

**Comment by aeschylus** [comment]
Any word on this? It has been useful for us to monitor checks through github's interface. It would be a shame to have to move to something like codecov.

**Comment by aeschylus** [comment]
This particularly occurs when accepting pull requests from forks, a fairly important process in which to reduce friction.

**Comment by dwasyluk** [comment]
Any updates here? We're hitting this too after migrating from the legacy integration to the newer app on GitHub...

**Comment by bytewalls** [comment]
This is happening because you have coveralls set as a required check in your github settings. Github creates the status even though coveralls will not be reporting. You can tell this because of the github generic pending status of `Waiting for status to be reported` as opposed to `'Coverage pending from Coveralls.io'` which is what coveralls will send for a pending status.
