### ISSUE TITLE
Builds of master branch not picked up, other branches work well

### ISSUE THREAD

**Issue by ghost** [lemurheavy/coveralls-public#845]
https://coveralls.io/github/darkwebdesign/symfony-transformers

On my dashboard it displays "MASTER: 100%" and "DEFAULT BRANCH: MASTER", but the master branch is not displayed anywhere and the list of builds and the number of builds only display builds of other branches.

Also the badge is displaying "coverage: unknown".

I'm using Travis CI for building, and the build process/scripts of the master branch are identical to the ones in the 1.4 branch.

**Comment by raymondschouten** [comment]
I tried to delete my Github repository and to re-setup everything again, but I can't disable or turn on the listed repositories. Even deleting my account didn't help.

**Comment by raymondschouten** [comment]
Above comments are mine... After recreating my Github account with the same username "raymondschouten" and same company "darkwebdesign", everything is messed up within coveralls.

1. Deleting my account is not deleting any repository information
2. I can't disable repositories after enabling them
3. My repositories are not picking up any builds anymore, probably because they are still connected to the old Github account
