### ISSUE TITLE
Coverage dropped after refactoring exact same tests into different files

### ISSUE THREAD

**Issue by bbyars** [lemurheavy/coveralls-public#929]
Hi there,
On [this commit](https://github.com/bbyars/mountebank/commit/0008be7b78e5577e1a925f7fc39e8c47f19a8361) and [the next one](https://github.com/bbyars/mountebank/commit/ddf83e005592a22bb79bfa6207e707930f3dcb73), I did (mostly) nothing other than to split large test files into multiple files. The new files contain the same tests; however, the coverage in coveralls.io dropped precipitously, from 94.91% to 76.75% after the first commit, and to 68.48% after the second (builds 1313 and 1314 on the [dashboard](https://coveralls.io/github/bbyars/mountebank).

Running coverage locally shows 95.95% (`./node_modules/.bin/istanbul cover grunt mochaTest:unit`). I run coveralls through Travis as

````
./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly test/**/*.js -- -R spec  && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
````

**Comment by danielhoherd** [comment]
I had a similar issue where coveralls showed a golang coverage reduction from ~30% to ~13% after renaming unused variables to `_` and removing an unnecessary `break` in an `if ... else` block, which were both suggested by a linter. 🤷‍♂️

My confidence in this tool also dropped accordingly.

**Comment by afinetooth** [comment]
Hi @danielhoherd. I'm sorry to hear about that. I'd be happy to have a look at your project builds to see if I can determine the reasons for those changes. It would help us, too, to understand those so we can rule out any issues with our aggregate coverage calculations.

Regarding this particular issue, a lot has changed since 2017 in terms of our support for `Go` via-a-vis the common coverage report formats for `Go` and other languages. In 2017, we only had two native integrations: one for Ruby that supported Simplecov format reports, and one for Node/JS that supported LCOV format, to which you'd need to convert your original format reports. Back then, the best support for particular languages came from our 30+ community-created [language integrations](https://docs.coveralls.io/integrations#language-integrations). But we have since introduced a number of [official integrations](https://docs.coveralls.io/integrations#official-integrations), which in actuality are one integration ([Coverage Reporter](https://github.com/coverallsapp/coverage-reporter)) and two extensions for popular CI services (a [GitHub Action](https://github.com/marketplace/actions/coveralls-github-action) and an [Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls)), both of which use the Coverage Reporter integration under-the-hood.

The reason I mention this is that our users have more options now for integrations, covering [more coverage formats](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#supported-coverage-report-formats), and what is especially helpful about our [official integrations](https://docs.coveralls.io/integrations#official-integrations) is that we maintain them so they've been built in lockstep with our API, and they allow us to support your entire toolchain.

The last thing I wanted to say is that Coveralls doesn't make any interpretations about, or changes to, the data in your original coverage reports. So barring an issue of conversion at the integration level, your coverage stats at Coveralls should be identical to those in your original reports, and we can easily verify that now, as we store your coverage report uploads for 90-days for the purpose of comparison.

**Comment by danielhoherd** [comment]
Thank you for the info @afinetooth. I submitted a support ticket, and then realized we are not using the official integration, so that's something I'll have to fix on my end. I don't think this thread is the right place to continue discussing my issues though for a variety of reasons, but hopefully your links serve others like me who search for reasons that coverage could drop and find this thread.

**Comment by afinetooth** [comment]
Hi @danielhoherd. My pleasure.

> [...] then realized we are not using the official integration, so that's something I'll have to fix on my end.

You can definitely hold off on that for now as it's not a requirement unless we turn up an issue with your current integration. 

> I don't think this thread is the right place to continue discussing my issues

I agree. Primarily because you are a member of an org with a paid Coveralls subscription, so you can get direct support from support@coveralls.io, and your project data will remain private through that channel.

So, yes, please let's continue via support@coveralls.io.

I will keep this issue closed because: 
- The details of such issues are case-by-case, and one answer won't necessarily be relevant to the next reader. 
- More important are details around how to approach examining the root causes of coverage drops, which is handled better in some more recent issues about this same subject, like [this one](https://github.com/lemurheavy/coveralls-public/issues/1746#issuecomment-2319040030).
- This issue will still come up in Google searches and keyword searches here.
