### ISSUE TITLE
Coveralls not picking up new branches

### ISSUE THREAD

**Issue by itsterry** [lemurheavy/coveralls-public#97]
We have a fairly busy private repo at Github, and we start new branches regularly.

Coveralls seems to be stuck about a week behind, and hasn't picked up any of the new branches. If it helps, it gets changes to the ones it knows about already just fine.

Is there any way to nudge it and say (for instance) "Go look at branch v3.x" ?

**Comment by drewzh** [comment]
I've been struggling to get my repo to sync branches or even find the badge in the README.md.  Did you ever get anywhere with this?

**Comment by yanickrochon** [comment]
I come across the same problem, too. A new push shows `unknown` on the bagde. When going on to Coveralls, the project has no branch anymore. I tried resetting the source, sync'ing with Github, nothing works. This is a personal, public, repository and coverage worked before.

If it helps, I am noticing this since I created a dev branch for a new feature, then merged it to master. Now, I removed the dev branch (as it was behind anyway) and the last push shows `unknown` coverage. It is passing just fine on Travis CI.

**Comment by devinivy** [comment]
I'm having the same issue while getting started with coveralls.

**Comment by bstopp** [comment]
Experiencing the same issue myself; project is: https://coveralls.io/github/bstopp/puppet-aem

**Comment by cjsauer** [comment]
Still experiencing the issue 3 years later. Is anyone reading these issues?

**Comment by barczaG** [comment]
+1

**Comment by zoechi** [comment]
I was missing a branch as well a few days ago. It showed up eventually for no apparent reason.
Now I have it again. the `develop` (default branch) is not showing up and Coveralls presents the coverage information generated for `develop` as coverage for `master`.

**Comment by itsterry** [comment]
Hmmm. It's been 5 years since I opened this ticket.

Doesn't look like anyone at Coveralls is on it.

I'm closing it to get it off my list. Feel free to open a duplicate ticket, anyone...

**Comment by NathanWailes** [comment]
I seem to be encountering the same issue.
